### ISSUE TITLE
import events while keeping event id and attribute dates

### ISSUE THREAD

**Issue by Deventual** [MISP/MISP#1009]
Hi all,

I have two instances of MISP:
the first is 2.3 and the second is a new one - 2.4.23.
I want to import events from the 2.3 instance, however I need to maintain several elements:
1. the event id number
2. the dates of the attributes
3. all the attachments and metadata.
4. if possible it will be nice to keep the creation comments.

I tried to export as OpenIOC and it changed the event id,
I also tried to export as MISP xml and after importing it,
I changed the databases with the event id values in the events and attributes tables,
this method worked but I fear that I'm missing something...
Is there another way to do so, without me needing to modify the DB by my self?

Best regards,

**Comment by iglocska** [comment]
Is using the synchronisation mechanism of MISP an option? 2.4.23 can pull from 2.3 so you could just set up a sync-link and pull the data from the 2.3 instance.

**Comment by Deventual** [comment]
This way it will keep the event id nubmers?
it is crucial for my system.
If i do it in the edit-database way, should i need to change any more tables?

**Comment by iglocska** [comment]
The event IDs will indeed not be kept, that is tricky. Editing the database can get especially nasty since all of the relations use the ID as a foreign key (attributes, shadow_attributes, correlations, threads, event_tags, etc). If you go down the database route, you'll have to edit any event_id field that you come across in the other tables, I'd strongly recommend against this. 

MISP is not meant to keep the ID numbers the same across systems, we have UUID field on both the event and attribute level that persists through the synchronisation.

**Comment by elhoim** [comment]
@Deventual & @iglocska can be closed?
