### ISSUE TITLE
Event.php trying to unset causes fatal error

### ISSUE THREAD

**Issue by I-am-Sherlocked** [MISP/MISP#1019]
Line 1754 in app/Model/Event.php
`unset($data['Event']['Attribute'][$k]['SharingGroup']);`
needs to check whether the value is set before trying to unset it.
`if (isset($data['Event']['Attribute'][$k]['SharingGroup']))`

Unsetting without verifying that it's set is throwing fatal errors. Encountered when doing an import.

**Comment by iglocska** [comment]
I see, that is a good point. Instead of checking whether it is set I've moved it into the conditional (distribution == 4 should always have a sharing group). 

Thanks for the heads-up, let me know if you still get the error even after the fix (which would mean that something went wrong at an earlier step).

**Comment by I-am-Sherlocked** [comment]
Yes seems to have fixed it :)

**Comment by iglocska** [comment]
Excellent, let us know if you run into any other issues!
