### ISSUE TITLE
CTI Feeds

### ISSUE THREAD

**Issue by honey4free** [MISP/MISP#1073]
Hi is it possible to add feeds like https://www.spamhaus.org/drop/ to MISP and use it as a feed tool.
We wan't to have feeds in MISP With Our threat databse-

**Comment by cvandeplas** [comment]
Personally, I'm not sure if MISP should be used as a tool to import massive external databases. 
Technically it will work, however you might encounter performance issues because of the correlations and such. 
CIF (http://csirtgadgets.org/collective-intelligence-framework/) is better at combining automated massive feeds to new feeds. 

The spamhaus list is however rather small, so today you could use PyMISP to automatically import the data using an external python script.
Once the modular import/export part of MISP is finished this could probably be also done on MISP-side.

**Comment by adulau** [comment]
I see multiple options: 
- Creating a lookup against the spamhaus RBL services using misp-modules (if the list is really huge but the spamhaus drop file seems quite small)
- Like @cvandeplas mentioned, a simple PyMISP import script could do the job

I might have a look at creating a misp-module for RBL check.

**Comment by xsallowed** [comment]
What is the recommended sources of integration for MISP?

**Comment by Rafiot** [comment]
What do you mean? You can enable the OSINT feeds for example.

**Comment by rotanid** [comment]
as there was no answer for over two months, we're closing the issue.
feel free to reopen, if you want to work with us on it.

as adulau wrote regarding the original question: that can be achieved with a PyMISP import script.

**Comment by adulau** [comment]
@honey4free In the recent version of MISP (starting from 2.4.52 - http://www.misp-project.org/2016/10/07/MISP-2.4.52-released.html ), you can easily import feed (CSV, free-text) in MISP.  Looking at the DROP feed, it could be even something that could be add in the warning-list too.
