### ISSUE TITLE
Failed to Load GPG

### ISSUE THREAD

**Issue by rjsecurity** [MISP/MISP#1145]
1) Unable to get GPG running.  the diagnostics tab of MISP says FAIL: Failed to load GPG.
2) I want to actively receive MISP updates, please advise how can i achieve this

Please help.

**Comment by iglocska** [comment]
There could be several reasons for this. 
1. Is GnuPG installed correctly?
2. Is CryptGPG installed correctly?
3. Can you check if your GPG settings are correct in the MISP settings? (Just try to use the same homedir / credentials to sign a test message via the command line).

**Comment by rotanid** [comment]
as there was no answer for over two months, we're closing the issue.
feel free to reopen, if you want to work with us on it.

**Comment by vpistillo** [comment]
After follow the installation istruction 'xINSTALL.centos7.txt' I have installed MISP v2.4.55.
In /servers/serverSettings/diagnostics I have the following errors:
1) GnuPG installation and settings....FAIL: Failed to load GPG	
2) PHP CLI Version (>5.6.0 recommended): 5.4.16 (Version unsupported, update ASAP)   
Well, with Centos7 if I try to update the php-cli package i receive: Package php-cli-5.4.16-36.3.el7_2.x86_64 already installed and latest version.
Could you help me to fix these two problems 
Thanks in advanced.

**Comment by RichieB2B** [comment]
For issue 1 is check the error.log for details. It could be a number of things.
Issue 2 is due to the fact that CentOS 7 ships with PHP 5.4.16 but MISP needs 5.6.x. So during installation you installed a new version in /opt/rh/rh-php56/root/usr/bin/php
The PHP CLI check the MISP diagnostics page runs just uses the normal ```$PATH``` so it finds PHP 5.4.16 instead. As long as you have used ```scl enable rh-php56 '....'``` in ```/etc/rc.local``` you should be fine.

**Comment by iglocska** [comment]
Ah my bad, need to fix the check.

**Comment by RichieB2B** [comment]
If ```/usr/bin/scl``` exists you could run ```scl enable rh-php56 'php -v'``` or better yet, detect which php scl package is installed first by running ```scl -l | grep php``` which on my system returns ```rh-php56```

**Comment by iglocska** [comment]
Sounds like a plan!

**Comment by ppanero** [comment]
Im having a similar issue (FAIL: Failed to load GPG). If I am not mistaken that can only be due to (line 2798 of Server.php): 
```php
try {
    require_once 'Crypt/GPG.php';
    $gpg = new Crypt_GPG(array('homedir' => Configure::read('GnuPG.homedir'), 'binary' => (Configure::read('GnuPG.binary') ? Configure::read('GnuPG.binary') : '/usr/bin/gpg')));
} catch (Exception $e) {
    $gpgStatus = 2;
    $continue = false;
}
```
The fact is that the exception can be rised only by the require_once and I tested with: 
     ```scl enable rh-php56 'php -a'``` 
and then perform the require and it does not fail.

I read something on the gpg key having a passphrase, is that an inconvenient? (just in case, tried both with and without passphrase)

EDIT: also running the gpg-agent on the directory

**Comment by ppanero** [comment]
Fixed. It was a selinux issue. Plus the passwordless. As doc in case someone runs into the same again:
### GnuPG

To set up GPG fist you need to generate a gpg key with:
```bash
gpg --gen-key
```
Note that the email should be the email set up in the GnuPG part of the configuration (gpg_email parameter), and the same applies for the password (gpg_password parameter). There are known cases of errors when using it with a password (instead of passwordless as in the default configuration). If it gives an error run is as root.

Then move the key to the directory set up as home directory (gpg_homedir parameter), set apache as owner and group and the selinux context httpd_sys_rw_content_t. 
```bash
mv ~/.gnupg /var/www/MISP/
chown -R apache:apache /var/www/MISP/.gnupg
chcon -R -t httpd_sys_rw_content_t /var/www/MISP/.gnupg
```

Finally export the public key to the webroot
```bash
sudo -u apache gpg --homedir /var/www/MISP/.gnupg --export --armor YOUR-EMAIL > /var/www/MISP/app/webroot/gpg.asc
```

**Comment by jimanderles** [comment]
Hi! 
I have the same problem with PHP, I  installed the version 7.2 and the result on the console is:
-------------------------------------------------------------------------------

```
php -v
PHP 7.2.13-1+ubuntu14.04.1+deb.sury.org+1 (................................
```

-----------------------------------------------------------------------------------
But the result on the Misp page is:
-----------------------------------------------------------------------------------
PHP Settings
PHP ini path:… /etc/php5/apache2/php.ini
PHP Version (>7.0.16 recommended): 5.5.9-1ubuntu4.26 (Version unsupported, update ASAP)
PHP CLI Version (>7.0.16 recommended): 7.2.13-1+ubuntu14.04.1+deb.sury.org+1 (Up to date)

----------------------------------------------------------------------------------------------------------
The PHP ini path is rong, because the new path is on: /etc/php/7.2/apache2/php.ini

Someone knows how to change the path route?

Thanks.
