### ISSUE TITLE
bug in search() in AttributesController?

### ISSUE THREAD

**Issue by rotanid** [MISP/MISP#1156]
in AttributesController.php there is the method search().
inside, there is the following loop:

```
foreach ($orgArray as $orgArrayElement) {
...
}
```

but **after** this loop there is some fiddling with $saveWord and $i which the other foreach-loops in the search-method have inside their loop-body.
looks like a bug to me, but i'm not that far into the code so i don't do a PR for this.

**Comment by iglocska** [comment]
This is indeed correct. The code outside of the foreach loop should set the description string for the search result, which in this case only stores the last searched for org name.

This results in the header text saying something like "search results for the organisation(s) org3" instead of "search results for the organisation(s) org1, org2, org3".
