### ISSUE TITLE
Statistics on taxonomy and tag usage

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1158]
We have a nice API for getting the statistics for the categories and the attributes usage. A similar approach to get the taxonomy and tag usage could be very handy.

**Comment by iglocska** [comment]
Fixed in 21111498c3aec08f87da244db99d8efb4aaf1155

Just go to: 

mymisp/tags/tagStatistics/[percentage]/[name-sort]

Both parameters are set to false by default. Name-sort, when set will sort by the namespace, otherwise the sorting will happen on the value. Percentage will switch between exact count and percentage.

For example to get the exact count stats for the tags, sorted by namespace use:

mymisp/tags/tagStatistics/false/true
