### ISSUE TITLE
Add ip range attribute type

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#126]
Have IP range attribute under network activity

Possible entry notation types: CIDR (1.2.3.0/24), range between two IPs (1.2.3.0-1.2.3.255), partial range for last byte (1.2.3.0-255).

**Comment by elhoim** [comment]
Just adding this comment that came up during a verbal discussion:
If the correlation is changed from a simple equality of values to something more evolved:
- ip in IP range (like listed above);
- hostname from domain (as described in #117);
- overlap between a path with filename and a standalone filename; 

then it does not break realational intelligence.
This might require to have correlations not to be created exactly at the attribute creation time, but in a separate loop/queue that gets picked up by workers.

**Comment by adulau** [comment]
FYI an experimental CIDR correlation is now available https://github.com/MISP/MISP/commit/c8a0b0d870a5ece886d089cfe702b9c0db9b0c57

**Comment by ping-gtm** [comment]
I still don't find an attribute type 'ip-range'. If I am importing an ip range like 192.168.0.1-192.168.0.10 using a py misp script that ingests the ioc's from an excel file (very large data set) then it throws error. Because single ip or cidr is fed into ip-src or ip-dst but range cannot be inserted it fails . Because there is no such attribute type as ip-range . Requesting urgent attention to this or the possible work around.
