### ISSUE TITLE
Problem with TLS>=1.1 and php 5.5.9 while syncing MISP instances due to bug in php

### ISSUE THREAD

**Issue by michael-kerscher** [MISP/MISP#1290]
### Work environment

| Questions | Answers |
| --- | --- |
| Type of issue | Bug in Cakephp |
| OS version (server) | Ubuntu 14.04.4 LTS |
| OS version (client) | Ubuntu 14.04.4 LTS |
| PHP version | 5.5.9-1ubuntu4.17 |
| MISP version / git hash | 2.4.39 |
| Browser | not browser related |
| Cakephp | 2.8.3-7-g79db545 |
### Expected behavior

Sync two MISP instances with TLS>=1.1 and the given versions
### Actual behavior

If the remote server of the sync has no TLS 1.0 support and you run a connection test you get the following message "Server unreachable".
### Steps to reproduce the behavior

Use the above stated versions (especially php) and disable TLS1.0 on the remote server

After lots of debugging I figured out that php tries to create a connection with stream_socket_client and upgrade the connection with stream_socket_enable_crypto([...], STREAM_CRYPTO_METHOD_TLS_CLIENT).

If you look at the network traffic you will see a TLS1.0 connection request which just fails...

The problem is this bug https://bugs.php.net/bug.php?id=65329 (tl;dr TLS_CLIENT => TLS 1.0 only!)   and counter intuitively  SSLv23_CLIENT => all versions (yes, including TLS 1.1 and 1.2!)
### How to fix it

As a workaround you can use this patch on cakephp... (which unfortunately will also allow the usage of SSL2 and SSL3 so be careful with this!)
https://gist.github.com/michael-kerscher/cf332e0782ec3e6ccde38c6ab5ffdd52

**Comment by RichieB2B** [comment]
Nice find. Since the solution is a CakePHP patch, can you open a PR there? https://github.com/cakephp/cakephp/tree/2.x make sure you use the 2.x branch so MISP can benefit from it. 

According to http://php.net/manual/en/migration56.openssl.php PHP 5.6 interprets the STREAM_CRYPTO_METHOD_TLS_CLIENT flag to select any TLS version which currently is 1.0, 1.1 or 1.2. CakePHP uses this when tls:// is used with enableCrypto, see https://github.com/cakephp/cakephp/blob/2.x/lib/Cake/Network/CakeSocket.php#L95
So your patch should only switch to sslv23 for PHP_VERSION < 5.6.0

**Comment by adulau** [comment]
This should have been fixed.

We will close this issue. If the issue persists, feel free to reopen the ticket.
