### ISSUE TITLE
NOT FOUND - /users/login was not found on this server

### ISSUE THREAD

**Issue by avivos120** [MISP/MISP#1304]
Hi.

i using ubuntu 16.04.
installed by :
https://github.com/MISP/MISP/issues/1195

open localhost in browser and get Not found, url /users/login was not found on this server.

well, i enable the rewrite.

what should i do?

**Comment by cristianbell** [comment]
Hi, 

if you followed the instruction in the #1195 than the rewrite should be enabled. But maybe take a look at our [official Ubuntu 16.04 installation guide](https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt).

Also make sure you update the basepath ('baseurl' => '') in /var/www/MISP/app/Config/config.php. 

Otherwise you could paste here your misp.conf so we can see it..

**Comment by avivos120** [comment]
Well, i installed now from :
https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt

i just didnt used a ssl commands..
and still same problem..
rewrite enable.

i did every step on the installation guide except ssl parts...

**Comment by cristianbell** [comment]
so instead of the line `sudo a2enmod ssl rewrite` you used `sudo a2enmod rewrite`? 
can you please run `apache2ctl -M` and see if module_rewrite is really enabled? 

Also, how does your misp.conf some look like? either paste it here or send it in a message. 

And offtopic: are you installing MISP for yourself, or for a user community?

**Comment by adulau** [comment]
@avivos120 Did you review your Apache configuration for the virtual host configuration? Are the hostname matching the ones resolving in your DNS?

**Comment by avivos120** [comment]
@cristianbell 
i did : sudo a2enmod rewrite
apache2ctl -M :
...
~ rewrite_module (shared)
...

what is misp.conf , i didnt saw that file, i edit some conf files from the tutrial
i install for my self..

@adulau , 
its for localhost only so in all i put a localhost..

**Comment by cristianbell** [comment]
oki. 

you should have at least 1 website configuration file - such as misp.conf or default.conf.. 

Also, maybe too much work (sorry), but can you try installing using this script: [https://github.com/da667/AutoMISP/blob/master/auto-MISP-ubuntu.sh](https://github.com/da667/AutoMISP/blob/master/auto-MISP-ubuntu.sh) 
Thanks!
