### ISSUE TITLE
CSV for API export seems to not show all entries

### ISSUE THREAD

**Issue by Kafeine** [MISP/MISP#1312]
Not sure if it's a bug or expected
### Work environment

MISP 2.4.48 - Mysql 5.7.11
### Expected behavior

Using CSV API export  to get access to all entries like for instance :
domain|ip  field
### Actual behavior

Fields like domain|ip are not there while it's in CSV_ALL from the main Export page.
### Steps to reproduce the behavior

Create an event with an attribute Network Activity : domain|ip
Then try and CSV download it with API using :
/events/csv/download
or
/events/csv/download/false/false/false/false/false/true/  where true is :
"includeContext: Include the event data with each attribute."

**Comment by iglocska** [comment]
Hmm, it works for me. Keep in mind that the only things exported by default are attributes marked "to IDS" (otherwise it behaves like CSV_sig from the export page)- if you would like to override that, set the "ignore" parameter to true (it stands for ignore export rules):

/events/csv/download/[event_id]/[ignore]/...

So if you would like to download a csv with all attributes, no matter the IDS flag that is tagged "privint", you'd use the following url:

https://mymisp/events/csv/download/false/true/privint

Let me know if that wasn't the issue though! Also, let's keep this issue open for now as the CSV export only doesn't seem to support passing parameters via a POSTed JSON object and I hate having search parameters being passed through the URL.
