### ISSUE TITLE
Display event using UUID not working if UUID's first numbers equals to an real ID

### ISSUE THREAD

**Issue by r-anthony** [MISP/MISP#1338]
Hi,

I am using the "display event using UUID" features (https://github.com/MISP/MISP/issues/88)
but I think there is a bug : 

I have an event with uuid = 577a061ee-9158-4b5e-8a8e-aca8950d2109 and when I go to :
   https://myurl.com/events/view/577a061ee-9158-4b5e-8a8e-aca8950d2109
it displays : 
Event ID 577   with Uuid 5491454c-0308-4270-b33b-459d950d210b  

Easy to reproduce, just go to 
https://myurl.com/events/view/549withanyletters

==> it works because event ID 549 exists

If I go to https://myurl.com/events/view/5490withanyletters
==> it doesn't work because event ID 5490 doesn't exist

Do you need any more informations ?

**Comment by rotanid** [comment]
i may have found the issue, why the wrong event is shown instead of an error, see #1339

but your UUID "577a061ee-9158-4b5e-8a8e-aca8950d2109" should be wrong because it has 37 characters, the first part has 9 characters but UUIDs only have 8 there (and 36 in total) according to RFC4122.
are you sure about that UUID and if yes, which MISP version are you using?

**Comment by jls31** [comment]
Hi,
Thanks for your quick help. r-anthony is busy but i can follow the discussion.

I have verify for the uuid and you are right. If we give a correct uuid "577d2550-f798-48fb-8cbb-70d15b86d7e5" (8 char for the first part) the correct event is returned. We’ll implement a regexp to fix the problem in our side. 

The only remark that I can add is that the return message should be an error message of type “wrong uuid” instead of the event with id 577. For example:
- when we call: https://myurl.com/events/view/577dd2550-f798-48fb-8cbb-70d15b86d7e5  => the event with id = 577 and uuid = 5491454c-0308-4270-b33b-459d950d210b is returned.
- when we call https://myurl.com/events/view/577d2550-f798-48fb-8cbb-70d15b86d7e5  => the event with id = 2625 and uuid = 577d2550-f798-48fb-8cbb-70d15b86d7e5  is returned.

The error comes from the two char "dd" in the first part of the uuid instead of one char "d".

**Comment by iglocska** [comment]
Right now it is corrected, basically what it will do:

Enter an invalid / malformed UUID or an invalid ID: It will correctly return event not found.

Just git pull to get the fix. Thanks a lot for letting us know!
