### ISSUE TITLE
CertAuth Plugin not working as expected

### ISSUE THREAD

**Issue by infde6** [MISP/MISP#1360]
Hello,

We are attempting to configure the CertAuth plugin and are having issues identifying how the fields are supposed to be mapped. Could anyone provide an explanation of which fields are from the certificate and which fields are from MISP?

For troubleshooting, we are able to successfully query certificate information, but are unable to get responses from MISP. Are the User Class and Field from LDAP?

Thanks in advance to any clarification, and thank you Alexandre Dulaunoy (adulau) very much for providing the plugin!

**Comment by RichieB2B** [comment]
The CertAuth plugin doesn't use LDAP. See https://github.com/MISP/MISP/tree/2.4/app/Plugin/CertAuth for the documentation.

**Comment by infde6** [comment]
Understood, and the documentation was used for reference. There's no indication of where the User Class and User Field values are coming from. If they are supposed to be in the certificate, our company does not use those values.

**Comment by RichieB2B** [comment]
Where do you see User Class and User Field when you use this plugin? I have set up CertAuth recently and I don't recall seeing either terms.

**Comment by infde6** [comment]
They're in the comments in the configuration example.

**Comment by RichieB2B** [comment]
Now I see them. :-) The User Model refers to the CakePHP model and User is the right value for MISP. The User Field (UserModelKey) defines how the Users table is queried. The value to search for is extracted from the SSL certificate via the map lookup. I don't use unique nids_sid in MISP (nor store them in the SSL cert) so I changed it to email (which is in my SSL cert).

This actually makes me think the example in the README.md is wrong because it does not extract the nids_sid from the SSL cert using the map. Perhaps @capile or @iglocska can clarify.

**Comment by iglocska** [comment]
I am not entirely sure either, have to look into it. 

You seem to be spot on though @RichieB2B, it indeed looks like it's not using the nids_sid. From what I can tell after a quick glance, it maps id, name, org, email from the certificate into $client and then uses either the UserModelKey as the lookup value or if it's not set it uses the $user array as the condition (I need to look into this how that actually works, I assume cake does some magic and will end up using ID?).

**Comment by infde6** [comment]
Thanks to everyone for the responses.

We were not able to get CertAuth working in our infrastructure, but were able to get LDAP and AD working.
