### ISSUE TITLE
Sync Actions => List Server => error message in my VM

### ISSUE THREAD

**Issue by hibouu** [MISP/MISP#1414]
When I look at admin menu bar the Sync Actions menu => List Server, I have an error message in my VM (see screenshoot). 
### Work environment

VM => https://www.circl.lu/assets/files/misp-training/newtraining.ova
on Max OS X.5.5
| Questions                 | Answers
|---------------------------|--------------------
| Type of issue                | Bug, Question, 
| OS version (server)      | ubuntu4.14
| OS version (client)       | 
| PHP version                | PHP Version 5.5.9-1 

| MISP version               | 2.4.9
| Browser                      | Chrome Version 51.0.2704.103 (64-bit)
### Expected behavior

View the List Server 
### Actual behavior

Error message, see screenshot. 
### Steps to reproduce the behavior

Admin login => bar menu => List Servers
### Logs, screenshots, configuration dump, ...

![pb list server](https://cloud.githubusercontent.com/assets/11872380/17456171/928bfa16-5bce-11e6-889b-fca0a05516e5.png)

**Comment by elhoim** [comment]
Something that helps in most cases of mismatched between models and tables in MISP is to use the _clean cache_ feature under diagnostics tab part of the settings menu (https://github.com/MISP/misp-book/tree/master/administration#errors-about-fields-or-tables).

In theory it should not happen since there is a kind of autoclean that should happen after a data model update, but in practice it does happen sometimes; that's why I added that entry in the misp book.

Please let us know if the above solution does not work, it might be an indication of some other problem in that case.

**Comment by hibouu** [comment]
You're right, and your solution works. 
I add your entry in the doc. 
Issue solved. 
Thank.
