### ISSUE TITLE
Scheduled Tasks to pull feeds at regular interval 

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#1523]
A default scheduled tasks to pull feeds at regular interval should be added.

**Comment by Pedriton** [comment]
Is it possible to somehow schedule a regular feeds update (not just server pull)? For instance via CLI?

This type of scheduled job is definitely missing.

**Comment by iglocska** [comment]
Not currently, I was working on a reimplementation of the scheduled tasks but some priorities changed and I'm focusing on another feature now. Will finish it off soon though!

**Comment by dspruell** [comment]
Wanted to voice agreement on this, would be very useful to see periodic scheduling for pulling feeds. Is current process in 2.4.60 to manually "Fetch all events" for each feed from Feeds page?

**Comment by uforia** [comment]
I'm also waiting for this... There is no API call for it either, unfortunately. Manually scripting a download and import (PyMISP or otherwise) is a bit cumbersome.

**Comment by panzertime** [comment]
I am working on this now (for the current implementation of scheduled tasks, anyway).

**Comment by adulau** [comment]
There is an API interface to get and pull the feeds and the API is available via PyMISP:

- http://pymisp.readthedocs.io/en/master/_modules/pymisp/api.html#PyMISP.fetch_feed

So you can control the fetching of feed via any cronjob or scheduler as you which.

**Comment by billmurrin** [comment]
So what does "pull_all" in scheduled tasks actually pull? Sorry, I'm new to MISP and trying to figure everything out. 

Does anyone have any PyMISP examples of setting up the cronjob for pulling feeds that they would be willing to share?

**Comment by panzertime** [comment]
The PyMISP API call that adulau linked just sends a GET request to `/feeds/fetchFromFeed/<feed id>`, which is exactly what clicking the "fetch" button on the Feeds page does.  In order to script this, you'd have to find out what the Feed ID is for each feed you want to fetch, then either use that PyMISP call or another REST client to repeatedly call `/feeds/fetchFromFeed/<feed id>` until you've fetched every feed you care about.

Pull All in the Scheduled Tasks page simply propagates events from linked instances of MISP to your instance.  If you aren't using multiple instances of MISP, then it's not what you're looking for.

**Comment by dspruell** [comment]
Has any similar API interface for this been tested/proposed to enable similar behavior for server synchronization? Thinking push/pull of events to sync servers, and could be controlled offline via cron, etc. If not, is this good for a separate issue?

(Is the intention in the app that this kind of scheduling be done offline via cron/API, or is in fact the intended behavior that scheduled tasks should handle this natively)?

**Comment by FurqanKhan1** [comment]
Hi 
Kindly pardon me if the question may seem lame ,I am little new to MISP.
Reading the docx ,I don't have clarity on pulling of feeds from internet.
As of now ,is MISP capable of pulling feeds from external urls automatically ?? ,as in a scheduler that may run at regular intervals to do the same. 

If not then what does the enable checkbox does ,would it cache some specific feed ,so that while export the process is quicker ??

Please let me know over this.

Regards

**Comment by panzertime** [comment]
I have finished a pull request for this issue

https://github.com/MISP/MISP/pull/2451

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/bcbee05e2f39b07704cd7663237812ab5a724803 (2.4.79)

**Comment by chintamvijay** [comment]
Hi Guys!
am getting error while accessing the MISP application below is the screenshot, Please help me out, Thank you.
![image](https://user-images.githubusercontent.com/129829209/236168376-9d9feb2f-21a9-4858-8017-46ba946cdbbd.png)
