### ISSUE TITLE
Workers dying sporadically

### ISSUE THREAD

**Issue by did-this** [MISP/MISP#1622]
Every few days all (cache, default, email, prio, scheduler) workers die. Webui is only way to monitor and restore operations.

Server:
MISP 2.4.52 on Debian 7, 3.2.0-4-amd64 #1 SMP Debian 3.2.81-2 x86_64 GNU/Linux

Logs: nothing in syslog

**Comment by dewiestr** [comment]
I'm having the same problem with the scheduler. 

Server: MISP 2.4.56 on Debian 8 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux


Resque worker_error.log is saying : 

Error: Connection lost
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Stat.php(31): Redis->incrBy('stat:processed', 1)
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(573): Resque_Stat::incr('processed')
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(262): Resque_Worker->doneWorking()
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#4 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#5 {main}

Nothing in other logs...

**Comment by iglocska** [comment]
Did you restart apache by any chance?

**Comment by adulau** [comment]
As mentioned by @iglocska, when restarting Apache (after an update or a configuration change), this can have an impact of the worker. So a restart of the workers is usually needed. In a future, we might trigger the restart of the workers automatically. Not really sure if this is related to your issue.

**Comment by dewiestr** [comment]
No I didn't restart apache. And they still keep dying after that I restarted them. The unfortunate thing is that I'm not getting any logs from resque, even with debug=on.Do you have any idea where I should look next?  

My temp solution is an hourly Cron job that restarts all workers. 

Any typing errors are courtesy of my smartphone.

**Comment by adulau** [comment]
@dewiestr Thank you for the feedback and the debugging. Could you give us the php-redis version installed?

**Comment by dewiestr** [comment]
@adulau  Hey alex, thanks for taking the time. here are my versions:

> php -r 'phpinfo();' | grep -i 'redis version'
> Redis Version => 2.2.5
>PHP Version => 5.6.28-0+deb8u1
>Redis server v=2.8.17 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=4c1d5710660b9479``  

I did do a small change in the php-redis, that was also in https://github.com/xme/misp-docker/blob/master/Dockerfile

>print_status "Installing redisent & php-redis..."
>pecl install redis-2.2.8 &>> $logfile
>apt-get install -y php5-redis &>> $logfile
>error_check 'Redisent and php-redis install'

> After installing it, enable it in the php.ini file
>print_status "Enabling redis in php.ini..."
>echo "extension=redis.so" >> /etc/php5/apache2/php.ini
>print_good 'Add redis to php.ini'

**Comment by ghost** [comment]
Hey, 
I am using Ubuntu 16.04.1 with MISP 2.4.62 and i am having the same issue. For the last week or so the workers have been dying on a daily basis and most of the times I have not been able to restart them - neither via the GUI nor through the command line.

What I have found out is that this was/is a file permission issue. Some of the files in "/var/www/MISP/app/tmp/logs/" either had the wrong file permissions (e.g. executable-flag set) or the owner was changed to root. This happens on a daily basis now that whenever the logfile for a certain day is created (e.g resque-scheduler-2017-01-26-error.log), the file permissions/owner settings are messed up.

The file permissions were definitely correct after the last update since I used the official MISP update instructions including 

find /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP
chown -R www-data:www-data /var/www/MISP

But like I said, every day when the log files are written, especially the scheduler worker happens to die and I can only restart it once I take care of the file permissions.

**Comment by iglocska** [comment]
The log files being created for the wrong user happens if there are workers running that were not started by the apache worker. So if you launch a worker via the command line using a root user you'll run into this issue.

**Comment by ghost** [comment]
Thank you for your answer. Over the weekend I had the same again. Friday I made sure everything was fine before I left work for the weekend. This screenshot is from friday ~ 1pm.
![20170127_1255_mispworkers](https://cloud.githubusercontent.com/assets/20771149/22417017/368f5e9e-e6d2-11e6-9e64-61b1691e18fa.JPG)

Friday 27th all the scheduled tasks were finished and no problems. Then the first task on saturday the 28th the log file is created as root user, no more scheduled tasks get executed or scheduled and the default worker died (still started with the user www-data).
![20170130_0845_misp_logs_2](https://cloud.githubusercontent.com/assets/20771149/22417069/8deaf6a8-e6d2-11e6-93e3-099f85a035dc.JPG)
![20170130_0845_mispworkers](https://cloud.githubusercontent.com/assets/20771149/22417086/a7fb7040-e6d2-11e6-9cd9-0db03368f037.JPG)

Syslog, Apache logs or any other logs do not show anything weird around that time. The apache has not been restarted, there is no other cronjobs or anything. 

I dont want to exclude an administration issue but so far i have looked everywhere and couldnt find anything. The same thing happened on our other servers. Is there anything different in how the first daily scheduled task is executed, that you guys programmed in your code?

**Comment by RichieB2B** [comment]
When Apache and the MISP workers are originally running under their own uid (apache/httpd/www-data, as they should) then there is no way the MISP code can cause this. Some external process running as root created that log file. 

Did the server get restarted over night? If so, are there any MISP related statements in /etc/rc.local ?

**Comment by ghost** [comment]
The server itself and apache did not restart. The /etc/rc.local includes the line that should be added when setting up MISP.
![image](https://cloud.githubusercontent.com/assets/20771149/22423059/08a042be-e6f0-11e6-933d-6c6a78c608b3.png)

The apache process is running like this:
![image](https://cloud.githubusercontent.com/assets/20771149/22423248/07256e36-e6f1-11e6-9fa6-b4e9fc733b23.png)

Environment variables:
![image](https://cloud.githubusercontent.com/assets/20771149/22423349/822e8234-e6f1-11e6-8b9e-05fb5d947768.png)

**Comment by RichieB2B** [comment]
Well something is creating that log file as root. Is logrotate set up for these logs?

**Comment by ghost** [comment]
Sorry for the delay. I still have not found the the cause of my problem, but my workaround is a cronjob that restarts the workers and takes care of file permissions every day after the first log file is written. Since then the problem has not occured, but obviously the original issue has not been addressed. 

I did not open this issue, but for me the topic is closed because I can live with the workaround.
Thank you for you support anyway.
