### ISSUE TITLE
Cannot publish event after creating attribute with AJAX pop-over

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#1753]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.56

### Expected behavior
- Being able to publish after adding attribute.

### Actual behavior
- Not able to publish after adding attribute.

### Steps to reproduce the behavior
- Create an event.
- Add attribute using the AJAX pop-over (top left _**+**_ sign, **not** via the _Add Attribute_ link.
- Try to publish event, either normal or without email.
 The result look like the screenshot below.

### Logs, screenshots, configuration dump, ...
![image](https://cloud.githubusercontent.com/assets/178521/21103415/a4db0bf8-c082-11e6-9beb-6a13664f93a3.png)

**Comment by cristianbell** [comment]
The issue comes from https://github.com/MISP/MISP/blob/2.4/app/View/Attributes/add.ctp#L102 which adds a second confirmation_box div. Which happens in multiple places (for ex. in Attributes\ add_attachment.ctp, add_threatconnector.ctp..). 

Either change names of the confirmation_box which are not in default.ctp, or check if the div exists 
`$("#confirmation_box").length` and if not, add it.
