### ISSUE TITLE
Accepting proposals does not indicate event needs to be republished 

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#1763]
When a user accepts a proposal the attribute list is updated via Ajax, but the event meta data is not. As a result the Published field still displays Yes (in green) and the user does not get a visual indicator the event needs to be republished. Only upon reloading the event Published shows no (in red) and the event can be republished.

**Comment by iglocska** [comment]
Good point

On Dec 15, 2016 9:53 AM, "Richie B2B" <notifications@github.com> wrote:

When a user accepts a proposal the attribute list is updated via Ajax, but
the event meta data is not. As a result the Published field still displays
Yes (in green) and the user does not get a visual indicator the event needs
to be republished. Only upon reloading the event Published shows no (in
red) and the event can be republished.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MISP/MISP/issues/1763>, or mute the thread
