### ISSUE TITLE
Add related event at attribute level

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#1793]
RelatedAttribute was there, and isn't anymore: https://github.com/viper-framework/viper/blob/master/viper/modules/misp.py#L667

**Comment by iglocska** [comment]
This one is actually tricky. I found the relevant code that handles this and it looks like it was intentional. 

An example use case: Creating a MISP feed and not wanting to disclose related attributes that you can see.

I think the best solution would be to keep it as it is, also remove related events and have a parameter that would include both that is completely optional.

**Comment by Rafiot** [comment]
Fair enough, the optional switch works for me. Can you let me know when it is implemented? I'll update pymisp and viper module.

**Comment by cvandeplas** [comment]
This issue also affects me importantly, such an option would be valuable, but will break many scripts.

**Comment by Rafiot** [comment]
Well, an optional switch would do the trick, if you enable it, you get the related events.

**Comment by Rafiot** [comment]
fixed.
