### ISSUE TITLE
Just upgraded to 2.4.62 and instance is dog slow

### ISSUE THREAD

**Issue by bambenek** [MISP/MISP#1877]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

2.4.62 is very unresponsive on my instance.  MySQL has high memory usage but not enough to explain to slow response on order of minutes just to login.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug,
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | 16.04
| PHP version               | 5.5
| MISP version / git hash   | 2.4.62
| Browser                   | If applicable

**Comment by iglocska** [comment]
Indeed looking into it, your instance is the second I came across with a specific issue causing crazy slow performance. The issue was caused by an earlier update (by the lookups of it when you upgraded from 2.4.50) and your MISP has been trying to run the upgrade scripts on each request ever since. 

Which in itself causes a slowdown, but what really makes matters worse over time that these upgrade scripts are meant to be benign if you've already ran them once - however they will still log the attempted upgrade queries. Your log table is currently 150 GB in size, so this must have been going on for a while now...

I have currently cleaned up the issue that caused the perpetual upgrade loop but we still have to deal with the massive tables.

**Comment by bambenek** [comment]
What steps should I take? Want access to the server?

**Comment by adulau** [comment]
Sure especially that we would like to test some approaches (and your dataset is quite interesting) for the next release to solve this issue.

**Comment by iglocska** [comment]
I still have access from last time, I've done some emergency fixes to get it operational for now - but still working on a patch that will clean up your db. Expect it later tonight!

**Comment by adulau** [comment]
@iglocska Thank you.

**Comment by bambenek** [comment]
Sounds good, thanks all.  And by all means, please use the instance how
you see fit to make MISP better. :)

**Comment by iglocska** [comment]
So should be all good now. Your instance is incredibly interesting with the unique data-set and it helped us resolve several of the issues. It is now cleaned up and updated, the performance is looking pretty good now ;)

Just a recap of what happened:
- ran a fix for the upgrade loop
- cleaned up the logs of all upgrade messages
- updated MISP to the latest version
- switched to redis sessions which should be more stable and faster

We'll make sure to mention your support in the latest release notes.

Let us know if you find anything else not performing as it should and thanks a lot for helping with the debug.

**Comment by bambenek** [comment]
Thanks, i think only one issue with the export remains, let me play and
will get back to you
