### ISSUE TITLE
Get Discussion/Comment via API

### ISSUE THREAD

**Issue by FafnerKeyZee** [MISP/MISP#1880]
Hey,

Is it possible to add the possibility to retrieve the discussions of an event via the API request ?

Regards,

**Comment by adulau** [comment]
Until now, it's not possible. We will add it in the long-list of API changes ;-)

**Comment by iglocska** [comment]
This is now available, simply use one of the following:

```
https://<misp url>/threads/view/<thread id>
https://<misp url>/threads/viewEvent/<event id>
```

**Comment by geekscrapy** [comment]
Is there a way to submit a comment via the API?

**Comment by cybermung** [comment]
@geekscrapy 
Looking at the POST parameters, this isn't documented, but this works:
curl -k -i --header "Authorization: \<API Key\>" --header "Accept: application/json" --header "Content-Type: application/json" -d '{"Post":{"message":"\<Your comment\>"}}' https://\<misp url\>/posts/add/event/\<event id\>

From that point on, if you want to edit the specific comment, you'd have to get the post ID # and repost to the relevant thread id# related to the event id#.  To automate/api this, it'd look something like:
1. Get post ids related to event id via https://\<misp url\>/threads/viewEvent/\<event id\>
2. POST request in the following way:
curl -k -i --header "Authorization:  \<API Key\>" --header "Accept: application/json" --header "Content-Type: application/json" -d '{"Post":{"contents":"\<new message\>"}}' https://\<misp url\>/posts/edit/\<post id\>/event

Note that for the edit, the JSON key is 'contents' not 'message' (likely since you're making a request to a different URL to edit posts).

**Comment by geekscrapy** [comment]
I presume, as it's not been documented it's not in pyMISP?

**Comment by cybermung** [comment]
@geekscrapy 
Nope.  Not in PyMISP.
