### ISSUE TITLE
Scheduler workers failed

### ISSUE THREAD

**Issue by honey4free** [MISP/MISP#1911]
su -s /bin/bash apache -c 'scl enable rh-php56 /var/www/MISP/app/Console/worker/start.sh'
gives me the following error.
I followed the install manuale 
https://github.com/MISP/MISP/blob/f39eb469d33a3e7fd3d307fe7b05623e7494c12f/INSTALL/xINSTALL.centos7.txt

Stopping workers
   There is no workers to stop ...

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating the scheduler workers
Starting scheduler worker ..................... Fail

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | CentOS, 
| OS version (client)       | 7
| PHP version               |  5.6
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

**Comment by driveraider** [comment]
I am seeing the same error on my installation.

**Comment by elhoim** [comment]
Expected behavior: Scheduler worker starts
Actual behavior: Scheduler worker does not start.

No specific error message in error.log, debug.log, resque-scheduler*.log, resque-*.log, resque-worker-error.log, resque-scheduler-error.log

**Comment by elhoim** [comment]
I finally diagnosed it with:
diff --side-by-side --suppress-common-lines /var/www/MISP/INSTALL/setup/config.php /var/www/MISP/app/Plugin/CakeResque/Config/config.php

to see the differences between the running config and the default provide config. Somehow the CakeResque config file ended up with the value enabled as false instead of true.
`		'enabled' => true,			      |			'enabled' => false,`

Changed the value to true then it worked like planned.

**Comment by iglocska** [comment]
That simply means it wasn't installed correctly, moving the cakeresque
config file that has it set to true is part of the installation.
