### ISSUE TITLE
Unable to only select ZMQ event messages

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#2239]
ZeroMQ uses unique prefixes for messages. MISP currently sends:
```
misp_json
misp_json_attribute
misp_json_sighting
misp_json_organisation
misp_json_user
misp_json_self
```
So subscribing to `misp_json` gets all other types as well. It makes more sense to rename the event publishing message to `misp_json_event`.

**Comment by iglocska** [comment]
(I know we've talked about it on gitter, but just to keep a record of it ;)) We cannot rename the event feed for historic reasons (scripts out there polling it already), however, since ZMQ is a bit weird with namespacing just filter on topic on ingestion (so fetch all topics, only parse the topic, handle it if applicable).

Will close the issue for now, feel free to open new ones if it's no solution for you ;)
