### ISSUE TITLE
This action is for ajax requests only?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#2274]
When trying to edit an element from an existing template, MISP always returns an error based on this condition in the code:

if (!$this->request->is('ajax')) Throw new MethodNotAllowedException('This action is for ajax requests only.');

Any tip? To reproduce:

List Templates -> Select one -> Action 'edit' -> Select "View template" > Select element -> Action "edit" -> Change (ex: enable "mandatory") -> Submit -> Error

**Comment by iglocska** [comment]
Should be fixed now thanks for the heads-up!

**Comment by orbital-github-user** [comment]
Same problem here. When going to Event Actions - List Templates - Select one template - (+) - Text - Submit, get this error:

This action is for ajax requests only.
Error: The requested address '/templateElements/add/text/7' was not found on this server.

I am using CIRCL VirtualBox virtual machine with MISP 2.4.77.

**Comment by iglocska** [comment]
I thought this was fixed recently, will have a look. Could you git pull to
2.4.78?

**Comment by orbital-github-user** [comment]
Updated to 2.4.78 and problem fixed.
Thanks a lot!

**Comment by iglocska** [comment]
Excellent news B-)

**Comment by orbital-github-user** [comment]
It seems now the error happens every time an element of a template is modified.

When going to Event Actions - List Templates - Select one template - Edit template element - (make a modification) - Submit, get this error:

This action is for ajax requests only.
Error: The requested address '/templateElements/edit/attribute/63' was not found on this server.

And also happens if trying to edit another different one:

This action is for ajax requests only.
Error: The requested address '/templateElements/edit/text/64' was not found on this server.

I am using MISP 2.4.78 and "admin" account (full permissions).

**Comment by orbital-github-user** [comment]
Also when trying to delete one element of any template:

This action is for ajax requests only.
Error: The requested address '/template_elements/delete/62' was not found on this server.
