### ISSUE TITLE
Missing Database Table

### ISSUE THREAD

**Issue by RyanAiden** [MISP/MISP#232]
I'm trying to play around with MISP and followed the download instructions step by step and am getting a missing database table error.
The html page says Error: Table cake_sessions for model Session was not found in datasource default.
The logs say Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'misp.cake_sessions' doesn't exist' in /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php:458
If anyone could help me out I would greatly appreciate it. I don't know too much about MIPS but I'm running Ubuntu 12.04 Desktop in VMware Player.
Thank you for your time,
Ryan

**Comment by emwalsh2805** [comment]
Hey I keep getting this error 

It looks like you're encountering an error related to a missing database table (public.workspaces) in your application. The error occurs when attempting to load the login page, likely due to the backend trying to access a table that doesn’t exist or isn't properly set up.

How do I fix?

For context I am trying to create this chatbot ui through vercel. I have no knowledge of coding and very confused.
