### ISSUE TITLE
MISP event default TLP classification

### ISSUE THREAD

**Issue by beberlacrapule** [MISP/MISP#2506]
Hello MISP dev team,

I have a question/remark regarding the TLP MISP handling. I did some research to know what am I allowed to do with information without TLP attribution. The official TLP definition does not appear to provide details about this point.
I found that some people attribute by default the AMBER classification:
https://www.jigsawsecurityenterprise.com/terms-of-service 

If I follow this some events of the community which are in fact TLP:WHITE because data is coming from public blog post should be considered as TLP:AMBER. I think this is a problem.

I was wondering what is MISP point of view ? Should I consider all unmarked events as TLP:AMBER ?
To avoid any ambiguity, why MISP does not force the user to add a TLP tag to all events ?

Thank you in advance

**Comment by panzertime** [comment]
Obviously things from public sources are TLP:WHITE.  Good practice involves treating things with an unknown classification as if they were TLP:AMBER until you can determine the correct classification, but that doesn't mean the same thing as automatically classifying them as TLP:AMBER.

MISP does not force a user to add a TLP tag (or any other kind of tag) to an event because not all users of MISP use the TLP taxonomy.
