### ISSUE TITLE
Sync user, local vs. remote organisation (support)

### ISSUE THREAD

**Issue by marcnil815** [MISP/MISP#2595]
Hi

I have a very basic question about the correct way to sync between servers. The documentation is rather unclear on this. I seem to have found some pointers in answers to related questions, especially in the comments of #855 , but none are answering it in a succinct way.

I have 2 MISP instances that I want to sync.
**misp-local** owned by **my-org.local**
**misp-remote** owned by **other-org.local**

**misp-local** will be _pulling_ events.

This was my initial train of thought:
1. Add the my-org.local as a REMOTE organisation on the misp-remote (uncheck "local") using the UUID of my-org.local
2. Add syncuser@my-org.local in my-org.local on **misp-remote**
3. Set up sync server on the misp-local using the AUTH key from syncuser@my-org.local created on misp-remote

However **_2. cannot be done_**. There is no way to add a user to an ORG that is set as remote.

So I did this:

1. Add the my-org.local as a REMOTE organisation on the misp-remote (uncheck "local") using the UUID of my-org.local
2. Add syncuser@my-org.local in other-org.local on **misp-remote**
3. Set up sync server on the misp-local using the key from syncuser@other-org.local created on misp-remote

The unfortunate result that **all** events are pulled, even those with sharing right "Organization only".
This is of course because syncuserformyorg@other-org.local actually has the rights to see everything as he is a member of other-org.local.

Ok. Apparently that does not work as intended.

The way I made it work is as follows:

1. Add my-org.local as a LOCAL organisation on the misp-remote (to provide access to the server)
2. Add syncuser@my-org.local in my-org.local on **misp-remote**
3. Set up sync server on the misp-local using the key from the sync user created on misp-remote

Is this the correct way?
This just seems odd. Seen from the misp-remote my-org.local should not be a LOCAL org, but a REMOTE.

So there is an added optional step:
4. After doing the above, change my-org.local on misp-remote from LOCAL to REMOTE. The syncuser@my-org.local on misp-remote will continue to be associated with my-org.local.

The documentation is not clear on this as it says the following things:
"You can find the authentication key on your profile on the external server." (whose profile? The sync user? Which organisation? remote-org or local-org?)

"In order to share data with a remote server via pushes and pulls, you need to request a valid authentication key from the hosting organisation of the remote instance." What auth key? Sync user on remote-org.local, which results in total visibility? Or "the sync user added to your org that has been added locally to the remote server?)

It would be nice with a step by step instruction on how to set this up in the documentation. I'd be more than happy to lend a hand.

Br
Marc

**Comment by iglocska** [comment]
1. Add my-org.local as a LOCAL organisation on the misp-remote (to
   provide access to the server)
   2. Add syncuser@my-org.local in my-org.local on *misp-remote*
   3. Set up sync server on the misp-local using the key from the sync user
   created on misp-remote

This is indeed the correct way to do it. It is a LOCAL organisation since
it has a user locally on the instance (syncuser@my-org.local). The
difference between local and remote is simple: Is the organisation present
with any users on the instance? If yes, it's a local organisation from
MISP's perspective.

As for clarifications in the documentation, we always welcome pull requests that aim to clarify things that aren't as obvious as they should be. Thanks in advance!

**Comment by marcnil815** [comment]
Excellent. Thanks for the quick feed back !
I'll see what I can do about a pull request.

**Comment by felixpk** [comment]
Against your documentation I have to add a NON LOCAL organisation on the MISP Instance that hosts the SyncServer.

This means the synchronisation process consists of 4 Steps, not 3:

1. Add Local Organisation on MISP-A
2. Add SyncUser to Local Org on MISP-A
3. Add NON LOCAL Organisation on MISP-B
4. Add SyncServer on MISP-B with Authkey from user in (2) and OrgId from (3)

Am I doing something wrong or does this have changed?

**Edit:** I just noticed that it does not matter what UUID or OrgName you chose for the NON LOCAL organisation, it just satisfies the need for a remote UUID for the syncserver. 
This verifies that #3210 is either a Bug or  useless.

**Comment by criptk** [comment]
I am still having issues with this, it seems that the results are different every way i do it.

I have followed the instructions on the manual, setting up kinda like you are extending the local organization to a remote instance (by creating a organization checked to be local but with the uuid of the created remote org) and then assigning a sync user. Was able to get the events sometimes, others didn't. 

I did other crazy stuff in an attempt to get all events, since on my experiments only All Communities and Connected Communities event where being sent, such as creating the sync server with an admin user configured to be the admin (not org admin) of the Remote-Local Organization (so that the ORG on sync servers get set to the remote org), setting the remote organisation to either the local one and remote. Was able to get events some times, but will try to repeat and it fails (i am using the OVA btw last version as of Oct 4th 2019).

Am looking for clarification as to the best way to get all the events from a remote instance, and some pointers as how should the configuration look overall after it is done as well as some ideas on where to look to understand what is going on behind the curtain.

Thanks

**Comment by marcnil815** [comment]
@criptk 
It looks like you are running into the following: you are trying to PUSH the events to a remote instance, however, I have found that not all events are pushed. To my knowledge it is as below:
All communities, connected communites, Sharing Groups: PUSHable
Commuity: not PUSHable (only PULL).

You need to create the remote ORG on the local MISP. And then PULL from the remote to make sure that you get all events. I have never figured out why Community events cannot be PUSHed.

It's been a while since I tested it thoroughly though.

**Comment by TGeeSec** [comment]
Hi, I wanted to pull from the misppriv instance to our local organization instance. However, I am not able to create a "Sync User" on the misppriv instance as it is not suggested in the dropdown menu. Is this specific to misppriv?

When I look under "List Roles" I see that there is a "Sync User", "Org Admin" and "Org Admin API limited" with Sync Action permits”. Which user type do I need to create on the misppriv instance to synchronize with our local instance? 

Sorry to bother you with this basic question, but I couldn't find any information on it. 

Thanks!
