### ISSUE TITLE
Add tag for all events

### ISSUE THREAD

**Issue by santi10** [MISP/MISP#2667]
Hi,

I have this version 2.4.56, I would add a new tag to all events that I've register on my MISP.

How I can do it???

Regardas

**Comment by santi10** [comment]
Hi,

Can I do like recursive task or automation task????

Any update about this, please?


Thanks

**Comment by iglocska** [comment]
Hello,

first of all update before we deal with anything else, because you're running a year old version. 

Next, yes, you can write a python script that does what you want - however, keep in mind that you should not tamper with events created by others. You can however have a look at PyMISP, write a script that fetches a list of all events, iterate through them and add the tag accordingly.

**Comment by santi10** [comment]
for example "addtag.py", is it ok?

Thx

**Comment by santi10** [comment]
Done! Thanks iglocska!

**Comment by faustus25** [comment]
> 
> 
> Done! Thanks iglocska!

Can you share how you updated all the events with a tag/s using the addtag/s scripts?

I am looking to use the addtag/s.py script as the REST API complains when attempting the same action.
