### ISSUE TITLE
Attribute not added when sending complete event via the API

### ISSUE THREAD

**Issue by kyr-stefanidis** [MISP/MISP#2893]
Introduction

MISP version 2.4.87

We have 3 misp instances demo1/2/3
When sending events from one instance to another we use the following procedure
- press "publish event to zmq"
- read complete event json from zmq
- send complete event json to another instance
- POST/PUT complete event json to that other instance

In general syncronization is working. MISP creates or updates the correct event based on the uuid in the json. The following error happens in the case of adding attributes in the misp instance that recieved the event:

- When sending and event with an attribute from demo1 to demo2 and demo3. The event is created successfully to demo2 and demo3
- When adding an attribute to the event in demo1 and sending the updated event to demo2 and demo3. The event is updated successfully to demo2 and demo3
- When adding an attribute to the event in demo3 and sending the updated event to demo1 and demo2. The event is not updated correctly to demo1 and demo2

In the latest case, when examining the UI in demo1 and demo2, the new attribute is added in the list of attributes correctly, the new attribute is shown as part of the correct event, the event though does NOT show that it has that new attribute in itself.

Steps

1.Event with one attribute created at demo 1
(see 1.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_created.json for json as extracted from the MISP UI)
--Event send to demo2 and demo3
--[CORRECT]Event synced with demo2 and demo3 successfully

2.Event updated with one new attribute at demo 3
(see 2.demo3_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_updated.json json as extracted from the MISP UI)
(see 2.demo3_event_view.png for UI screenshot)

3.Event send to demo1 and demo2:
(see 3.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_push.json for POST/PUT payload)
(see 3.demo2_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_push.json for POST/PUT payload)

4.Demo1 and demo2 respond to the REST call with 200,OK and the event json inside: 

[BUG?] Demo1 and demo2 recieve an event with two attributes and respond 200 with an event with 1 attribute
(see 4.1.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012._response.json for responce payload)
(see 4.1.demo2_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012._response.json for responce payload)

[CORRECT] Demo1 and demo2 list of attibutes have correctly the new attribute in the list and it is linked with the correct event
(see 4.2.list_attributes_demo1.png for UI screenshot)
(see 4.2.list_attributes_demo2.png for UI screenshot)

[BUG?] Demo1 and demo2 events do NOT show the new attribute linked with the event
(see 4.3.list_events_demo1.png and 4.3.event_view_demo1.png for UI screenshot)
(see 4.3.list_events_demo2.png and 4.3.event_view_demo2.png for UI screenshot)

5.Repeat the step 2
[BUG] Any susequent updates sent from demo3 (e.g. add another attribute) result in misp error and no updates in the UI whatsoever
(see 5.demo2_misp.error.txt)

Attachments

[1.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_created.txt](https://github.com/MISP/MISP/files/1677703/1.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_created.txt)
[2.demo3_event_view](https://user-images.githubusercontent.com/35960867/35567246-06374016-05cd-11e8-8f51-8cab36347572.png)
[2.demo3_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_updated.txt](https://github.com/MISP/MISP/files/1677704/2.demo3_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_updated.txt)
[3.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_push.txt](https://github.com/MISP/MISP/files/1677705/3.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_push.txt)
[3.demo2_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_push.txt](https://github.com/MISP/MISP/files/1677706/3.demo2_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012_push.txt)
[4.1.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012._response.txt](https://github.com/MISP/MISP/files/1677707/4.1.demo1_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012._response.txt)
[4.1.demo2_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012._response.txt](https://github.com/MISP/MISP/files/1677709/4.1.demo2_misp.event.5a7032f8-34c8-45ef-b84d-0153ac120012._response.txt)
[4.2.list_attributes_demo1](https://user-images.githubusercontent.com/35960867/35567247-07164446-05cd-11e8-8dd3-0947ef204bb5.png)
[4.2.list_attributes_demo2](https://user-images.githubusercontent.com/35960867/35567248-073672f2-05cd-11e8-928a-1d65a5bda5d2.png)
[4.3.event_view_demo1](https://user-images.githubusercontent.com/35960867/35567251-075e2bd0-05cd-11e8-8f50-e1125bfbeea9.png)
[4.3.event_view_demo2](https://user-images.githubusercontent.com/35960867/35567252-0788252a-05cd-11e8-9512-c716aa06d6f6.png)
[4.3.list_events_demo1](https://user-images.githubusercontent.com/35960867/35567253-07aae0c4-05cd-11e8-9795-db69dcc4f747.png)
[4.3.list_events_demo2](https://user-images.githubusercontent.com/35960867/35567254-07d0a17e-05cd-11e8-9cbc-c20a2aa1cec7.png)
[5.demo2_misp.error.txt](https://github.com/MISP/MISP/files/1677710/5.demo2_misp.error.txt)

**Comment by iglocska** [comment]
That sounds like correct behaviour. MISP is basically blocking updates for events coming from a sync if the event was created locally. It's the tamper protection that prevents third parties to modify an event at source remotely.

The correct workflow would be:

Event created on misp 1 -> pushed to misp 3, org of misp 3 creates proposals to the event, proposals get pushed back to -> misp 1, event creator accepts the proposals.

**Comment by chpanag** [comment]
Let me elaborate on this.
We've just performed two new tests on our testbed with the 3 MISP instances.

**1. Share new event and attribute creation**
create event on misp3 -> pushed to misp 1 & misp 2 -> new event added in misp1 and misp2 
edit event to misp1 -> add new attribute -> pushed to misp2 & misp3 -> event updated with the new attribute only on demo3 and not on demo2, however the attribute is listed in the Attributes' list of demo2.
in misp2 error.log the following exception is logged:
`2018-01-30 14:05:23 Error: [Error] Call to a member function save() on null
Request URL: /events/105
Stack Trace:
#0 /var/www/MISP/app/Model/Event.php(2722): Attribute->editAttribute(Array, '105', Array, 0, Object(Log))
#1 /var/www/MISP/app/Controller/EventsController.php(1531): Event->_edit(Array, Array, '105')
#2 [internal function]: EventsController->edit('105')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#6 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}`

[event_on_demo1.png](https://user-images.githubusercontent.com/1949210/35570367-b132ac08-05d7-11e8-9cfe-876c034c4d38.png)
[event_on_demo2.png](https://user-images.githubusercontent.com/1949210/35570368-b151ca66-05d7-11e8-8573-f3658e25d1f0.png)
[event_on_demo3.png](https://user-images.githubusercontent.com/1949210/35570369-b1705d28-05d7-11e8-8f27-32ab72601934.png)
[list_attribute_on_demo2.png](https://user-images.githubusercontent.com/1949210/35570370-b18f0048-05d7-11e8-8a82-c0eb57a7c45f.png)

**2. Share new event and objects creation**
Event created on demo1 -> email object was added -> pushed to misp2 and misp3 -> new event added in misp1 and misp2
edit event on demo3 and add a new pastebin object -> pushed to misp1 and misp2 -> event updated with the new object successfully on both misp1 and misp2.


[demo1_misp event 91 5a7075bd-bba4-4b57-a5e8-00d4ac120012.png](https://user-images.githubusercontent.com/1949210/35570633-72720e90-05d8-11e8-9028-2e179c7ad05c.png)
[demo2_misp event 91 5a7075bd-bba4-4b57-a5e8-00d4ac120012.png](https://user-images.githubusercontent.com/1949210/35570634-72b1c8c8-05d8-11e8-80e9-7834b02edc8a.png)
[demo3_misp event 91 5a7075bd-bba4-4b57-a5e8-00d4ac120012.png](https://user-images.githubusercontent.com/1949210/35570635-72f43f6e-05d8-11e8-8078-43c98caaa3fc.png)

so, what should we consider as expected behavior in both cases?

**Comment by chpanag** [comment]
bump

**Comment by iglocska** [comment]
The stack trace part should now be fixed. As for the behaviour itself, let me just try to recap what happens:
3 instances (A, B, C)

Event e1 is created on A and pushed to B and C. B and C successfully receive the event.
Event e1 is updated on instance C and the edit is propagated back after it is republished
Event e1 gets updated on instance B but not on instance A.

Is this correct? If so, this is an intentional protection of MISP. e1 should never be edited on C, users of C should create proposals instead and the editing is always done on the instance where the event was created. Does this answer your issue? Or did I misunderstand the problem in the first place?

**Comment by chpanag** [comment]
Well the fact is that based on our investigation, the expecting behavior you describe doesn't match our observations. The e1 event does get updated on instance A as propagated from instance C. Please have a look on the following three scenarios (we have tested several other cases with the same event created on instance A, and changes propagated back and forth from the other two instances B and C to instance A):

> Scenario 1
>===========
>Event: new
>
>*Event created on demo1 with 6 attributes (uuid)
>**Network Activity:ip-src
>**Other:comment
>**Payload type:text
>**Person:first-name
>**Person:last-name
>**Person:phone-number
>*Event published (no email)
>*Publish Event to ZMQ
>PASS: The event with the 6 attributes received successfully by demo2 and demo3
>
>Scenario 2
>===========
>Event (created on demo1 in scenario 1)
>
>A.
>*Event editted on demo2 (changing the info field).
>*Event published (no email)
>*Publish Event to ZMQ
>PASS: The editted event with the 6 attributes received successfully by demo1 and demo3
>
>B.
>*Event editted on demo2 is again editted on demo3 (changing the info field).
>*Event published (no email)
>*Publish Event to ZMQ
>PASS: The editted event with the 6 attributes received successfully by demo1 and demo2
>
>Scenario 3
>===========
>Event
>
>*Edit Network activity:ip-src (10.10.20.1 -> 10.10.20.9) and Person:first-name (christos -> >christosEdittedOnDemo3) on demo3
>*Event published (no email)
>*Publish Event to ZMQ
>PASS: The editted event with the 6 attributes and the editted values received successfully by demo1 and demo2

**Comment by chpanag** [comment]
any update on this? did you confirm these observations?

**Comment by adulau** [comment]
Is it still applicable for MISP latest commit? Thank you.

**Comment by adulau** [comment]
I'll close the issue as we didn't get feedback about test with the latest version.
