### ISSUE TITLE
newbie getting misp-modules/xforceexchange running

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3246]
we are new to MISP (cool!) and are trying to get the out-of-the-box xforceexchange misp-module running and have some newbie questions. we believe misp-modules are enabled and working fundamentally as we can curl retrieve the list of modules.

we are running the latest 2.4.90 on 3.10.0-693.11.6.el7.x86_64

1. is there a document that gives the instructions that would have answered the following questions we pose? we didn't really parse out our needs in https://github.com/MISP/misp-modules/blob/master/README.md or https://www.circl.lu/assets/files/misp-training/brussels2016/misp-modules.pdf (although they are excellent docs otherwise :-)

1. is there a file where we need to configure the credentials to access the IBM XForce API (note: we do have access, and can run our own API clients to XForce outside of MISP).

1. Once configured, how do we initiate MISP retrieving data from XForce? We do not see any modules listed under Server Settings & Maintenance > Plugin Settings > Enrichment ... all we see is, and this part appears OK to us:
```
Priority | Setting | Value | Description | Error Message
Critical | Plugin.Enrichment_services_enable | true | Enable/disable the enrichment services |  
Critical | Plugin.Enrichment_hover_enable | true | Enable/disable the hover over information retrieved from the enrichment modules |  
Recommended | Plugin.Enrichment_timeout | 10 | Set a timeout for the enrichment services |  
Recommended | Plugin.Enrichment_hover_timeout | 5 | Set a timeout for the hover services |  
Recommended | Plugin.Enrichment_services_url | https://127.0.0.1 | The url used to access the enrichment services. By default, it is accessible at http://127.0.0.1:6666 |  
Recommended | Plugin.Enrichment_services_port | 6666
```

4. Once MISP is talking with XForce will the ingestion into MISP magically occur?

1. What else should we be asking? :-)

**Comment by Rafiot** [comment]
I think I know what's going on: `https://127.0.0.1` should be `http://127.0.0.1` (misp-modules are HTTP only).

Then, yes, when MISP can talk to the modules, you will have the configuration on that page. You need to enable the XForce one, set the credentials, and it will just work.

**Comment by github-germ** [comment]
the browser incoming to http://127.0.0.1:6666/modules is seen in `/var/log/httpd/misp.local_access.log but after /usr/bin/misp-modules` starts with the last line of the output being
```
2018-05-11 20:30:59,830 - misp-modules - INFO - MISP modules server started on localhost port 6666
```
there is no output when we see the hit in the apache log.

are we missing something in apache `conf.d/`

**Comment by gitnorty** [comment]
Hi Rafiot, no go with http or https; when I try either I get an "unable to connect" error.

If I try to go to http://misp-adddress/modules I get the error:

{
    "error": "Something went wrong, no response from misp_modules."
}

**Comment by github-germ** [comment]
i just think we are missing something in the setup. `misp-modules` is listening on `6666` but never seems to get any incoming. `apache` gets incoming. so it seems like we are missing a "`connector`" between `apache` and `misp-modules`. hence, my question above about a possible missing `apache conf.d`. we do have a `misp-ssl.conf` and the MISP WebUI on 443 is working fine.

thanks... i am hopeful that this is just a small nit and we'll be running well after that.

**Comment by Rafiot** [comment]
Soo, I'm confused: you say [here](https://github.com/MISP/MISP/issues/3246#issuecomment-388481206) that you can reach the misp-modules. They have nothing to do with apache, they run their own web server.

Then, you say [here](https://github.com/MISP/MISP/issues/3246#issuecomment-388481206) that you cannot reach the modules (is the port missing?).

And [finally](https://github.com/MISP/MISP/issues/3246#issuecomment-388503566), it seems the modules aren't reachable anymore.

**Comment by github-germ** [comment]
i will talk to our net admin to ensure we have a clear route.

in the meantime, would appreciate clarity on

1. http://localhost:6666/modules from a browser or curl wil list all modules via JSON. correct?

1.  what is the URL to access the config of a specific module, in our case xforceexchange? e.g. don't we need to enter our IBM user credentials somehow for the module to use?

1. Are any user auth credentials required from client to misp-modules? (seems like the modules JSON list does not require any auth.)

1. it's our impression that the xforceexchange module will talk to the IBM xforce API (we are registered for access), retrieve data, and ingest into our MISP. how do we initiate this process, e.g. something within misp-modules, or is there a URL we invoke with a curl request that is cron based, etc.?

THANKS!!

**Comment by Rafiot** [comment]
1. yes, if you can do a curl on http://localhost:6666/modules, and you get a JSON blob, it means the modules are running
2. The config will show up on the MISP interface (https://<domain>/servers/serverSettings/Plugin) -> enrichment. Internally, MISP queries the URL to retrieve the parameters required by the modules. If you can cURL, but MISP doesn't sees the modules, it means your apache process isn't allowed to run the HTTP GET and I have no clue how you can solve it and will blame your OS :) 
3. no
4. I don't know how the module itself work (I never used it, and don't have creds), but yes, most probably.

**Comment by gitnorty** [comment]
I noticed in the documentation that it mentions enabling the enrichment, which we see tabs for.  I also see tabs for import and export, but don't see any tab for 'expansion' or 'hover'; is this an install issue or is something else preventing these tabs from being displayed?

**Comment by github-germ** [comment]
also, is there a log file for the running misp-module where we can see requests/responses?

are there any other docs other than https://github.com/MISP/misp-modules that will shed more light on how all the dots connect?

any further details on the inner workings that can help us start to isolate root cause would be greatly appreciated, e.g. running some diagnostic tool and what to look for, etc...

**Comment by github-germ** [comment]
we are stuck. your help so far is greatly appreciated. would be great if you could reply to [this](https://github.com/MISP/MISP/issues/3246#issuecomment-388873672) and [that](https://github.com/MISP/MISP/issues/3246#issuecomment-388876548)

i feel we are close and just need to clear a small hurdle once the fog clears.

!! T H A N K S !!

**Comment by iglocska** [comment]
Hello there - sorry just trying to understand the underlying issue here:

1. could you paste the output if you curl  http://localhost:6666/modules ?

2. If the above correctly barfs up a JSON with all modules, could you try to set selinux not to enforce just to see if that's causing issues (there's a directive called httpd_can_network_connect IIRC that can cause issus).

**Comment by gitnorty** [comment]
The curl seems to work fine; we just aren't seeing the 'expansion' or 'hover' tabs.

Here is the curl output:


[root@md2nj01ta logs]# curl http://localhost:6666/modules
[{"name": "asn_history", "type": "modules", "mispattributes": {"input": ["AS"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query an ASN Description history service (https://github.com/CIRCL/ASN-Description-History.git)", "module-type": ["expansion", "hover"], "config": ["host", "port", "db"]}}, {"name": "rbl", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["text"]}, "meta": {"version": "0.1", "author": "Christian Studer", "description": "Check an IPv4 address against known RBLs.", "module-type": ["expansion", "hover"], "config": []}}, {"name": "farsight_passivedns", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Christophe Vandeplas", "description": "Module to access Farsight DNSDB Passive DNS", "module-type": ["expansion", "hover"], "config": ["apikey"]}}, {"name": "iprep", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["text"]}, "meta": {"version": "1.0", "author": "Keith Faber", "description": "Query IPRep Data for IP Address", "module-type": ["expansion"], "config": ["apikey"]}}, {"name": "virustotal", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst", "md5", "sha1", "sha256", "sha512"], "output": ["domain", "ip-src", "ip-dst", "text", "md5", "sha1", "sha256", "sha512", "ssdeep", "authentihash", "filename"]}, "meta": {"version": "2", "author": "Hannah Ward", "description": "Get information from virustotal", "module-type": ["expansion"], "config": ["apikey", "event_limit"]}}, {"name": "ipasn", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query an IP ASN history service (https://github.com/CIRCL/IP-ASN-history.git)", "module-type": ["expansion", "hover"], "config": ["host", "port", "db"]}}, {"name": "shodan", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query on Shodan", "module-type": ["expansion"], "config": ["apikey"]}}, {"name": "reversedns", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst", "domain|ip"], "output": ["hostname"]}, "meta": {"version": "0.1", "author": "Andreas Muehlemann", "description": "Simple Reverse DNS expansion service to resolve reverse DNS from MISP attributes", "module-type": ["expansion", "hover"], "config": ["nameserver"]}}, {"name": "crowdstrike_falcon", "type": "modules", "mispattributes": {"input": ["domain", "email-attachment", "email-dst", "email-reply-to", "email-src", "email-subject", "filename", "hostname", "ip", "ip-src", "ip-dst", "md5", "mutex", "regkey", "sha1", "sha256", "uri", "url", "user-agent", "whois-registrant-email", "x509-fingerprint-md5"], "output": ["hostname", "email-src", "email-subject", "filename", "md5", "sha1", "sha256", "ip-dst", "ip-dst", "mutex", "regkey", "url", "user-agent", "x509-fingerprint-md5", "threat-actor", "text"]}, "meta": {"version": "0.1", "author": "Christophe Vandeplas", "description": "Module to query CrowdStrike Falcon.", "module-type": ["expansion"], "config": ["api_id", "apikey"]}}, {"name": "circl_passivessl", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Module to access CIRCL Passive SSL", "module-type": ["expansion", "hover"], "config": ["username", "password"]}}, {"name": "xforceexchange", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst", "vulnerability", "md5", "sha1", "sha256"], "output": ["ip-src", "ip-dst", "text", "domain"]}, "meta": {"version": "1", "author": "Joerg Stephan (@johest)", "description": "IBM X-Force Exchange expansion module", "module-type": ["expansion", "hover"], "config": ["apikey", "event_limit"]}}, {"name": "sourcecache", "type": "modules", "mispattributes": {"input": ["link", "url"], "output": ["attachment", "malware-sample"]}, "meta": {"version": "0.1", "author": "Alexandre Dulaunoy", "description": "Module to cache web pages of analysis reports, OSINT sources. The module returns a link of the cached page.", "module-type": ["expansion"], "config": ["archivepath"]}}, {"name": "geoip_country", "type": "modules", "mispattributes": {"input": ["ip-src", "ip-dst", "domain|ip"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Andreas Muehlemann", "description": "Query a local copy of Maxminds Geolite database", "module-type": ["expansion", "hover"]}}, {"name": "cve", "type": "modules", "mispattributes": {"input": ["vulnerability"], "output": ["text"]}, "meta": {"version": "0.2", "author": "Alexandre Dulaunoy", "description": "An expansion hover module to expand information about CVE id.", "module-type": ["hover"], "config": []}}, {"name": "yara_syntax_validator", "type": "modules", "mispattributes": {"input": ["yara"], "output": ["text"]}, "meta": {"version": "0.1", "author": "Dennis Rand", "description": "An expansion hover module to perform a syntax check on if yara rules are valid or not.", "module-type": ["hover"], "config": []}}, {"name": "otx", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst", "md5", "sha1", "sha256", "sha512"], "output": ["domain", "ip-src", "ip-dst", "text", "md5", "sha1", "sha256", "sha512", "email"]}, "meta": {"version": "1", "author": "chrisdoman", "description": "Get information from AlienVault OTX", "module-type": ["expansion"], "config": ["apikey"]}}, {"name": "circl_passivedns", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Alexandre Dulaunoy", "description": "Module to access CIRCL Passive DNS", "module-type": ["expansion", "hover"], "config": ["username", "password"]}}, {"name": "vulndb", "type": "modules", "mispattributes": {"input": ["vulnerability"], "output": ["text", "link", "cpe"]}, "meta": {"version": "0.1", "author": "Koen Van Impe", "description": "Query VulnDB - RiskBasedSecurity.com", "module-type": ["expansion", "hover"], "config": ["apikey", "apisecret", "discard_dates", "discard_external_references", "discard_cvss", "discard_productinformation", "discard_classification", "discard_cpe"]}}, {"name": "threatminer", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst", "md5", "sha1", "sha256", "sha512"], "output": ["domain", "ip-src", "ip-dst", "text", "md5", "sha1", "sha256", "sha512", "ssdeep", "authentihash", "filename", "whois-registrant-email", "url", "link"]}, "meta": {"version": "1", "author": "KX499", "description": "Get information from ThreatMiner", "module-type": ["expansion"]}}, {"name": "vmray_submit", "type": "modules", "mispattributes": {"input": ["attachment", "malware-sample"], "output": ["text", "sha1", "sha256", "md5", "link"]}, "meta": {"version": "0.2", "author": "Koen Van Impe", "description": "Submit a sample to VMRay", "module-type": ["expansion"], "config": ["apikey", "url", "shareable", "do_not_reanalyze", "do_not_include_vmrayjobids"]}}, {"name": "wiki", "type": "modules", "mispattributes": {"input": ["text"], "output": ["text"]}, "meta": {"version": "0.2", "author": "Roman Graf", "description": "An expansion hover module to extract information from Wikidata to have additional information about particular term for analysis.", "module-type": ["hover"], "config": []}}, {"name": "eupi", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "url"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query the Phishing Initiative service (https://phishing-initiative.lu)", "module-type": ["expansion", "hover"], "config": ["apikey", "url"]}}, {"name": "passivetotal", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst", "x509-fingerprint-sha1", "email-src", "email-dst", "target-email", "whois-registrant-email", "whois-registrant-phone", "text", "whois-registrant-name", "whois-registrar", "whois-creation-date"], "output": ["hostname", "domain", "ip-src", "ip-dst", "x509-fingerprint-sha1", "email-src", "email-dst", "target-email", "whois-registrant-email", "whois-registrant-phone", "text", "whois-registrant-name", "whois-registrar", "whois-creation-date", "md5", "sha1", "sha256", "link"]}, "meta": {"version": "1.0", "author": "Brandon Dixon", "description": "The PassiveTotal MISP expansion module brings the datasets derived from Internet scanning directly into your MISP instance. This module supports passive DNS, historic SSL, WHOIS, and host attributes. In order to use the module, you must have a valid PassiveTotal account username and API key. Registration is free and can be done by visiting https://www.passivetotal.org/register", "module-type": ["expansion", "hover"], "config": ["username", "api_key"]}}, {"name": "countrycode", "type": "modules", "mispattributes": {"input": ["hostname", "domain"]}, "meta": {"version": "1", "author": "Hannah Ward", "description": "Expand Country Codes", "module-type": ["hover"], "config": []}}, {"name": "threatcrowd", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "ip-src", "ip-dst", "md5", "sha1", "sha256", "sha512", "whois-registrant-email"], "output": ["domain", "ip-src", "ip-dst", "text", "md5", "sha1", "sha256", "sha512", "hostname", "whois-registrant-email"]}, "meta": {"version": "1", "author": "chrisdoman", "description": "Get information from ThreatCrowd", "module-type": ["expansion"], "config": []}}, {"name": "whois", "type": "modules", "mispattributes": {"input": ["domain", "ip-src", "ip-dst"], "output": ["freetext"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Query a local instance of uwhois (https://github.com/rafiot/uwhoisd)", "module-type": ["expansion"], "config": ["server", "port"]}}, {"name": "dns", "type": "modules", "mispattributes": {"input": ["hostname", "domain", "domain|ip"], "output": ["ip-src", "ip-dst"]}, "meta": {"version": "0.2", "author": "Alexandre Dulaunoy", "description": "Simple DNS expansion service to resolve IP address from MISP attributes", "module-type": ["expansion", "hover"], "config": ["nameserver"]}}, {"name": "domaintools", "type": "modules", "mispattributes": {"input": ["domain", "email-src", "email-dst", "target-email", "whois-registrant-email", "whois-registrant-name", "whois-registrant-phone", "ip-src", "ip-dst"], "output": ["whois-registrant-email", "whois-registrant-phone", "whois-registrant-name", "whois-registrar", "whois-creation-date", "freetext", "domain"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "DomainTools MISP expansion module.", "module-type": ["expansion", "hover"], "config": ["username", "api_key"]}}, {"name": "mispjson", "type": "modules", "mispattributes": {"userConfig": {}, "inputSource": ["file"]}, "meta": {"version": "0.1", "author": "Richard van den Berg", "description": "MISP JSON format import module for merging MISP events", "module-type": ["import"], "config": []}}, {"name": "goamlimport", "type": "modules", "mispattributes": {"inputSource": ["file"], "output": ["MISP objects"]}, "meta": {"version": 1, "author": "Christian Studer", "description": "Import from GoAML", "module-type": ["import"], "config": []}}, {"name": "threatanalyzer_import", "type": "modules", "mispattributes": {"userConfig": {}, "inputSource": ["file"]}, "meta": {"version": "0.6", "author": "Christophe Vandeplas", "description": "Import for ThreatAnalyzer archive.zip/analysis.json files", "module-type": ["import"], "config": []}}, {"name": "cuckooimport", "type": "modules", "mispattributes": {"userConfig": {}, "inputSource": ["file"]}, "meta": {"version": "0.1", "author": "Victor van der Stoep", "description": "Cuckoo JSON import", "module-type": ["import"], "config": []}}, {"name": "openiocimport", "type": "modules", "mispattributes": {"userConfig": {"not save ioc": {"type": "Boolean", "message": "If you check this box, IOC file will not save as an attachment in MISP"}, "default tag": {"type": "String", "message": "Add tags spaced by a comma (tlp:white,misp:threat-level=\"no-risk\")", "validation": "0"}}, "inputSource": ["file"]}, "meta": {"version": "0.1", "author": "Rapha\u00ebl Vinot", "description": "Import OpenIOC package", "module-type": ["import"], "config": []}}, {"name": "email_import", "type": "modules", "mispattributes": {"userConfig": {}, "inputSource": ["file"]}, "meta": {"version": "0.1", "author": "Seamus Tuohy", "description": "Email import module for MISP", "module-type": ["import"], "config": ["unzip_attachments", "guess_zip_attachment_passwords", "extract_urls"]}}, {"name": "vmray_import", "type": "modules", "mispattributes": {"userConfig": {"include_textdescr": {"type": "Boolean", "message": "Include textual description"}, "include_analysisid": {"type": "Boolean", "message": "Include VMRay analysis_id text"}, "only_network_info": {"type": "Boolean", "message": "Only include network (src-ip, hostname, domain, ...) information"}, "sample_id": {"type": "Integer", "errorMessage": "Expected a sample ID", "message": "The VMRay sample_id"}}, "inputSource": []}, "meta": {"version": "0.1", "author": "Koen Van Impe", "description": "Import VMRay (VTI) results", "module-type": ["import"], "config": ["apikey", "url"]}}, {"name": "stiximport", "type": "modules", "mispattributes": {"userConfig": {}, "inputSource": ["file"]}, "meta": {"version": "0.2", "author": "Hannah Ward", "description": "Import some stix stuff", "module-type": ["import"], "config": []}}, {"name": "csvimport", "type": "modules", "mispattributes": {"inputSource": ["file"], "output": ["MISP attributes"]}, "meta": {"version": "0.1", "author": "Christian Studer", "description": "Import Attributes from a csv file.", "module-type": ["import"], "config": ["header"]}}, {"name": "ocr", "type": "modules", "mispattributes": {"userConfig": {}, "inputSource": ["file"]}, "meta": {"version": "0.1", "author": "Alexandre Dulaunoy", "description": "Optical Character Recognition (OCR) module for MISP", "module-type": ["import"], "config": []}}, {"name": "testimport", "type": "modules", "mispattributes": {"userConfig": {"number1": {"type": "Integer", "regex": "/^[0-4]$/i", "errorMessage": "Expected a number in range [0-4]", "message": "Column number used for value"}, "some_string": {"type": "String", "message": "A text field"}, "boolean_field": {"type": "Boolean", "message": "Boolean field test"}, "comment": {"type": "Integer", "message": "Column number used for comment"}}, "inputSource": ["file", "paste"]}, "meta": {"version": "0.2", "author": "Andras Iklody", "description": "Simple CSV import tool with mapable columns", "module-type": ["import"], "config": []}}, {"name": "testexport", "type": "modules", "mispattributes": {"responseType": "application/txt", "userConfig": {}, "outputFileExtension": "txt", "inputSource": ["event"]}, "meta": {"version": "0.1", "author": "Andras Iklody", "description": "Skeleton export module", "module-type": ["export"], "config": []}}, {"name": "cef_export", "type": "modules", "mispattributes": {"responseType": "application/txt", "outputFileExtension": "cef"}, "meta": {"version": "1", "author": "Hannah Ward", "description": "Export a module in CEF format", "module-type": ["export"], "config": ["Default_Severity", "Device_Vendor", "Device_Product", "Device_Version"]}}, {"name": "threatStream_misp_export", "type": "modules", "mispattributes": {"responseType": "application/txt", "outputFileExtension": "csv", "userConfig": {}, "inputSource": []}, "meta": {"version": "1.0", "author": "Robert Nixon, based off of the ThreatConnect MISP Module written by the CenturyLink CIRT", "description": "Export a structured CSV file for uploading to ThreatStream", "module-type": ["export"], "config": []}}, {"name": "threat_connect_export", "type": "modules", "mispattributes": {"responseType": "application/txt", "outputFileExtension": "csv", "userConfig": {}, "inputSource": []}, "meta": {"version": "0.1", "author": "CenturyLink CIRT", "description": "Export a structured CSV file for uploading to ThreatConnect", "module-type": ["export"], "config": ["Default_Source"]}}, {"name": "liteexport", "type": "modules", "mispattributes": {"responseType": "application/json", "outputFileExtension": "json"}, "meta": {"version": "1", "author": "TM", "description": "export lite", "module-type": ["export"], "config": ["indent_json_export"]}}, {"name": "goamlexport", "type": "modules", "mispattributes": {"responseType": "application/xml", "outputFileExtension": "xml"}, "meta": {"version": "1", "author": "Christian Studer", "description": "Export to GoAML", "module-type": ["export"], "require_standard_format": true, "config": ["rentity_id"]}}, {"name": "pdfexport", "type": "modules", "mispattributes": {"responseType": "application/pdf", "outputFileExtension": "pdf"}, "meta": {"version": "1", "author": "Rapha\u00ebl Vinot", "description": "Simple export to PDF", "module-type": ["export"], "require_standard_format": true, "config": []}}]

**Comment by iglocska** [comment]
OK, great, did you try relaxing SELinux?

**Comment by gitnorty** [comment]
we have it disabled:

[root@md2nj01ta logs]# sestatus
SELinux status:                 disabled

**Comment by gitnorty** [comment]
Can you clarify if we should be seeing the following tabs under the plugins section?

'expansion' 
'hover' 

If not, where do we enable and configure the modules?

**Comment by iglocska** [comment]
Those are sub categories of enrichment modules. An enrichment module can be either or both an expansion module and/or a hover module.

**Comment by gitnorty** [comment]
thanks; so does this mean all configurations of the individual misp-modules is done elsewhere?  if so, can you either point me to the documentation that gives the details or straighten me out of what I'm missing to configure in the web UI? thanks again.

**Comment by gitnorty** [comment]
in particular we'd like to focus our attention initially on the xforce module

**Comment by iglocska** [comment]
Basically this is where the configuration is done. The way it works is this:

- Misp modules (the tornado service) runs side by side with MISP.
- When you go to the plugin page, MISP will query http://localhost:6666/modules to get a list of the modules along with all of their configuration options and populate the settings
- Whatever changes you make will be reflected in the settings of MISP

So, in order to be able to configure the xforce module, you need to first enable the module system (for example, go to import modules, enable the import module system) - and then when you refresh the settings will be there.

**Comment by gitnorty** [comment]
thanks for the great information; I don't see anything that looks like 'import module system' (please see the attached screenshot; I put it in a word doc since it wasn't clear on how to attach them)

is this because we missed some installation step

[plugins_tab.docx](https://github.com/MISP/MISP/files/2005599/plugins_tab.docx)

**Comment by gitnorty** [comment]
sorry forgot to write my whole question; are we not seeing the 'import module system' setting because of a missed installation step or misconfiguration?

**Comment by Rafiot** [comment]
Yes, as I said (https://github.com/MISP/MISP/issues/3246#issuecomment-388405256), remove the s from https: the modules are running on the port 80, *not* 443.

**Comment by gitnorty** [comment]
ok, thanks for the clarification; currently we have only https enabled; have to changes some things around and try it again.

**Comment by gitnorty** [comment]
Hi Rafiot, so I tried with port 80 and I see the additional menu options; so does the code not currently support SSL with misp-modules?  Is there a backdoor from the CLI to make changes to these settings?  currently with SSL enabled, I can't reach this page.

**Comment by iglocska** [comment]
Basically the intent for misp-modules was to run in your own internal infrastructure and not serve it remotely. Think of it more as an inter-process communication I guess rather than an actual web server, so SSL didn't make much sense in the initial scope, however, we will probably revisit that for the use-case where someone wants a hosted misp-module service that is offered as a service.

**Comment by iglocska** [comment]
Also, it's not just a matter of menu options, MISP will not be able to use the misp-modules for lookups via SSL, even if you were to configure the modules via alternate means.

**Comment by gitnorty** [comment]
thanks for all you explanations iglocska!

In our setup, with SSL enabled, the system keeps trying to encrypt the 'plugins' page; is there a recommended configuration which would allow us to use SSL for all interactions with the web interface, but still enable the misp-modules functionality to work?

**Comment by github-germ** [comment]
**OK... found root cause. issue resolved! thanks for all your help.**

**...details...**
`config.php` (set by WebUI `Plugins`) had `'Enrichment_services_url'` set to `https://127.0.0.1`. all i did is change to `http` and all is fine, i.e. can now see all modules listed under `Enrichment`

**...questions...**
1. should `'Import_services_url` and `'Export_services_url`also use `http`?
1. we are not sure the `https` setting was set by us manually or via the install. can we assume that a fresh install will use `http`?

**...excerpt from `Config/config.php` on our instance...**
```
  'Plugin' =>
  array (
    'Import_services_enable' => true,
    'Enrichment_services_enable' => true,
    'Enrichment_hover_enable' => true,
    'Export_services_enable' => true,
    'Cortex_services_enable' => false,
    'CustomAuth_enable' => true,
    'CustomAuth_header' => 'Authorization',
    'Enrichment_services_port' => 6666,
    'Enrichment_services_url' => 'http://127.0.0.1',
    'Import_services_url' => 'https://127.0.0.1',
    'Import_services_port' => 6666,
    'Export_services_url' => 'https://127.0.0.1',
    'Export_services_port' => 6666,
    'Enrichment_timeout' => 10,
    'Enrichment_hover_timeout' => 5,
    'Import_timeout' => 10,
    'Export_timeout' => 10,
  ),
```

**Comment by SteveClement** [comment]
Import services should use 'http'

Sincerely.

**Comment by MU-03** [comment]
I am having the same issue even tho my Enrichment_services_url is http. What else could be the reason ,kindly guide
