### ISSUE TITLE
help with first attempt of a misp-module query

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3254]
2.4.90

we've got `misp-modules -d` enabled and running and are trying to test the `xforceexchange` module via curl. we are getting an error. any help is appreciated since this is new for us. thank you!

`xforce` is enabled and configured in the `MISP WebUI Server Settings Plugins` and we are able to see it on an `Event > Enrich Event` -- but that task fails. so, we want to test it with curl.

note: we are not sure what to place in the `apikey` config for `xforce` as X-Force uses a `user:passwd` key. we are registered uses and tried `user:passwd` and also the `base64.b64encode('user:passwd')`. however, we don't think we've gotten a test yet to actually attempt authorizing directly with the external IBM X-Force API URL.

```
$ cat ip-test.json
{
  "module": "xforceexchange",
  "ip-src": "1.1.1.1"
}
$ 
$ curl \
-k \
--header "Authorization: <my-misp-user-key>" \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
-X POST \
--data @ip-test.json \
https://localhost/modules/queryEnrichment
{"name":"Module not found or not available.","message":"Module not found or not available.","url":"\/modules\/queryEnrichment"}
$ 
```

misp-modules debug shows:
```
2018-05-17 01:58:58,012 - misp-modules - DEBUG - MISP ListModules request
DEBUG:misp-modules:MISP ListModules request
```

the script exists:
```
$ /usr/lib/python3.6/site-packages/misp_modules/modules/expansion/xforceexchange.py
-rw-r--r-- 1 root root 2726 May  7 18:38 /usr/lib/python3.6/site-packages/misp_modules/modules/expansion/xforceexchange.py
$ 
```

**Comment by SteveClement** [comment]
As stated in the module code [L25](
https://github.com/MISP/misp-modules/blob/b9d2a003e563ea9c0d3c0ff85cc22374d880fbfd/misp_modules/modules/expansion/xforceexchange.py#L25)

```
# config fields that your code expects from the site admin
moduleconfig = ["apikey", "event_limit"]
```

Thus, please config the API Key in the Web GUI as per Screenshot…

![screen shot 2018-05-24 at 06 22 31](https://user-images.githubusercontent.com/362025/40464343-f4d945e2-5f1a-11e8-95b5-acaf8f1fe01d.jpg)

**Comment by Alaa-HIjazi** [comment]
Config the API Key is not working, I have the same error.

This template is meant for bug reports, if you have a feature request user the other template.
If you would like to report a bug, please fill the template bellow

Work environment
Questions Answers
Type of issue No Module Found
OS version (server) Ubuntu
OS version (client) Win10
PHP version 7.4
MISP version / git hash 2.4.125 (4604aa4)
Browser Firefox
Expected behavior
When Using CURL: curl -k --header "Authorization: Api key" --header "Accept: application/json" --header "Content-Type: application/json" --data @event.json -X POST https://misp.local/modules/queryEnrichment

and event.json is:
{
"domain": "Test.com",
"module": "virustotal"
}
it should get as a response json format, because with securitytrails module it's working fine
Moreover, otx, whois, Are not working too with the same error below

Actual behavior
What i'am receiving is an error :
{'name': 'Module not found or not available.', 'message': 'Module not found or not available.', 'url': '/modules/queryEnrichment'}
