### ISSUE TITLE
Add comments for tags

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#349]
Allow tag creators to include a comment displayed in a tooltip when hovering on a tag

**Comment by adulau** [comment]
Just to keep track of this. Comments mean description of a tag.

**Comment by adulau** [comment]
Another point is that the description can be overwritten by a description field (and/or the expanded field) from the taxonomies.  The current implementation already includes the expanded field via a tooltip. 

@elhoim could you review the request following the current tag/taxonomies implementation and check if the issue is still the same or different. Thank you.

**Comment by elhoim** [comment]
Current implementation is perfect.

**Comment by adulau** [comment]
Thank you for the feedback.
