### ISSUE TITLE
Question:  Direction on Uninstalling MISP?

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [MISP/MISP#3749]
# Uninstall of MISP on RHEL (or anything)
having a lot of trouble finding data to uninstall MISP from a server.  Anyone gone through this and have information relevant?

Thanks in advance

**Comment by iglocska** [comment]
MISP is pretty self contained in /var/www/MISP, just remove that and disable the site in apache.

**Comment by SHSauler** [comment]
The webserver, PHP etc. pose an attack vector in case you no longer need them for MISP. You might want to remove (only!) the packages you no longer require. In the best scenario you deployed MISP in a dedicated VM or Docker container and can just purge it.

Removing packages example
```
sudo apt-get purge curl gcc git gnupg-agent make python python3 openssl redis-server sudo vim zip
sudo apt-get purge libapache2-mod-php php php-cli php-gnupg php-dev php-json php-mysql php-opcache php-readline php-redis php-xml php-mbstring`.
sudo apt-get purge mariadb-client mariadb-server
sudo apt-get purge apache2 apache2-doc apache2-utils
```

For removing `misp-modules`, you might want to recursively uninstall the `REQUIREMENTS` [like this](https://stackoverflow.com/a/15708711).

**Comment by iglocska** [comment]
Oh yeah, if you want to remove all dependencies it's a whole different ballgame. Keep in mind that other tools you are running might be running the dependencies listed above, so be careful before you remove python for example ;)

**Comment by SteveClement** [comment]
Ok, I will just close this issue.

Why?

I strongly advocate to not do patch-work on machines that face potential attack vectors and mostly host potentially confidential data.

Done with using your dedicated MISP machine? Recycle it! Invest the time into reinstalling the machine.

Especially if you are concerned with attack vectors.

Thus the uninstall procedure for MISP is: reinstall the machine and ideally wipe the disk because some confidential data might be present in the form of events/attributes etc etc.
