### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by Kahuna01** [MISP/MISP#3772]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu 16.04
| OS version (client)       | Win 7
| PHP version               | 7.0
| MISP version / git hash   | 2.4.96, d464fa820a1071338f346a8149d693bf4d22ff30

Hey guys,
I encountered some problems with the whitelist functionality. As far as I remember the whitelist was still working under 2.4.94.

### Expected behavior
When exporting or downloading events, attributes which are whitelisted won't be be exported.

### Actual behavior
All attributes are exported, even those which are whitelisted.

### Steps to reproduce the behavior
- got to "Input Filters" --> "Signature Whitelist"
- Whitelist any domain, like "/evildomain.com/"
- add that domain to an event
- on the event view, choose "download as..." or use the REST-API

Best regards

**Comment by radoslawc** [comment]
Good day, same thing here:

## Work environment

|  Questions | Answers   | 
|---|---|
|  Type of issue |Bug   |
|  OS version (server) | Ubuntu Xenial   |
|   OS version (client) | Win 10/OSX/Ubuntu BB desktop  |
|PHP version| 7.2|
|MISP version/git hash| 2.4.96, 2.4.98, 2.4 1684ae69 |

## Expected behaviour
When exporting or downloading events, attributes that are whitelisted are not suppose to be exported.

## Actual behaviour
All attributes are exported, regardless whitelisting state.

## Steps to reproduce the behaviour
- any domain whitelisted under /admin/whitelists/index and added to whichever event has no impact on either webpage download or API get

Best regards,
Rado

**Comment by cudeso** [comment]
Bug remains in 2.4.117

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| OS version (server) | Ubuntu 18.04.2
| PHP version | 7.2
| MISP version/git hash | 2.4.117

**Comment by github-germ** [comment]
Was this resolved post 2.4.117? Thx...

**Comment by mokaddem** [comment]
Sorry for the long waiting time... Whitelist should work as they did.
