### ISSUE TITLE
STIX export does not support URL Object type

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#3900]
The STIX 1.x export (misp2stix.py) does not export the contents of the URL Object. The URL inside the Object of the MISP event is simply missing from the STIX export.

**Comment by chrisr3d** [comment]
Hey,

I just tried to reproduce your issue, and it works for me, but let's see what is going on !
So if I understand correctly, it is an URL Object, but the value of the url attribute is missing, right ?

I expect from my script to return an Observable Composition for this Object, do you have any sample with the output you get for this Object, so I can see where the issue is ?

**Comment by RichieB2B** [comment]
Indeed the URL value is missing in the STIX export. Here is the MISP JSON format as well as the STIX XML export. Running fe3921ae9f22584b43fdf51ea90655644e65b0af (latest version) now.

[misp-url-object-stix.zip](https://github.com/MISP/MISP/files/2612118/misp-url-object-stix.zip)

**Comment by chrisr3d** [comment]
I found that the entire object was skipped because of a specific case not returning what I expected it to do and raising an exception.
It is now fixed with [ef242f3](https://github.com/MISP/MISP/commit/ef242f3eb3c0034729092a0dce752523e2c7f798), and should be working as expected

Thank you very much for your feedback
