### ISSUE TITLE
Users can add tags on external events

### ISSUE THREAD

**Issue by ancailliau** [MISP/MISP#3933]
For some events (I think that these are events whose local org is the org of the current user), users are able to add tags to attributes (but not to events).

As adding a tag to an attribute will break the synchronization of tags on these edited attributes, users should not be able to add these tags.

On long term, local tags would be best :)

**Comment by SteveClement** [comment]
@ancailliau is this still the case in v2.4.108

**Comment by ancailliau** [comment]
It is still the case in v2.4.109.

**Comment by adulau** [comment]
We introduced a new functionality to allow local tagging in the HEAD. 2a059f7b3171e3f3f8b26de6b8e7b5594e4ac3ee It will be included in 2.4.110. Don't hesitate to reopen an issue if you have other ideas. Thanks a lot for report.

**Comment by ancailliau** [comment]
Great to hear that. Is there documentation somewhere about the feature? Is
it transparent for the user?

**Comment by iglocska** [comment]
No documentation as of yet, but it's straight forward:

- Use global tags (globe icon) to add tags that behave as they did before
- (Host org users only): Use local tags (user icon) attach tags to data for local routing/sync filtering, local lookups on the instance

Local tags will not modify / unpublish the event and will not synchronise out. Otherwise they act the same way as regular tags. You can add tags, galaxies, tag collection, attack matrix element, whatever this way.

**Comment by ancailliau** [comment]
This is great. Thanks a lot, guys.

Is the API updated also? So I can start updating my scripts.
