### ISSUE TITLE
Full TLP support

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#394]
Currently, MISP does not support TLP internally. We use tags to denote the TLP level, but these are not exported (yet, see #320). It would be nice if MISP would support TLP in the data model.

Alternatively, we could ship MISP with default TLP tags, and check those when exporting to other formats like STIX.

**Comment by iglocska** [comment]
TLP is a little bit tricky in this case as we already do a rough
translation from our current distribution levels to TLP when exporting to
STIX. For now, tags are indeed your best option (it's also what we use
internally), but the STIX export definitely complicates this.

**Comment by adulau** [comment]
For your information, we are using TLP classification via the tags. The only missing part is the export of the tags from the API. Beside this, it's a viable solution.

**Comment by iglocska** [comment]
It's definitely on the to-do list, I'll try to implement this asap.

**Comment by RichieB2B** [comment]
I can work on exporting TLP tags properly into STIX. That is the major issue for us. TLP tags do work fine in MISP.

**Comment by iglocska** [comment]
What did you have in mind? Just on an incident level, or also on an
indicator / CoE / etc level? I remember this being an issue that is
actually pretty tricky, several of the STIX structures don't support TLP :(

**Comment by RichieB2B** [comment]
Since MISP tags are on the event level I think it makes sense to set the TLP in STIX on the incident level.

**Comment by iglocska** [comment]
The problem with this is that TLP is our closest way of indicating the releasability of the data contained within, so I ended up sort-of mapping it to TLP, as this way we can retain the idea of "you can share this incident information, but not these indicators". If we put the TLP markings that come from tags into the incident TLP marking, then that kind of invalidates the distribution translation to TLP for all objects. 

With that said, since we are moving away from the current distribution mechanism, maybe this might be a good idea for the next version, as we'll definitely not be able to translate the new system.

**Comment by Rafiot** [comment]
Fixed with taxonomies
