### ISSUE TITLE
help to reduce /tmp/sess_ * files

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#3972]
I imagine this might be a `php` setting. We see thousands of `/tmp/sess_*` files being created and not cleaned up. What's the setting to remove these over time, or do we need a cron job to remove older than...?

Thx.

**Comment by iglocska** [comment]
You are using the wrong session handler. This besides the massive number of session files also has an impact on performance, please switch to using redis sessions.

Go to server settings -> security -> session handler and check the description. It should be set to php and in your php.ini you have to make the appropriate changes to let the php session handler use redis instead of flat files.

**Comment by github-germ** [comment]
Many thanks!!!

**Comment by iglocska** [comment]
No worries!
