### ISSUE TITLE
There is no standard syntax name convention for registry keys and values

### ISSUE THREAD

**Issue by aaronkaplan** [MISP/MISP#402]
While importing massively many attributes/events we came across a small issue which is worth discussing and solving.

Problem description:

There are two groups of naming conventions:

```
  HKLM\path\path\path\path\kkkk = "value"
  ^------------ key ------------^     ^ value
```

However, there is a second understanding:

```
  HKLM\path\path\path\path\    kkkk      = "value"
  ^---------- key ---------^     ^-- value    ^------ data
```

It seems that in Windows, there are these two different understandings.
See also:
https://en.wikipedia.org/wiki/Windows_Registry#.REG_files for an example of naming.

So far so good. However how does this affect MISP?
Well, if you want to match values in MISP (correlation) it is important to know what is being correlate and matched.  If there is no clear definition, on how users should enter that data and how they need to interpret it, the correlation engine might have issues.

As a consequence, we would like to propose  a clearer syntax and semantical definition for well known attributes (such as registry keys).

Besides - please also note that often enough registry data (paths within registry values) are localised to a different language  (C:\Program Files\ ... vs. C:\Programme (german) )

So all of this makes the job of the correlation engine very hard. I vote for a standard format here.

And of course, we have the same issue with path names per se (which are also attributes).

**Comment by iglocska** [comment]
Yeah, the registry thing definitely needs to change to allow for key, value
and value-data. As for the localisation: We use regex entries for it. The
default set for regex entries includes Program Files to be converted
to %PROGRAMFILES%\\
.  One option would be to manually add the languages that you are
interested in, or alternatively we could think about adding a list of those
to the default set of regexes and just distribute them with the MYSQL.sql
file in MISP.

**Comment by didelphodon** [comment]
Regarding file-paths there's more we wonder how it impacts the correlation engine or how it could be done properly ...

Environment variables within paths:
There are very different scenarios how one can add a path as you can see in the following examples ...
c:\windows\system32
%windir%\system32
\windows\system32
As you can see for such a short path there are plenty ways to "see" it. Even if the 3rd example is not a "classical" one (and I can easily find more, just think about systems where the root drive isn't "c") it's an imaginable/possible entry as there is no clear input convention or check.

Another thing: What about backslashes ... single ones or double (in c-style)? That's also a question for registry keys.

**Comment by iglocska** [comment]
Very good points. I think we really need to tighten the regexes used for
this so that we really cover all of these use-cases. If you have more
similar examples, please compile them here and I'll do another pass at the
supplied transformations before the next release based on it!

**Comment by iglocska** [comment]
An alternative would be to change the way the correlation engine works (which is pretty simple at the moment) - this would of course have a performance impact and may prompt a higher need to separate the correlation task from the data entry.

**Comment by didelphodon** [comment]
I just took a look at the environment variables on a Windows 7 system and there are "endless" possibilities how to describe paths with those. So, imho, the only way is to restrict the data when it is entered. And of course this rules should also be put in the documentation of the data-model so that people who want to do i.e. an automatic import from their sandboxes (just what we are doing at the moment) know what's the proper format. I could even think of using some stored procedures (if the underlying db supports it that way) doing a check on insert if the according data matches the conventions - that might prevent "bad" inserts/updates.

**Comment by didelphodon** [comment]
... so imho an "easy" way for file paths might be to expect environment variables like %temp%, %ProgramFiles%, %SystemRoot%, %USERPROFILE%, %HOMEDRIVE% and %HOMEPATH% (etc.) to be used, that would also solve the localization stuff.

**Comment by didelphodon** [comment]
... However, to have this solution working "we" should check out the various environment variables of the various Windows flavours and versions to find the ones which are understood/supported by all (or at least the most) of them.

**Comment by iglocska** [comment]
Indeed. MISP kind og does this right now for various flavours, but assuming
an english windows installations (during data entry, c:\program files will
get converted automatically). Do you know of a list for the environment
variables and what resolves to them in all languages / flavours of windows?
If yes, we can create rules based on that!

**Comment by didelphodon** [comment]
I can take a look at Windows 7 and Windows XP (possibly also on Windows Server 2003 R2 and Windows RT, the latter is not relevant, though) and try to find out the variables they have in common.
Other Windows versions I do not have access to.

**Comment by iglocska** [comment]
That would be a great start, I'll have a look if I can find out too!

**Comment by didelphodon** [comment]
Regarding languages I only have German (maybe one of those systems is in English).

Maybe I could contact M$ for that question - but that's just an idea and I don't know if we'll get a satisfying answer.

**Comment by iglocska** [comment]
Have a guy from MS sitting next to me, I'll try to see if he has any info :)

**Comment by elhoim** [comment]
Some references that may come in handy for environment variables:
http://www.askvg.com/list-of-environment-variables-in-windows-xp-vista-and-7/
http://en.wikipedia.org/wiki/Environment_variable#Windows
https://technet.microsoft.com/en-us/library/cc749104%28v=ws.10%29.aspx

Sadly, I could not find anything more authoritative from Microsoft.

**Comment by iglocska** [comment]
So apparently there is no list for all languages / versions for windows...
This will be difficult to solve :)

**Comment by didelphodon** [comment]
The askvg-link is already a good starting point. Actually one can easily find the most relevant environment variables from this list when it comes to file-paths.

However, I've seen yet another point why you should only accept paths using those relevant environment variables: %APPDATA%

"%APPDATA%" resolves to something like "C:\Documents and Settings\{username}\Application Data" and here we have again a matching problem: {username}
Using the environment variable this issue would be solved, or better say wouldn't be an issue.

**Comment by didelphodon** [comment]
Imho, languages do not affect the environment variables. I'll try to come up with a (hopefully complete) list of relevant environment variables and according use-cases in paths.

**Comment by didelphodon** [comment]
As mentioned here's the list with the (most) relevant scenarios, imho ...

* Systemfiles
	- Relevant environment variable: %WINDIR%
	- Examples
		- %WINDIR%\System32\find.exe
			- Might resolve to ... "C:\Windows\System32\find.exe"
		- %WINDIR%\SysWOW64\find.exe
			- Might resolve to ... "C:\Windows\SysWOW64\find.exe"
		- %WINDIR%\System32\drivers\etc\hosts
			- Might resolve to ... "C:\Windows\System32\drivers\etc\hosts"
	
* Tempfiles (System)
	- Relevant environment variable: %WINDIR%
	- Example
		- %WINDIR%\Temp\file.dat
			- Might resolve to ... "C:\Windows\Temp\file.dat"
		
* Tempfiles (User)
	- Relevant environment variables: %TEMP%, %TMP% (equal => might make sense to treat similar)
	- Example
		- %TEMP%\file.dat
			- Might resolve to ... "C:\Documents and Settings\bob\Local Settings\Temp\file.dat"
			- Might resolve to ... "C:\Dokumente und Einstellungen\bob\Local Settings\Temp\file.dat"
			- Might resolve to ... "C:\Users\bob\AppData\Local\Temp\file.dat"
			- Might resolve to ... "C:\Benutzer\bob\AppData\Local\Temp\file.dat"

* Programfiles
	- Relevant environment variables: %PROGRAMFILES%, %PROGRAMFILES(X86)%
	- Examples
		- %PROGRAMFILES%\CompanyABC\program.exe
			- Might resolve to ... "C:\Program Files\CompanyABC\program.exe"
			- Might resolve to ... "C:\Programme\CompanyABC\program.exe"
		- %PROGRAMFILES(X86)%\CompanyABC\program.exe
			- Might resolve to ... "C:\Program Files (x86)\CompanyABC\program.exe"
			- Might resolve to ... "C:\Programme (x86)\CompanyABC\program.exe"

* Applicationdata
	- Relevant environment variable: %APPDATA%, %LOCALAPPDATA% (only in Windows Vista and later => might make sense to treat similar)
	- Examples
		- %APPDATA%\CompanyABC\savefile.dat
			- Might resolve to ... "C:\Documents and Settings\bob\Application Data\CompanyABC\savefile.dat"
			- Might resolve to ... "C:\Dokumente und Einstellungen\bob\Application Data\CompanyABC\savefile.dat"
			- Might resolve to ... "C:\Users\bob\AppData\Roaming\CompanyABC\savefile.dat"
			- Might resolve to ... "C:\Benutzer\bob\AppData\Roaming\CompanyABC\savefile.dat"
		- %LOCALAPPDATA%\CompanyABC\savefile.dat
			- Might resolve to ... "C:\Users\bob\AppData\Local\CompanyABC\savefile.dat"
			- Might resolve to ... "C:\Benutzer\bob\AppData\Local\CompanyABC\savefile.dat"

* Homepath
	- Relevant environment variable: %HOMEPATH%
	- Example
		- %HOMEPATH%\config.ini
			- Might resolve to ... "C:\Documents and Settings\bob\config.ini"
			- Might resolve to ... "C:\Dokumente und Einstellungen\bob\config.ini"
			- Might resolve to ... "C:\Users\bob\config.ini"
			- Might resolve to ... "C:\Benutzer\bob\config.ini"

**Comment by didelphodon** [comment]
Another potential problem might be matching paths including 8.3 names with long ones ...
%WINDIR%\System32\thisisalongfilename.dat == %WINDIR%\System32\thisis~1.dat

... just for the sake of completeness ;-)

**Comment by didelphodon** [comment]
Any thoughts or advises in which format we should fill path or registry attributes - we've got to continue our work asap?

Thx in advance!

**Comment by iglocska** [comment]
I think the best is to keep it in the format

key\value|data for now until we get a more granular data model. Right now
one of the biggest limitations of the data-model is that we can only create
attribute types consisting of 2 components, and realistically we should
have 3 for windows registry information.

I think right now the safest bet is to follow these rules:

1. I want to create an attribute that captures the registry key, value and
data:
    chosen type: regkey|value
    attribute value: HKEY_LOCAL_MACHINE\Software\Foobar\value|something

2. I want to create an attribute that captures the registry key and value:
    chosen type: regkey
    attribute value: HKEY_LOCAL_MACHINE\Software\Foobar\value

3. I simply want to create an attribute that captures the registry key
    chosen type: regkey
    attribute value: HKEY_LOCAL_MACHINE\Software\Foobar\

Of course the naming convention for regkey|value is not very fortunate, it
should be regkey/value and regkey/value|data. In the future the idea is to
have a registry object with 3 components, which should make this a lot
clearer.

As for the environment variables:

Some of those cases are already covered (go to Input filters -> import
regexp), but none of the german language versions are included there.

Here is the list you have provided with the cases covered (with the missing
ones bolded):

Systemfiles

   - Relevant environment variable: %WINDIR%
   - Examples
      - %WINDIR%\System32\find.exe
         - Might resolve to ... "C:\Windows\System32\find.exe"
      - %WINDIR%\SysWOW64\find.exe
         - Might resolve to ... "C:\Windows\SysWOW64\find.exe"
      - %WINDIR%\System32\drivers\etc\hosts
         - Might resolve to ... "C:\Windows\System32\drivers\etc\hosts"

Tempfiles (System)

   - Relevant environment variable: %WINDIR%
   - Example
      - %WINDIR%\Temp\file.dat
         - Might resolve to ... "C:\Windows\Temp\file.dat"

Tempfiles (User)

   - Relevant environment variables: %TEMP%, %TMP% (equal => might make
   sense to treat similar)
   - Example
      - %TEMP%\file.dat
         - Might resolve to ... "C:\Documents and Settings\bob\Local
         Settings\Temp\file.dat"
         - *Might resolve to ... "C:\Dokumente und Einstellungen\bob\Local
         Settings\Temp\file.dat"*
         - Might resolve to ... "C:\Users\bob\AppData\Local\Temp\file.dat"
         - *Might resolve to ...
         "C:\Benutzer\bob\AppData\Local\Temp\file.dat"*

Programfiles

   - Relevant environment variables: %PROGRAMFILES%, %PROGRAMFILES(X86)%
   - Examples
      - %PROGRAMFILES%\CompanyABC\program.exe
         - Might resolve to ... "C:\Program Files\CompanyABC\program.exe"
         - *Might resolve to ... "C:\Programme\CompanyABC\program.exe"*
      - %PROGRAMFILES(X86)%\CompanyABC\program.exe
         - Might resolve to ... "C:\Program Files
         (x86)\CompanyABC\program.exe"
         - *Might resolve to ... "C:\Programme
         (x86)\CompanyABC\program.exe"*

Applicationdata

   - Relevant environment variable: %APPDATA%, %LOCALAPPDATA% (only in
   Windows Vista and later => might make sense to treat similar)
   - Examples
      - %APPDATA%\CompanyABC\savefile.dat
         - Might resolve to ... "C:\Documents and Settings\bob\Application
         Data\CompanyABC\savefile.dat"
         - Might resolve to ... *"C:\Dokumente und
         Einstellungen\bob\Application Data\CompanyABC\savefile.dat"*
         - Might resolve to ...
         "C:\Users\bob\AppData\Roaming\CompanyABC\savefile.dat"
         - Might resolve to ... "
         *C:\Benutzer\bob\AppData\Roaming\CompanyABC\savefile.dat"*
      - %LOCALAPPDATA%\CompanyABC\savefile.dat
         - Might resolve to ...
         "C:\Users\bob\AppData\Local\CompanyABC\savefile.dat"
         - *Might resolve to ...
         "C:\Benutzer\bob\AppData\Local\CompanyABC\savefile.dat"*

Homepath

   - Relevant environment variable: %HOMEPATH%
   - Example
      - %HOMEPATH%\config.ini
         - *Might resolve to ... "C:\Documents and Settings\bob\config.ini"*
         - *Might resolve to ... "C:\Dokumente und
         Einstellungen\bob\config.ini"*
         - *Might resolve to ... "C:\Users\bob\config.ini"*
         - *Might resolve to ... "C:\Benutzer\bob\config.ini"*


The following additional entries in the import regex settings will cover
your remaining use-cases:

/.:.Benutzer\\(.*?)\\AppData.Local.Temp./i   -> %TEMP%\\
/.:.Dokumente und Einstellungen\\(.*?)\\Local Settings.Temp./i -> %TEMP%\\
/.:.Programme./i -> %PROGRAMFILES%\\
/.:.Programme (x86)./i -> %PROGRAMFILES(X86)%\\
/.:.Benutzer\\(.*?)\\AppData.Local./i -> %LOCALAPPDATA%\\
/.:.Benutzer\\(.*?)\\AppData.Roaming./i  -> %APPDATA%\\
/.:.Benutzer\\(.*?)\\Application Data./i  -> %APPDATA%\\

Instead of the %HOMEPATH% (which in 99% of the cases will indeed be
something along the lines of C:\Users\username\, can be something else in
certain cases) we use %USERPROFILE%. For the missing german userprofile
regexes use these:

/.:.Dokumente und Einstellungen\\(.*?)\\/i -> %USERPROFILE%\\
/.:.Benutzer\\(.*?)\\/i -> %USERPROFILE%\\

Hope this helps!

**Comment by iglocska** [comment]
I see the bolding didn't work, serves me right for replying to github via email :)

**Comment by didelphodon** [comment]
I just found out that there are also differences between the localizations which cannot be addressed by the use of environment variables (folders for images, documents, ...). So, how shall we solve this?

**Comment by iglocska** [comment]
That makes it tough indeed, maybe the best option is to always go with the
english option and just convert it to that. Let me know if you need help
with the regexes for this!

So for images for example, it would be:

C:\Benutzer\Bob\Bilder\bild.exe

Would be resolved to

%USERPROFILE%\Bilder\bild.exe

Adding a new rule like this after the previous rule set:
Pattern:
/%USERPROFILE%.Bilder./i
Replacement:
%USERPROFILE%\\Pictures\\

should change it to:

%USERPROFILE%\Pictures\bild.exe

Hope this helps!

**Comment by didelphodon** [comment]
Sounds reasonable to use English localization as a generic solution. I already spend some time now to find a comparison list regarding German and English localization of Windows (for XP, Vista, 7, ...) => couldn't find one. Imho, there's a need for such a list to be able to resolve this aspects.

Btw, I guess all of the regexes you mentioned are done by the backend (web server) - this still leads to problems if one likes to directly insert data into the DB (just as we do it). Did you think of/is there a way to use/using stored procedures for Insert and Update which can handle this actual replacements?

**Comment by iglocska** [comment]
Ah ok, that is a good question, I've never looked into that. I don't think
that MySQL has any regex capability, at least not by default - but I could
be completley wrong about this. This would mean that the stored procedures
for this would have to be written from scratch and the regex rules could
not be reused.

 I'd really recommend going through the API / interface to enter data (MISP
does a lot of validation, altering of the data). Is using the API a
possiblity for you? Is there anything from the API missing that would allow
you to use it instead of directly inserting data into the DB?

**Comment by didelphodon** [comment]
Hm, not knowing the API in absolute details we spotted a general problem when one would like to export lots of data automatically - it's the autonum columns and the IDs ... We are aware that it's very likely when we have done all of our imports into MISP from our sandbox that some time later there will be new ideas what else we could extract from the recorded data adding this to already existing events - therefore we would need ...
* a way to find out what event number has been created in terms of a new event to add the according attributes 
* a way to find already existing events that match the actual scan we want to enhance in terms of data
... so the import formats seem to be not apropriate to us. And an API would have some learning curve and would still have to be implemented in our exporter - we thought writing directly into the DB would save us some time.
There way actually some more thoughts that lead to our decision but I cannot remember them now.

**Comment by iglocska** [comment]
I am not sure I understood it correctly but the API on event creation will
actually return the inserted data in the same format as you have submitted
it in including all the data such as the id.
So for example:

If you use the API and submit a json formatted event, for example this:

{
  "Event": {
    "date": "2012-04-12",
    "threat_level_id": "4",
    "info": "info",
    "user_id": "1",
    "distribution": "0",
    "analysis": "0",
    "timestamp": "1",
    "Attribute": [
      {
        "type": "ip-dst",
        "category": "Network activity",
        "to_ids": "1",
        "distribution": "0",
        "value": "1.1.1.1",
        "timestamp": "0"
      }
]
  }
}

then MISP will create an event with the attribute and return this:

"{\"Event\":{\"id\":\"24\",\"org\":\"NCIRC\",\"date\":\"2012-04-12\",\"threat_level_id\":\"4\",\"info\":\"info\",\"published\":false,\"uuid\":\"54eb53be-5fbc-4f45-8d21-1377c0a8380b\",\"attribute_count\":\"1\",\"analysis\":\"0\",\"timestamp\":\"1\",\"distribution\":\"0\",\"proposal_email_lock\":false,\"orgc\":\"NCIRC\",\"locked\":false,\"publish_timestamp\":\"0\",\"Attribute\":[{\"id\":\"2745\",\"type\":\"ip-dst\",\"category\":\"Network
activity\",\"to_ids\":true,\"uuid\":\"54eb53be-b194-4553-a06a-1377c0a8380b\",\"event_id\":\"24\",\"distribution\":\"0\",\"timestamp\":\"1424708542\",\"comment\":\"\",\"value\":\"1.1.1.1\",\"ShadowAttribute\":[]}],\"ShadowAttribute\":[],\"RelatedEvent\":[]}}"

with the newly created ID included.

It all boils down to what you are really after, but you may run into issues
when synchronising data entered directly into the DB, since the same data
validation that you would have on the initial data entry will only happen
during the sync itself on the far end.

**Comment by didelphodon** [comment]
Hm, I was only aware of XML-based import mechanisms so far - thx for the clarification. Actually this example looks quite good.
However, one question is still unanswered, though: How would I add new attributes to an already existing event and how would I update/modify an existing attribute this way?

**Comment by didelphodon** [comment]
Btw., I just took a look at the documentation and regarding JSON, API, etc. I have to say that I do not feel comfortable in terms of knowing what's possible and how it's done at the moment.

**Comment by iglocska** [comment]
Indeed, the documentation of the API for data entry is far from perfect,
I'll look into it soon. I also ran across a bug with attribute entry, I'll
fix it asap.

**Comment by elhoim** [comment]
Just stumbled upon [this page](https://support.microsoft.com/en-us/kb/310516) from Microsoft explaining the syntax to create .reg file. Probably a good reference to try to create a validation module.

**Comment by adulau** [comment]
Now that we have the MISP objects, should we make an object which is following the format of a .reg file?

@elhoim do you want to create your [first object template](https://github.com/MISP/misp-objects/)?

**Comment by adulau** [comment]
A registry-key object now exists:

https://www.misp-project.org/objects.html#_registry_key

I'll close the issue. Feel free to reopen this issue or propose update on the object itself. Thank you!
