### ISSUE TITLE
Help with enabling standard feed workflow

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4029]
2.4.100

I'm new to enabling a standard feed. Is there a doc that explains the full workflow and management including monitoring, etc.?

Here's what I did. I want the hourly pull to ingest (merge) the data into the MISP event, but the data is pulled from the provider but nothing is being ingested.

1. Enabled `OpenPhish url list` in `Sync Action > List Feeds`
2. On `Administration > Scheduled Tasks` set `fetch_feeds` to frequency=1, and set the `Scheduled Time` and `Next Run` to start in 2 minutes.
3. `Administration > Jobs` showed that the job ran and completed.
4. No Event and no of the url attributes appear in MISP.
5. Back on `Sync Actions > List Feeds` click on `preview` magnify-glass icon and I see lots items in `OpenPhish url list`.
6. Select one `url`, click `Fetch selected` and indeed a MISP Event with that `url` attribute is created.

So... how do I set this feed to auto ingest after the data is pulled from the provider?

Am I correct that `cache` mode will not ingest, allowing for manual selection and ingestion? And if `cache` is not enabled, that the auto-ingest would occur?

Thanks!!

**Comment by iglocska** [comment]
Caching won't ingest it, that is only caching in order to get correlations against the feed / get data into the feed overlap matrix.

Fetching feeds ingests the in your MISP for usage. Scheduled tasks are crap, don't use them, use cron jobs - all fetching/caching functions are exposed to both the API and the CLI (event actions -> automation, bottom of the page for descriptions).

**Comment by github-germ** [comment]
how do i diagnose why this fails?
```
$ sudo /var/www/MISP/app/Console/cake Server fetchFeed 14 25

Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Job failed.
$ 
```

**Comment by github-germ** [comment]
ok, i saw the error listed in the WebUI `feeds/edit` page -- an old fixed `eventid` needed to be removed, and then it worked, and like magic the `eventid` was auto filled in for that feed: nice!

i do see that `/var/www/MISP/app/Console/cake` installs as`uid:gid` `root:apache 750` -- not too friendly. can we switch only the `own:grp` on that file or is more involved? the other choice is run the `cron` job as `root` or `apache` which our OPs team may not allow.

curious, are these details documented anywhere?

**Comment by github-germ** [comment]
what does this error man?
```fatal: Not a git repository (or any of the parent directories): .git```

```
$ sudo /var/www/MISP/app/Console/cake Server fetchFeed 14 25

Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
fatal: Not a git repository (or any of the parent directories): .git
Job done.
$ 
```

**Comment by cvandeplas** [comment]
There seems to be something wrong with your installation. Please ensure you install MISP using the [instructions](https://github.com/MISP/MISP/tree/2.4/INSTALL). If this does not suffice, would you be open to paid support to help you resolve your issues?

**Comment by gitnorty** [comment]
Hi cvandeplas, when we installed MISP, we followed the instructions on the MISP website; specifically the RedHat 7 Install instructions.  This instance has been up for about a year with no apparent issues; can you suggest some things to look at with regards to what might be incorrectly installed?   One thing of interest is that when I've tried reapplying the permissions in the documentation, that often times this causes issues, as if something is not right any more.  I know to look at the various log files under '/var/www/MISP/app/tmp/logs/'; but this doesn't always clearly point to what the issue is.  Any other suggestions would be very appreciated.  Thanks!

**Comment by iglocska** [comment]
Is git filemode set to false? Are you using the correct users to execute various scripts? (For example CLI scripts, starting workers etc should all be handled by the apache user). If you follow the install guide and stick to using the proper workers you should generally never have to reapply permissions.

**Comment by gitnorty** [comment]
I'm not sure if this is the proper way to check, but it looks like the 'git filemode' is set to false:

[root@md2nj08ta MISP]# git config --get core.fileMode
false

This is nothing that I recall configuring previously; I saw that I should be able to change it as follows, but is this the recommended method?

**git config --global core.fileMode true**

I found online the following description, " Tells Git if the executable bit of files in the working tree is to be honored.  Some filesystems lose the executable bit when a file that is marked as executable is checked out, or checks out a non-executable file with executable bit on."  

So if this is correct, since our system is set to 'FALSE'; does this mean the executable permissions may be removed, thus the permissions will be incorrect after upgrades/updates?

The only experience close to this that I've noticed so far is when updating PyMISP; the permissions were not working properly after updating to some of the newer versions (for example 2.4.101).

I believe we are using the correct user(s) for running various scripts, starting workers, etc..; but without checking every detail, I can't say for sure.

I'll go back through the install guide and see what if anything stands out as different between what should be configured and what is configured.

Thanks again for the suggestions!
