### ISSUE TITLE
Issue with JSON output in the API

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#411]
Until recently, it was possible to do the following:

```
source = PyMISP(<url>, <authkey>, True, 'json')
r_src = source.get_event(666)
r_src.json()  # python dict
```
But now, it is a python string. I have to use json.loads(r_src.json()) to have a python dict.

It is not a huge issue, but it should not be the case.

**Comment by RichieB2B** [comment]
I think this is a result of the fix for #407 where it was determined the output was not valid JSON (as it should be).

**Comment by iglocska** [comment]
No, it's something different, that one was about several events being
created separately as a json and then incorrectly put in a list without a
comma in between, this one is due to the json view running through
json_encode twice (once in the view, once in the JSON conversion tool).
I'll try to push a fix asap.

**Comment by Rafiot** [comment]
Thank you :)

**Comment by iglocska** [comment]
My pleasure! Keep em coming if you run into any other oddities!
