### ISSUE TITLE
fetchFeed git fatal error

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#4131]
2.4.102

was seeing git fatal error as below when running `fetchFeed`. chat on gitter and was able to stop that error by doing the following:
```
$ sudo chown -R root:apache /var/www/MISP/.git
$ sudo chmod -R g+w /var/www/MISP/.git
```

However, I then enabled `OSINT CIRCL Feed` and tons of these errors re-appeared.

The error...
```
$ sudo /var/www/MISP/app/Console/cake Server fetchFeed 14 25

Welcome to CakePHP v2.10.9 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
fatal: Not a git repository (or any of the parent directories): .git
Job done.
$ 
```

Instead of guessing... Do we need to also do
```
$ sudo chmod -R o+r /var/www/MISP/.git
```

**Comment by cvandeplas** [comment]
There seems to be something wrong with your installation. Please ensure you install MISP using the [instructions](https://github.com/MISP/MISP/tree/2.4/INSTALL) .

**Comment by gitnorty** [comment]
Hi cvandeplas, when we installed MISP, we followed the instructions on the MISP website; specifically the RedHat 7 Install instructions.  This instance has been up for about a year with no major issues; can you suggest some things to look at with regards to what might be incorrectly installed?   One thing of interest is that when I've tried reapplying the permissions in the documentation, that often times this causes issues, as if something is not right any more.  I know to look at the various log files under '/var/www/MISP/app/tmp/logs/'; but this doesn't always clearly point to what the issue is.  Any other suggestions would be very appreciated.  Thanks!
