### ISSUE TITLE
Worker status tab is missing

### ISSUE THREAD

**Issue by worldopener** [MISP/MISP#4213]
After the latest update https://github.com/MISP/MISP/commit/8057cd4128a91b579a2efcfb65061b83b964d794 the worker status tab is missing.

Was it removed or where can i find it?

**Comment by worldopener** [comment]
Except from this obvious bug, are there any planned regressions tests to catch at least API regression errors? It's a mess to update to the latest version because of bugs are not fixed in the latest release and one ends up with new bugs.

Would be nice to try at least in future to switch to a more security driven development process instead of commiting stuff and afterwards doing 3 other commits to fix bugs introduced days before (and no one saw them until someone files a bug, although the API is broken)

I like the software but it feels like a hobby project although i have to use it in an productive environment.

**Comment by adulau** [comment]
Fixed in https://github.com/MISP/MISP/commit/12ffbf991b48829a27f8f215a692b788a737ca00

As you are running the HEAD (2.4), this indeed could happen.  You can use a tagged version which is usually safer if you want to limit such issue. 

For API tests, we welcome pull-request and improvements in the current set of tests from [PyMISP](https://github.com/MISP/PyMISP/tree/master/tests). 

Thank you for the reporting.

**Comment by worldopener** [comment]
thanks for the quick fix

**Comment by worldopener** [comment]
thanks for the quick fix, it works.
