### ISSUE TITLE
Add bro output format

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#424]
Output format for Bro IDS.

Documentation on format:
http://blog.bro.org/2014/01/intelligence-data-and-bro_4980.html

**Comment by tdesrochers** [comment]
+1

**Comment by xme** [comment]
+1

**Comment by Rafiot** [comment]
Does this code help ? https://github.com/thnyheim/misp2bro

**Comment by tdesrochers** [comment]
I have seen that an i am currently utilizing it. I'd like to see the
ability built into MISP so that you could tell MISP which type of Intel the
data is and if you would or would not like to generate a notice.

The script you mentioned does part of the job and at last pull it had some
errors that needed correcting.

MISP is great and seeing it intergrate into bro I tel framework more easily
would make it more useful for a very large group of users. For right now I
am using the misp2bro.py to hack together some MISP data into my bro
sensors.

**Comment by RichieB2B** [comment]
Please submit your corrections as a pull request to https://github.com/thnyheim/misp2bro

**Comment by tdesrochers** [comment]
Pull request made already. See request #1.

**Comment by RichieB2B** [comment]
Oh, I see. You used the patches from @elhoim found at https://github.com/thnyheim/misp2bro/pull/1 Thanks!

**Comment by juju4** [comment]
This can probably be closed as
https://github.com/MISP/MISP/commit/06c15d75d1e725c48fccbf6d646d01b7a4d250ac

**Comment by Rafiot** [comment]
Yep, thanks for the reminder!

**Comment by juju4** [comment]
You welcome.

just a small note: export is available as generate/download in Web UI (https://<misp url>/events/downloadExport/bro) but not in API in same way than snort/suricata (https://<misp url>/events/nids/snort/download/false/false/tag1&&tag2&&!tag3) or it is not documented? it seems the former.

**Comment by Rafiot** [comment]
Good question, @iglocska is it in the API automatically?

**Comment by iglocska** [comment]
Sure it is! It's in the automation page. (Event actions -> automation, ctrl+f for "Bro IDS export"

@iglocska is proud that he didn't forget to document a feature.

**Comment by Rafiot** [comment]
:D

**Comment by juju4** [comment]
perfect. an entry in the book too? ;-) https://www.circl.lu/doc/misp/automation/

**Comment by iglocska** [comment]
Argh. Seems like i forgot something after all... :(
