### ISSUE TITLE
Error while trying to sync two instances - update

### ISSUE THREAD

**Issue by pabloes1337** [MISP/MISP#4684]
I have an error while I'm trying to sync two instances, I uplouded client certificate in .cer format and also server ca in .pem format. I have the newest brunch with submodules and also restarted all workers. 

2019-05-28 13:10:46 Warning: Warning (2): stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
stream_socket_enable_crypto - [internal], line ??
CakeSocket::enableCrypto() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490
CakeSocket::connect() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 247
CakeSocket::write() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 386
HttpSocket::request() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 377
HttpSocket::get() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 464
Server::runConnectionTest() - APP/Model/Server.php, line 3798
ServersController::testConnection() - APP/Controller/ServersController.php, line 1383
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

**Comment by rommelfs** [comment]
Please fill out the bug report template as good as possible in order to give people a chance to assess your situation.

The template is attached below for your convenience. 
The issue will be closed for the time being. It can easily be re-opened once the information is complete.

# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template










*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, Feature Request, support...
| OS version (server)       | Debian, ubuntu, CentOS, RedHat, ...
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1...
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Expected behavior


### Actual behavior


### Steps to reproduce the behavior


### Logs, screenshots, configuration dump, ...

**Comment by pabloes1337** [comment]
Type of issue - I have a problem while I try to connect to remote server, this server is client certificate to authorize. 
OS version (server) RHEL 7.6 Maipo
OS version (client) NA
PHP version 7.1.8
MISP version  v2.4.107 (304358b162597e2ca0fe7b0590682592ca49e566) 
Browser Firefiox/Chrome 

Expected behavior:
Full Synchronize between instances.

Actual behavior:
When I upload client and ca certificate in .pem format(base64 encoded) and run test connection I recieve error in file /var/www/misp/app/tmp/log/error.log

2019-05-31 11:54:21 Warning: Warning (2): stream_socket_enable_crypto(): Unable to set private key file `/var/www/MISP/app/files/certs/1_client.pem' in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
stream_socket_enable_crypto - [internal], line ??
CakeSocket::enableCrypto() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 490
CakeSocket::connect() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 247
CakeSocket::write() - APP/Lib/cakephp/lib/Cake/Network/CakeSocket.php, line 386
HttpSocket::request() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 377
HttpSocket::get() - APP/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php, line 464
Server::runConnectionTest() - APP/Model/Server.php, line 3798
ServersController::testConnection() - APP/Controller/ServersController.php, line 1383
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 499
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
