### ISSUE TITLE
GnuPG on CentOS/RHEL not working

### ISSUE THREAD

**Issue by SteveClement** [MISP/MISP#4796]
After some debugging the following issue becomes clear.

Tested with and without Passphrase.

[Similar issue](https://stackoverflow.com/questions/47785199/cannot-sign-document-with-crypt-gpg-fails-with-cannot-sign-data-no-passphrase)

Tested with GnuPG 2.0.2 and 2.2.9, permissions are correct.

I have no solution to this issue.

To debug, please feel free to use this [test.php](https://raw.githubusercontent.com/SteveClement/misp-test/master/test.php)

```
object(Crypt_GPG)#172 (5) { ["encryptKeys":protected]=> array(0) { } ["signKeys":protected]=> array(1) { ["CEEF34463F9E80BF"]=> array(2) { ["fingerprint"]=> string(40) "BAD85EF98A32FC8223170A0ACEEF34463F9E80BF" ["passphrase"]=> string(0) "" } } ["decryptKeys":protected]=> array(0) { } ["passphrases":protected]=> array(0) { } ["engine":protected]=> object(Crypt_GPG_Engine)#173 (28) { ["_strict":"Crypt_GPG_Engine":private]=> bool(false) ["_debug":"Crypt_GPG_Engine":private]=> bool(false) ["_binary":"Crypt_GPG_Engine":private]=> string(18) "/usr/local/bin/gpg" ["_agent":"Crypt_GPG_Engine":private]=> string(18) "/usr/bin/gpg-agent" ["_gpgconf":"Crypt_GPG_Engine":private]=> string(16) "/usr/bin/gpgconf" ["_homedir":"Crypt_GPG_Engine":private]=> string(20) "/var/www/MISP/.gnupg" ["_publicKeyring":"Crypt_GPG_Engine":private]=> string(0) "" ["_privateKeyring":"Crypt_GPG_Engine":private]=> string(0) "" ["_trustDb":"Crypt_GPG_Engine":private]=> string(0) "" ["_pipes":"Crypt_GPG_Engine":private]=> array(0) { } ["_agentPipes":"Crypt_GPG_Engine":private]=> array(0) { } ["_openPipes":"Crypt_GPG_Engine":private]=> array(0) { } ["_process":"Crypt_GPG_Engine":private]=> NULL ["_agentProcess":"Crypt_GPG_Engine":private]=> NULL ["_agentInfo":"Crypt_GPG_Engine":private]=> NULL ["_isDarwin":"Crypt_GPG_Engine":private]=> bool(false) ["_digest_algo":"Crypt_GPG_Engine":private]=> NULL ["_cipher_algo":"Crypt_GPG_Engine":private]=> NULL ["_commandBuffer":"Crypt_GPG_Engine":private]=> string(0) "" ["_processHandler":"Crypt_GPG_Engine":private]=> object(Crypt_GPG_ProcessHandler)#169 (6) { ["engine":protected]=> *RECURSION* ["errorCode":protected]=> int(0) ["needPassphrase":protected]=> int(0) ["data":protected]=> array(2) { ["Warnings"]=> array(0) { } ["KeyConsidered"]=> string(40) "BAD85EF98A32FC8223170A0ACEEF34463F9E80BF" } ["operation":protected]=> string(16) "list-public-keys" ["operationArg":protected]=> string(16) "admin@admin.test" } ["_statusHandlers":"Crypt_GPG_Engine":private]=> array(1) { [0]=> array(2) { ["callback"]=> array(2) { [0]=> object(Crypt_GPG_ProcessHandler)#169 (6) { ["engine":protected]=> *RECURSION* ["errorCode":protected]=> int(0) ["needPassphrase":protected]=> int(0) ["data":protected]=> array(2) { ["Warnings"]=> array(0) { } ["KeyConsidered"]=> string(40) "BAD85EF98A32FC8223170A0ACEEF34463F9E80BF" } ["operation":protected]=> string(16) "list-public-keys" ["operationArg":protected]=> string(16) "admin@admin.test" } [1]=> string(12) "handleStatus" } ["args"]=> array(0) { } } } ["_errorHandlers":"Crypt_GPG_Engine":private]=> array(1) { [0]=> array(2) { ["callback"]=> array(2) { [0]=> object(Crypt_GPG_ProcessHandler)#169 (6) { ["engine":protected]=> *RECURSION* ["errorCode":protected]=> int(0) ["needPassphrase":protected]=> int(0) ["data":protected]=> array(2) { ["Warnings"]=> array(0) { } ["KeyConsidered"]=> string(40) "BAD85EF98A32FC8223170A0ACEEF34463F9E80BF" } ["operation":protected]=> string(16) "list-public-keys" ["operationArg":protected]=> string(16) "admin@admin.test" } [1]=> string(11) "handleError" } ["args"]=> array(0) { } } } ["_input":"Crypt_GPG_Engine":private]=> NULL ["_message":"Crypt_GPG_Engine":private]=> NULL ["_output":"Crypt_GPG_Engine":private]=> string(1237) "tru:ot:1:1561363187:1:3:1:5 pub:-:3072:1:CEEF34463F9E80BF:1561363186:::u:::scESC::::::23::0: fpr:::::::::BAD85EF98A32FC8223170A0ACEEF34463F9E80BF: uid:-::::1561363186::9B4965E0622394416A696CE997EA760490DEDE8C::Autogenerated Key (WARNING\x3a MISP AutoGenerated Key consider this Key VOID!) ::::::::::0: sub:-:2048:1:F10B28E374DD1987:1561363186::::::e::::::23: fpr:::::::::7A9D6BB05C9AE68213B2363BF10B28E374DD1987: pub:-:3072:1:5A50B640F505126F:1561436683:::u:::scESC::::::23::0: fpr:::::::::DFA40724F0BC5CE3F6559DC75A50B640F505126F: uid:-::::1561436683::9B4965E0622394416A696CE997EA760490DEDE8C::Autogenerated Key (WARNING\x3a MISP AutoGenerated Key consider this Key VOID!) ::::::::::0: sub:-:2048:1:A64108C4BF873E52:1561436683::::::e::::::23: fpr:::::::::FDE9A59900600DD71DAE1600A64108C4BF873E52: pub:-:3072:1:53D4991A9C8CCEFC:1561437233:::u:::scESC::::::23::0: fpr:::::::::5B20FDDDDCFFFF38C6268BDB53D4991A9C8CCEFC: uid:-::::1561437233::9B4965E0622394416A696CE997EA760490DEDE8C::Autogenerated Key (WARNING\x3a MISP AutoGenerated Key consider this Key VOID!) ::::::::::0: sub:-:2048:1:801FED5BA98B3D08:1561437233::::::e::::::23: fpr:::::::::D9CC01EA288095445026985A801FED5BA98B3D08: " ["_operation":"Crypt_GPG_Engine":private]=> string(52) "--utf8-strings --list-public-keys 'admin@admin.test'" ["_arguments":"Crypt_GPG_Engine":private]=> array(4) { [0]=> string(13) "--with-colons" [1]=> string(18) "--with-fingerprint" [2]=> string(18) "--with-fingerprint" [3]=> string(17) "--fixed-list-mode" } ["_version":"Crypt_GPG_Engine":private]=> string(5) "2.2.9" } } 
```

![gpg-centos-debug](https://user-images.githubusercontent.com/362025/60070889-4c517f80-9753-11e9-9a61-78261b88ebbc.png)

**Comment by JakubOnderka** [comment]
Hi, the problem is in this script: https://github.com/pear/Crypt_GPG/blob/master/scripts/crypt-gpg-pinentry

Because it expecting that normal php is installed and not package from software collection. So far I don't know how to fix it clearly, the only fix is to change that path in shebang to real php binary location.

**Comment by RichieB2B** [comment]
So the PHP from SCL does not put it's own binary in the path so `#! /usr/bin/env php` will work? If not, you can try adding it to `env[PATH]` in `/etc/opt/rh/rh-php72/php-fpm.d/www.conf`

**Comment by redbaron4** [comment]
I had the same problem. The installation guide lists the step mentioned by @RichieB2B but it doesn't seem to have an effect.

Only way I have found for the diagnostics show GnuPG OK is by soft-linking `/opt/rh/rh-php72/root/usr/bin/php` to `php`

```
ln -s /opt/rh/rh-php72/root/usr/bin/php /usr/bin/php
```

**Comment by RichieB2B** [comment]
Very strange that php does not include it's own binary in it's $PATH.

In `/etc/opt/rh/rh-php72/php-fpm.d/www.conf` set these two variables:
```
clear_env = no
env[PATH] = /opt/rh/rh-php72/root/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
```
Then restart `rh-php72-php-fpm`, that should do the trick.

**Comment by redbaron4** [comment]
@RichieB2B Thanks for the suggestion. The lines are already present in the said configuration file (I had done the steps as part of install)  and the service too has been restarted but the same result happens.

It appears only manually soft-linking the php executable (rh-php72 one) solves the problem.

**Comment by butefr** [comment]
I tracked down this problem to SELinux. Hidden, you need to call first semodule -DB to see it in the audit logs. It blocks crypt-PGP's own crypt-gpg-pinentry when it's called by the pgp-agent because the file is not in the right security context (httpd_sys_rw_content_t instead of httpd_sys_script_exec_t)

This solved it for me:
sudo -u apache chcon -t httpd_sys_script_exec_t /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/../../scripts/crypt-gpg-pinentry

**Comment by redbaron4** [comment]
@butefr would that be an issue if SELinux is disabled or in permissive mode?

**Comment by butefr** [comment]
No, the problem disappeared when SELinux was disabled or put in permissive mode.

**Comment by RichieB2B** [comment]
Excellent! I have updated the documentation in #5763

**Comment by redbaron4** [comment]
@RichieB2B @butefr I had SELinux in permissive mode but I will still try out this suggestion.

**Comment by butefr** [comment]
Quick update guys, I noticed something but forgot to mention earlier:

The following is needed as is noted by @redbaron4  in the previous [comment](https://github.com/MISP/MISP/issues/4796#issuecomment-536482633) :

```
sudo mv /usr/bin/php /usr/bin/php.bak
ln -s /opt/rh/rh-php72/root/usr/bin/php /usr/bin/php
```

This was the only way I could get the apache user to have its /usr/bin/env php -v at version 7.3 instead of 5.6. The problem obviously affects some scripts using /usr/bin/env as a shebang. This is tricky because in the misp diagnostic page, php7.3 showed up as ok. 

There might be another way to obtain the same result of making php73 taking over the basic 5.6 install, that does not need us to play with /usr/bin/php when using the php72 or php73 scl.

For my use @redbaron4 's find is sufficient but for some people out there, breaking php56 might be a problem.

Anyhow, the easy way to test the result is to do the following obviously, and check the output for php73 (or php72, depending on your install):

```
sudo -u apache /bin/bash
/usr/bin/env php -v

```
Only then, in addition with the content of my previous [comment](https://github.com/MISP/MISP/issues/4796#issuecomment-607639833), would the problem be solved. :

`sudo -u apache chcon -t httpd_sys_script_exec_t /var/www/MISP/app/Vendor/pear/crypt_gpg/Crypt/GPG/../../scripts/crypt-gpg-pinentry`

It shoud be noted that when the symlink is put in place for overriding php56 to php73, only then putting SELinux in permissive mode, disabling it or updating the SElinux security context of crypt-gpg-pinentry corrects the bug we see here. 

I think it ties it together with @redbaron4 's previous [comment](https://github.com/MISP/MISP/issues/4796#issuecomment-608936877) about the fact he had seen the bug occuring even if SELinux was put in permissive mode. This particular scenario can occur if php is in the wrong context just discussed. 

So overall one could describe what's going on as three different bugs occuring at the same time:

1- /usr/bin/env php being wrong for the apache user even if php72/php73 scl is installed
2- Misp's diagnostic page not noticing #1 and giving php72/php73 a greenlight 
3- crypt-gpg-pinentry being in the wrong security context

**Comment by SteveClement** [comment]
I am not an RHEL expert, but moving your php out of the way like that and doing a symlink, feels wrong.

This command is usually used to enable the software collection php: /usr/bin/scl enable rh-php72

Doing anything else breaks the philosophy of scl.

**Comment by Omniru** [comment]
In my instance, I already had a version of PHP 5.4 running on the server in conjunction with 7.2. Instead of symlinking, I made sure that that I pear installed Crypt_GPG for 5.4. That way when it attempted to use /usr/bin/php the resources it required were still available to it.

> I am not an RHEL expert, but moving your php out of the way like that and doing a symlink, feels wrong.

The problem is even if you start your process using SCL it will still be broken.
