### ISSUE TITLE
Problem importing data

### ISSUE THREAD

**Issue by umbre42** [MISP/MISP#487]
Hello all,

First of all let me thank you for MISP, it is an awesome product.

I discovered it very recently and installed it on an Ubuntu distribution (a virtual machine), for a local use.

Everything works fine except functions about importing/exporting data.

For example, I get the following:
## 

The requested file was not found
## Error: The requested address '/events/downloadExport/xml' was not found on this server.

The requested file was not found
## Error: The requested address '/events/downloadExport/csv_all' was not found on this server.

Can someone help ? Thank you!

**Comment by elhoim** [comment]
Do you have any data stored?
On the export page, do you generate the files for export before trying to download them?
The export module is using some form of caching and this might be at play.

**Comment by iglocska** [comment]
Exactly, this sounds like there is no cache created yet. Just click generate and let the process finish, after that you should be able to download it.

Let me know if this doesn't fix it!

**Comment by umbre42** [comment]
Well when I click on "Generate" (any kind of format) it stays at 0% ... (checked for several minutes, and I only have 5 different events in it for now with not more than 100 attributes).

**Comment by iglocska** [comment]
With that amount of data it should be instant basically. There are two
things that could cause the issue that you are seeing:

1. the workers are not running - make sure that they are actually working
fine, just restart the workers from the admin interface. The diagnostics in
the server settings tool should also tell you if the workers do not work.

2. The directories used by the caching mechanism are not writeable - double
check the permissions for these. The diagnostics tool should tell you if
there are issues with these.

Let me know if you've managed to pinpoint what the cause was or if it's
still unresolved.

**Comment by umbre42** [comment]
The workers are running, they're on OK state.

The diagnostic shows no error.

Privileges seem ok too:

drwxrws--- 16 www-data www-data 4096 mai   13 15:47 ./
drwxr-x--- 16 www-data www-data 4096 mai    6 10:36 ../
drwxrws---  5 www-data www-data 4096 mai    6 10:32 cache/
drwxrws--- 10 www-data www-data 4096 mai    6 10:32 cached_exports/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 csv_all/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 csv_sig/
drwxrws---  2 www-data www-data 4096 mai   13 15:47 files/
drwxrws---  2 www-data www-data 4096 mai   13 15:47 logs/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 md5/
drwxrws---  2 www-data www-data 4096 mai    6 10:32 sessions/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 sha1/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 snort/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 suricata/
drwxrws---  2 www-data www-data 4096 mai    6 10:32 tests/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 text/
drwxr-sr-x  2 www-data www-data 4096 mai   13 15:47 xml/

So... Still unresolved yet.

**Comment by iglocska** [comment]
Could you try restarting your workers? Administration -> Server Settings ->
workers tab -> restart all workers

**Comment by umbre42** [comment]
I have restarted, does not work. Also, I see all my attempts to generate in administration/jobs. For each, the status is "in progress...", 0 retries, and the progress is at 0%...

**Comment by iglocska** [comment]
That definitely doesn't sound right. Could you check MISP's logs for any issues? The files that could be interesting:

/var/www/MISP/app/tmp/logs/error.log
/var/www/MISP/app/tmp/logs/resque-worker-error.log
/var/www/MISP/app/tmp/logs/resque-[the date when you tried exporting].log

If you see anything remotely suspicious / relevant for the issue just paste it here and I'll have a look!

If nothing else works, I'll write some new tools to debug the workers - either way, if the workers restart fine and show no errors then this is obviously a bug - either with the workers or with the diagnostics.

**Comment by elhoim** [comment]
@umbre42 any update?

**Comment by umbre42** [comment]
Just found this minute !

Somehow relaunching "bash /var/www/MISP/app/Console/worker/start.sh" did thing, all my exports is generated now.

**Comment by umbre42** [comment]
Thank you iglocska for the time spent in private ;-)

**Comment by iglocska** [comment]
Ahhhh, I know what happened then! I think what was going on must have been
that you started the workers as root before. I looked at the documentation
and this is indeed described there, which shouldn't happen, start.sh should
only be launched by the apache user. Basically the worker restart within
the UI could not execute because it couldn't kill the workers using the
apache user.

Glad you've managed to resolve this, I'll update the documentation!

**Comment by elhoim** [comment]
May I also suggest a feature in the diagnostics page using a combo like [getCurrentUser()](http://php.net/manual/en/function.get-current-user.php) & [pgrep](http://stackoverflow.com/questions/6403525/check-if-a-process-is-running-using-php-in-linux) or exec a ps to see the user of the start.sh process match the one used to exec the php script.
