### ISSUE TITLE
MITRE Attack Techniques Duplicated

### ISSUE THREAD

**Issue by timhux123** [MISP/MISP#4970]
Ubuntu 16.04
MISP version 2.4.112 (f568a62b154f2d98eb12093f7637e6adc806be1a)

After upgrading from 2.4.111 to 2.4.112 I'm noticing the MITRE Attack Matrix under an event shows duplicate entries for some techniques (Spearphishing Attachment, User Execution, etc...).
I performed a successful "Force Update Galaxies" under Galaxies/List Galaxies but this did not help.

![image](https://user-images.githubusercontent.com/8250365/62720862-8a87c300-b9d0-11e9-8c6f-83e1bf99cc61.png)

**Comment by iglocska** [comment]
Oh interesting. Thanks for the heads up!

**Comment by ITServ-DE** [comment]
I just upgraded two MISPs from 2.4.111 to 2.4.112, without this issue. -> works for me, can't confirm.

However, my matrix seems to be different (sorted).

![Mitre-attack](https://user-images.githubusercontent.com/50981940/62855435-84585600-bcf2-11e9-9cfe-4ac281f0485f.png)

**Comment by mokaddem** [comment]
The duplicate entries seems to be a bug. Could be caused by the part of the code that merges deprecated MITRE galaxies with the non-deprecated one. Will have a look.
Regarding the sorting, tagged elements are put at the top. Then, techniques are sorted alphabetically. So, it is likely that you will have different results.

**Comment by timhux123** [comment]
I fixed the issue by deleting the "Attack Pattern galaxy" and then performing a "Force Update Galaxies". Closing case.
