### ISSUE TITLE
Problem with GPG encryption on RedHat 6.6

### ISSUE THREAD

**Issue by ost89** [MISP/MISP#498]
Next error appeared during push/pull request:

"default pull Server: 1 Unable to perform enableCrypto operation on CakeSocket "

In diagnostic we see next error: "GnuPG installation and settings....FAIL: encrypt failed"

Turning on debug functionality, many GPG related errors were found, first one is:
"Crypt_GPG DEBUG: ERROR: can't connect to `/var/www/MISP/.gnupg/S.gpg-agent': Permission denied"

Totally the same installation works perfectly on Ubuntu.
Anybody who can help me out here?

**Comment by RichieB2B** [comment]
That is a known issue with the modifications RedHat made to GnuPG, see #413

**Comment by iglocska** [comment]
Yeah had the same issue on 6.6 - I think the solution ended up being replacing cryptGPG with a beta version. I'll try to find out what it was.

**Comment by ost89** [comment]
iglocska, could you give more information on this? What version of cryptGPG did you use?

Solution #413 does not help us.

**Comment by iglocska** [comment]
Sure, I checked my centos VMs and it's http://pear.php.net/package/Crypt_GPG/download/1.4.0b4/

From the patch notes:

This release adds support for GnuPG 2.x, supporting the latest version of RHEL and derivatives.

**Comment by ost89** [comment]
The issue has been "solved" (it's not the solution) by creating a key without a passphrase.
So the problem is at the way the gpg handels the authentication.
Any suggestion?

**Comment by iglocska** [comment]
One solution should be to downgrade to gnupg classic (1.4.19) manually,
I'll try to test it asap.

**Comment by ost89** [comment]
@iglocska, any news on this? 
Beta version doen't help us as well :(

**Comment by iglocska** [comment]
Sorry, not yet, I am traveling today, will have an update tomorrow. Sorry
for the inconvenience.

**Comment by iglocska** [comment]
OK, I was looking into this today and it's more frustrating than I
thought... There doesn't seem to be a clean way to downgrade to 1.4.19 to
be compatible with crypt_gpg 1.3 - I've installed it in a pretty dirty way
and apart from some quirks it works, but just having the beta crypt_gpg
version seems cleaner.

Next thing I'll look into whether transitioning to the gnupg extension of
php would resolve the issue (though I'm worried that they still pass the
passphrases similarly to crypt_gpg) - if yes, we could move MISP to that
instead.

I'll keep you posted here as soon as I have some news!

**Comment by ost89** [comment]
Dear @iglocska , any news on this?

**Comment by iglocska** [comment]
There is hope, I have a working Centos 6.6 with the non-beta cryptGPG
installation. Let me just start from scratch so I can note down the process!

**Comment by iglocska** [comment]
I am still running some tests whether it all works correctly but it should be resolved.

So please pull the latest version and do the following:

cd /tmp
wget ftp://ftp.gnupg.org/gcrypt/gnupg/gnupg-1.4.19.tar.bz2
tar jxf gnupg-1.4.19.tar.bz2
cd gnupg-1.4.19
./configure && make && make install

in server settings->GnuPG.binary: /usr/local/bin/gpg

This will install GnuPG 1.4.19 and point MISP to the new gpg executable. 

If you cannot access the server settings because the diagnostic stalls, just manually edit /var/www/MISP/app/config.php and add an extra entry to the GnuPG array:
'binary' => '/usr/local/bin/gpg'

**Comment by iglocska** [comment]
Wait with it still, it's not completely resolved yet, still WIP.

**Comment by ost89** [comment]
Dear @iglocska,
We again created new RSA keys without passphrase. But the import of the event (synchronisation) does not work. The error that we get:
"Unable to perform enableCrypto operation on CakeSocket ".
Please, help with this.

**Comment by iglocska** [comment]
That looks like something unrelated to the PGP issue but instead an https certificate issue - the MISP that you are trying to synchronise with, what sort of an SSL certificate does it use? If it is self-signed or if it is signed by a signing authority that is not in the default mozilla certificate store then you need to feed the certificate/certificate chain to MISP while creating the synchronisation link. 

Could you double check this? I am sorry for the slow replies I am at a conference this week but I'll try to keep my eye on this thread during the day.

**Comment by ost89** [comment]
Dear @iglocska, you were right, the problem was with self-signed certificate.

Despite this, the problem with GPG library still remains a big issue and we are waiting for solution.

**Comment by iglocska** [comment]
Sorry, I thought I've responded since but looks like I forgot. I've tried a
few solutions since then, but it seems that with that combination of
applications you are limited to a few non-perfect solutions:

1. Skip the passphrase (this is the easiest solution)
2. Use the beta crypt_GPG library
3. Install GnuPG classic in addition to GnuPG2 and use the new setting I've
pushed to redirect MISP to use the GnuPG classic executable for encryption
- I've tested this and can provide instructions for it, however, this
causes issues with SELinux. What happens is that GnuPG1 tries to disable
core dumps for itself and SELinux freaks out that the apache user is trying
change this. So the solution here would be to relax SELinux, which can make
this possibly the worst of the 3 options.

I suggest to go with option 1 since installing beta applications is not an
option for you (though it has been in beta state since 2013).

Let me know if this is an acceptable solution for you, if not we can look
into some other options.

**Comment by ost89** [comment]
Dear @iglocska, thank you for the fast reply!
We are using first solution already and it works. The question is, was is the impact on security? What are the possible risks? 
Thats why we would like to work totally according to security rules and would prefer to use the passphrase as well.

**Comment by iglocska** [comment]
Since the PGP key used by MISP is only used to sign messages and never
receives / decrypts anything I wouldn't worry about any risks.

**Comment by elhoim** [comment]
And if an attacker is able to read your private key on your server, then running a keyloger to intercept a passphrase, or search in the code for the hardcoded passphrase somewhere, is minimal effort.
Considering this as handled and closing.

**Comment by iglocska** [comment]
Just found out that http://pear.php.net/package/Crypt_GPG/download/1.4.0/ is now out of beta, so upgrading to this will resolve the issues with GPG 2
