### ISSUE TITLE
Creating MISP Galaxies

### ISSUE THREAD

**Issue by dmolina213** [MISP/MISP#5270]
Type of issue | support
OS version (server) | RedHat
OS version (client) | windows 7
PHP version | 7.2.10
MISP version / git hash | v2.4.107 ()
Browser

I dont have a bug or an issue. I just need assistance in creating Galaxies. We have a use case where we need to create a galaxy as a repository of work products, research, analysis. I found this source https://www.circl.lu/assets/files/misp-training/3.4-MISP-Galaxies.pdf.  that shows instructions on the JSON format. But does not show the location where to place the file?

I also found information on the admin guide. However, it indicates that it is still WIP. Has there been any updates to the guide?  https://www.circl.lu/doc/misp/galaxy/

thanks,

Doug

**Comment by mokaddem** [comment]
Hi @dmolina213,
The default location of the galaxies is ``/var/www/MISP/app/files/misp-galaxy``.
In order to create a new galaxy, you have four things to do:
1. Create a new file ``yourGalaxy.json`` in ``/var/www/MISP/app/files/misp-galaxy/galaxies``
2. Create a new file ``yourGalaxy.json`` in ``/var/www/MISP/app/files/misp-galaxy/clusters``
3. Launch ``/var/www/MISP/app/files/misp-galaxy/validate_all.sh`` to validate your galaxy. It will also look for inconsistencies
4. Hit the ``Update Galaxies`` button in MISP

To create the new files, just have a look at the other JSONs for the format. Also, don't forget to generate a new UUID for your entries.

Do not hesitate if you have other questions.
