### ISSUE TITLE
Unique use case questions

### ISSUE THREAD

**Issue by cbboggs** [MISP/MISP#5364]
We are attempting to use MISP in a semi-collaborative way.  The host org of the instance is the "curator" or "mentor" in this use case.  Other orgs (member orgs) are allowed to create events, but not publish them (all member org users are currently just assigned "user" role), as we would currently like publishing and all access control duties to reside with the host org - even though events are owned by the member orgs.

Currently, the users in the host org all have admin privileges.   However, separate accounts could be created and used without admin if it will help the situation.  This is applicable for a few reasons:

Host org users (as admins) can see all orgs events (even unpublished) but are currently unable to edit or propose changes currently to other orgs events (we receive an error in each case).  I understand this is outside the current intended model of MISP usage, and might not be a bug.  

If we remove admin from these host org users however, they will no longer be able to see the events, as we currently have enabled "MISP.unpublishedprivate".   We enabled it because we would like unpublished events not visible to all orgs until the collaborate review (between host org and the creating org of the event) is done and the event is published (and ready for consumption by all local orgs or synced instances).

Is there someway to make our use case work in MISP currently?

My only thought is that possibly disabling "MISP.unpublishedprivate" and using a sharing group (between the creating org and the host org) as the initial distribution level during event creation and review would satisfy our needs, but that seems cumbersome.

**Comment by iglocska** [comment]
Modifying / publishing events on behalf of others is definitely not the right way of moving forward. Generally our workflow for these issues involves using local tags.

Create a local tag called "vetted_by_curator", enforce it to be only set-able by the host org.

Add push/pull filters for the sync connections and make "vetted_by_curator" a requirement to synchronise. This will ensure that your constituents don't potentially end up with unvetted/low quality data.

For ingestion directly from your instance, ensure that you use the vetted tag as a requirement in the restSearch API queries

`"tags": {"AND": ["vetted_by_curator"]}`

Hope this helps!

**Comment by iglocska** [comment]
OK, re-reading the issue the above won't solve the issue for you as you want to actually hide the event from other users until it is vetted instead of preventing them from pulling/using the data (so it's less of a case of avoiding pollution and instead it's for access control to avoid leaking data for example).

This case is trickier. Sharing groups would indeed work, though you'd need (number of orgs - 1) sharing groups with 2 organisations each (host org + another org) to get this working, which can get a bit messy. Perhaps another alternative would be to use delegations:

Org A is working on an event, when they want a review from Org B, they create a delegation request - at which point Org B gets access. Org B reviews the event, but doesn't accept the request. Not entirely sure if this is all that clean, but I'd definitely try to avoid giving everyone admin rights.

**Comment by cbboggs** [comment]
Yeah - as discussed in Gitter chat - if we (as admins) could properly edit the attributes, then these other things wouldn't be a problem - as they are all workarounds to the initial issue.   We are presented buttons to modify and propose attributes in the UI, but always get the error message.   Appreciate your help.

**Comment by Syunek** [comment]
Hi there, i have some questions can You answer ?
