### ISSUE TITLE
Sync issue with Tags on object attributes

### ISSUE THREAD

**Issue by andurin** [MISP/MISP#5453]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| PHP version               | 7.0
| MISP version / git hash   | 2.4.119
| Browser                   | Firefox

### Support Questions

I recently noticed that Tags on object attributes won't get synced to other misp instances. Normal attribute tags are getting synced - even if only additional.

Our use case:
We ingest new MISP Events from different sources to our "MISP-A" instance and doing a first review about malicious observables. To get a QA view on those first analysis our First Level Analysts will publish some interesting events to push that event to "MISP-B" where our Second Level Analysts live. Since we focus ourself on good or bad observables we use different tagging on attribute level. From time to time an Analyst on "MISP-B" recognize some false positive tags on object attributes and remove them or of course add additional tags. Those vetted and quality approved events should then be synced back to "MISP-A".

Current situation: 
Normal attributes tagged on MISP-B will be available on MISP-A after publishing. Removed tags from MISP-B will NOT be removed on MISP-A. So tags are getting synced only additional?

Object attributes tagged on MISP-B won't be available on MISP-A after publishing. Only a guess - removed object attribute tags won't get deleted also.

Questions for support:

- Are object attributes really handled in a different way while syncing?
- Why are Tags only beeing synced additional to potential existing tags?

**Comment by andurin** [comment]
As discussed in chat, steps to reproduce:

Requirements: Two MISPs with sync from A-->B
As far as I can say it doesn't matter if push to B or pull from A or both.

1. Create an Event on "A". 
    Add a plain attribute + a object (f.e. url with fullurl, hostname, domain) to it. 
    Set an global tag also the plain attribute as also one of the object attributes. 
2. Let the event getting synced to "B"
Expectation: Event from A == Event on B

3. Now add an additional global Tag 
    to the plain attribute as also to the object attribute. 
    Publish the event again
Excpectation: Event from A == Event on B

Reality: 
Only the plain attribute get the newly added tag. The new tag on the object attribute get's lost.

**Comment by mokaddem** [comment]
Hey @andurin,
We just pushed a fix https://github.com/MISP/MISP/commit/b83e825b7bf251a3e668e2717692ca3fa9100b01 that should resolve the issue.
If you still experience other sync issues, please come back to us.
Thanks a lot for the comprehensive report!

**Comment by andurin** [comment]
Hey @mokaddem,

thanks for the fix. Tag updates are now synced in the already known 'additional' way. 
Beside that I'm very curious for the pruneOutdatedAttributeTagsFromSync() ^^

By the way: I saw that one of my sync-users, respectively the sync role of one instance, doesn't had the "tagger" permission but before the fix Tags were synced. I'm fine with spending the Tagger permission to the sync role, since it should be standard.

**Comment by mokaddem** [comment]
The idea of  ``pruneOutdatedAttributeTagsFromSync()`` is to completely mirror Tags attached to Attributes of the instance from which you are pulling from.

For example, let's say you have instance A and instance B.
1. Instance A create an Event and Attribute then proceed to tag the Attribute with ``tlp:red``
2. Instance B pull that Event from A
3. A user replace the tag ``tlp:red`` by the tag ``tlp:green`` on instance A
4. Instance B pull that Event from A
5. Instance B now has the two Tags ``tlp:red`` and ``tlp:green`` attached to the Attribute

The idea of ``pruneOutdatedAttributeTagsFromSync()`` if to force Instance B to only have ``tlp:green``.

After internal discussion, we decided not to mirror Tags due to two reasons:
- Tags can be used as filtering rules during synchronization but also for searching-related operations
- We know some organizations 'abusing' their power of site-admin and attaching Tags (as global) to Events they do not own in order to control how these Events will be propagated to their peers.

If we were to delete these additional Tags, organization will eventually loose control of their data. Thus, we are waiting the Tag soft-deletion feature so that additional Tags would not be silently removed but would be soft-deleted instead, similarly to Attributes.

I hope that it makes sense. ;)

**Comment by andurin** [comment]
> I hope that it makes sense. ;)

Absolutely. Thanks for clarify.
