### ISSUE TITLE
Attributes not visible for non-site-admins

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#5497]
On a brand new fresh MISP running on CentOS 7, only site admins can see attributes. Non-site-admin do not see any attributes. Of any events. Even the ones with distribution set to all. I must be going crazy. Something is turning `Attribute.distribution=4` into `Attribute.distribution=1` in the SQL query. Has CakePHP gone mad?

These are the attribute conditions in the params to [$this->find](https://github.com/MISP/MISP/blob/2.4/app/Model/Event.php#L2135) :
```
[conditions] => Array
 (
  [AND] => Array
   (
    [0] => Array
     (
      [OR] => Array
       (
        [0] => Array
         (
          [AND] => Array
           (
            [Attribute.distribution >] => 0
            [Attribute.distribution !=] => 4
           )

         )

        [1] => Array
         (
          [AND] => Array
           (
            [Attribute.distribution] => 4
            [Attribute.sharing_group_id] => Array
             (
              [0] => -1
             )

           )

         )

        [(SELECT events.org_id FROM events WHERE events.id = Attribute.event_id)] => 22
       )

     )

    [Attribute.deleted] => 0
   )

 )
```
They are turned into this query that never matches anything of course:
```
SELECT `Attribute`.`id`, `Attribute`.`type`, `Attribute`.`category`, `Attribute`.`to_ids`, `Attribute`.`uuid`, `Attribute`.`event_id`, `Attribute`.`distribution`, `Attribute`.`timestamp`, `Attribute`.`comment`, `Attribute`.`sharing_group_id`, `Attribute`.`deleted`, `Attribute`.`disable_correlation`, `Attribute`.`object_id`, `Attribute`.`object_relation`, (CASE WHEN `Attribute`.`value2` = '' THEN `Attribute`.`value1` ELSE CONCAT(`Attribute`.`value1`, '|', `Attribute`.`value2`) END) AS `Attribute__value` FROM `misp`.`attributes` AS `Attribute` WHERE ((((((`Attribute`.`distribution` > '0') AND (`Attribute`.`distribution` != '1'))) OR (((`Attribute`.`distribution` = '1') AND (`Attribute`.`sharing_group_id` = (-1)))) OR ((SELECT `events`.`org_id` FROM events WHERE `events`.`id` = Attribute.event_id) = '22'))) AND ((((((SELECT `events`.`org_id` FROM events WHERE `events`.`id` = Attribute.event_id) = '22') AND (`Attribute`.`deleted` = ('0')))) OR (`Attribute`.`deleted` = '0')))) AND `Attribute`.`event_id` = (1137)
```

**Comment by RichieB2B** [comment]
I finally figured this out. I had messed up my mysql schema and had attributes.distribution set to tinyint(1). This causes CakePHP to map any values > 1 to be 1 in the query because it detects it's a "boolean" type. So the fix was a simple
```
alter table attributes modify distribution tinyint(4) not null default 0;
```
I'm just surprised the `Schema status` on the diagnostics page does not catch this. It's that page that got me into messing with my schema in the first place..

**Comment by mokaddem** [comment]
Hey @RichieB2B, I finally got time to investigate why the DB schema diagnostic did not catch the error.
It turns out, I misunderstood the meaning of MySQL's `display width`.
I assumed that the column `NUMERIC_PRECISION` was also the `display width` of the column and that it was enforced MySQL side. However, it is not the case:

```
MariaDB [misp]> CREATE table tinyTest(
    tinyint(1) NOT NULL DEFAULT 0,
    tinyint(3) NOT NULL DEFAULT 0
);

MariaDB [misp]> desc tinyTest;
+-------+------------+------+-----+---------+-------+
| Field | Type       | Null | Key | Default | Extra |
+-------+------------+------+-----+---------+-------+
| c1    | tinyint(1) | NO   |     | 0       |       |
| c2    | tinyint(3) | NO   |     | 0       |       |
+-------+------------+------+-----+---------+-------+
2 rows in set (0.00 sec)

MariaDB [misp]> SELECT COLUMN_NAME, NUMERIC_PRECISION, COLUMN_TYPE FROM information_schema.columns WHERE TABLE_NAME = 'tinyTest';
+-------------+-------------------+-------------+
| COLUMN_NAME | NUMERIC_PRECISION | COLUMN_TYPE |
+-------------+-------------------+-------------+
| c1          |                 3 | tinyint(1)  |
| c2          |                 3 | tinyint(3)  |
+-------------+-------------------+-------------+

MariaDB [misp]> INSERT INTO `tinyTest` (`c1`, `c2`) VALUES (50, 50);
Query OK, 1 row affected (0.04 sec)

MariaDB [misp]> SELECT * FROM `tinyTest`;
+----+----+
| c1 | c2 |
+----+----+
| 50 | 50 |
+----+----+
1 row in set (0.00 sec)
```

You can see that you can store a larger value in `tinyint(1)` and [according to the doc](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html), it is totally normal. The display width `may be used by applications` and is not enforced by MySQL at all.
So the reason why we did not catch your issue is because the `display-length` is used and enforced by [cakephp itself](https://github.com/cakephp/cakephp/blob/master/src/Database/Schema/MysqlSchema.php#L85).
I'm considering updating the comparison strategy and adding the `display width` information with something similar to what cakephp is doing (`preg_match` on `COLUMN_TYPE`).

Unless @iglocska or anyone has another idea?

**Comment by iglocska** [comment]
Indeed, tinyint(1) will be able to store other values, tinyint(1) is basically used by the framework as a faux-boolean since it's the best we've got in mysql :) It's a nice hack from cakePHP to still have a "native" boolean type and auto infer UI elements based on that.

The preg_match strategy sounds good indeed.

**Comment by mokaddem** [comment]
I ended-up doing a simple string comparison for the diff. But a regex was needed for the SQL query generator 2bae36f214115341540acade33284170fd951662.

![image](https://user-images.githubusercontent.com/6977223/77994904-1e751900-732b-11ea-8afa-b10359b84f8c.png)

**Comment by iglocska** [comment]
![image](https://user-images.githubusercontent.com/3668672/78007894-3787c500-733f-11ea-8c60-e55943e66ff2.png)

**Comment by RichieB2B** [comment]
Sweet! I debugged this all the way to CakePHP `_convertColumn()` function myself. Quite a nasty trick they did there. I'm glad this is now part of the `Schema status` diagnostics!
