### ISSUE TITLE
new to MISP. where is the function to clean-up old feeds?

### ISSUE THREAD

**Issue by NetEyes** [MISP/MISP#5499]
Running MISP 2.4.119 using pre-built VM.
Please provide documentation for administration .. i.e.

- Feeds maintenance (add/remove/clean-up feeds > numberofdays)
- Customizing Feeds

**Comment by mokaddem** [comment]
Hi,
Feed can be configured here `/feeds/index`.
If you want to clean up ingested data, it will depends on how you configured your feed. For fixed even id, it will be easy. Otherwise, you will need to write a script.
When viewing all feed, you can also see the last time it has been cached.

For more documentation about feeds, I invite you to have a look at these [slides](https://github.com/MISP/misp-training/tree/master/a.3-misp-feed)

Cheers
