### ISSUE TITLE
Override ORG and ORGC upon import

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#550]
Sometimes we receive IOC's from our constituents that allow us to publish them, but without mentioning their organization name. It would be useful if upon import of a MISP XML the ORG and ORGC fields can be overridden.

**Comment by elhoim** [comment]
Would #472 be a viable alternative?

**Comment by RichieB2B** [comment]
Only while lacking another alternative. Pseudonims are nice but not a true alternative to anonymity IMHO.

**Comment by elhoim** [comment]
Changed from enhancement to functionality since it would require quite a bit of change (sync model, permission model, event format) to allow users to publish an event anonymously but *and* retain rights for it.
If there is no need to retain rights on it, then a quick way patch could work: adding an option in the MISP XML import to anonymise the event and log in admin logs that user X from org Y has published event Z as anonymised.

**Comment by RichieB2B** [comment]
In my use case there is no need to retain rights. Once the ORG/ORGC has changed those new ORG/ORGC will have the rights to the event.

**Comment by Rafiot** [comment]
Fixed.
