### ISSUE TITLE
Feeds UI doesnot show all default feeds

### ISSUE THREAD

**Issue by tinamina12** [MISP/MISP#5905]
# This template is meant for bug reports, if you have a feature request user the other template. 

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu, ...
| PHP version               | 7.0
| MISP version / git hash   |  v2.4.125 (d8a5ee76dcd9e6a569b58ec67ef5473399705829) 
| Browser                   | firefox

### Expected behavior
After fresh install of misp, all default feeds should be available on Feeds UI

### Actual behavior
Only two feeds are shown on Feeds UI

### Logs, screenshots, configuration dump, ...
![Screenshot from 2020-05-14 03-35-26](https://user-images.githubusercontent.com/32898278/81924461-06ccb980-9594-11ea-8b09-0b0bb2e5ed2c.png)

**Comment by iglocska** [comment]
Indeed, as of recently we've made loading them optional. Simply clock in load default feed metadata to load them all.

**Comment by RichieB2B** [comment]
First coffee, then comment on GitHub. I’m sure you mean “click on” not “clock in”.

**Comment by tinamina12** [comment]
Thank you so much :)

**Comment by palmiragomez** [comment]
Hi Tina! Sincerely hope that you read this didn't know how else to contact you so wishing this will work! you had solved the issue with urlilb2 on EvilOSX by setting up the environment -- what did you do to set up the environment ? I'm coming across the same issue that if you could post your solution I would greatly appreciate your help! gonna try myself however would love if you could assist with feedback. The issue is regarding EVILOSX urlilb2 issue was closed but solution wasn't posted --- 

appreciate your help! Thank you!
