### ISSUE TITLE
Proper way to sync many MISP instances

### ISSUE THREAD

**Issue by bit111** [MISP/MISP#5953]
Hello,
I would like to understand how to properly sync more MISP instances.
### My scenario:

- "A" Primary MISP instance (coordinator);
- Some MISP instances with _pull_ & _push_ rights (B_11, C_11, D_11, etc.);
- Some MISP instances with only _pull_ rights (Z_10, Y_10, X_10, etc.)

Each MISP instance (B, Z, etc) can only pull/push ioc from/to Organisation "A" which redistribute ioc to the other MISP instances (**Note:** each MISP instance is hosted on a remote domain)

### My idea of sync config:

- Organisation "A" has a _sync server_ for each of above organisation (B_11, C_11, Z_10, etc.) with flag on **pull** and **push**;
- organisations with pull/push right (B_11, C_11, etc) have **a** sync server with organisation A with flag on **push**
- organisations with only pull rights should automatically receive events without setting anything.

Is the above configuration correct or is better the following?

### Second idea of sync config:

- Organisation "A" just create a _sync user_ for each organisation (B_11, C_11, Z_10, etc.);
- organisations with pull/push right (B_11, C_11, etc) have **a** sync server with organisation A with flag on **pull** and **push**
- organisations with only pull rights have **a** sync server with organisation A with flag on **pull**

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| MISP version  | 2.4.126

Thanks for your support

**Comment by mokaddem** [comment]
Hey thanks for reaching out!
Considering the scenario you gave, please find some feedback below.
Note that I'm not sure if this is the exact configuration you want as I couldn't find a clear differentiation between what the other instances can do and they should do (capability vs permission).
Same goes for the sync method, you can have `pull` only, `push` only, or a combination of the two.

### Your idea 1
1. ``pull`` flag is not needed unless you plan to pull data from the other instances to **A**
2. ``pull`` flag should be set, otherwise, **B**, **C** and **D** will not be able to pull
    - But will receive data from the push done by **A**
3. This seems correct

### Your idea 2
1. **X**, **Y** and **Z** will then be able to create data on **A**
2. This seems correct
3. Even though only the `pull` flag is set, they still have the permission to create data on **A**

### Another sync configuration
So for your scenario, I would do the following:
- Instance **A**, creates a `sync user` for instance **B**, **C** and **D**
    - These instances will be able to PULL and PUSH to **A**
    - Then create a server connection from **B**, **C** and **D** to **A** with flags ``push`` and ``pull``
- Instance **A**, creates a `read only user` for instance **X**, **Y** and **Z**
    - These instances will only be able to PULL from **A**
    - Then create a server connection from **X**, **Y** and **Z** to **A** with flags ``pull``

With this configuration
- **B**, **C** and **D** can fetch data from **A** and create data on **A**
- **X**, **Y** and **Z** can only fetch data from **A**

Now if you wish that **A** automatically pushes any changes to the other instances (while letting others pull), you have to:
- Create a `sync_user` on other instances 
- Create a server connection on **A** for the other instances with the `push` flag
- Note that if you do this step only, other instances will not be able to pull but will receive the data from push

I hope it clarifies a bit the options.
Do not hesitate if you have more questions.

**Comment by bit111** [comment]
> ### Another sync configuration
> 
> So for your scenario, I would do the following:
> 
>     * Instance **A**, creates a `sync user` for instance **B**, **C** and **D**
>       
>       * These instances will be able to PULL and PUSH to **A**
>       * Then create a server connection from **B**, **C** and **D** to **A** with flags `push` and `pull`
> 
>     * Instance **A**, creates a `read only user` for instance **X**, **Y** and **Z**
>       
>       * These instances will only be able to PULL from **A**
>       * Then create a server connection from **X**, **Y** and **Z** to **A** with flags `pull`
> 
> 
> With this configuration
> 
>     * **B**, **C** and **D** can fetch data from **A** and create data on **A**
> 
>     * **X**, **Y** and **Z** can only fetch data from **A**

That's exactly what I wanted!
So, other instances that create server connection to **A** with `pull` flag have to manually run `pull updates` on server each time? **[1]**

> Now if you wish that **A** automatically pushes any changes to the other instances (while letting others pull), you have to:
> 
>     * Create a `sync_user` on other instances
> 
>     * Create a server connection on **A** for the other instances with the `push` flag
> 
>     * Note that if you do this step only, other instances will not be able to pull but will receive the data from push

This solution seems to be more automatic if [1] is true

**Comment by mokaddem** [comment]
> So, other instances that create server connection to A with pull flag have to manually run pull updates on server each time?

Exactly. Usually this process is put in CRON job so that they don't have to do it manually.

> This solution seems to be more automatic

it is
Both pull and push have their advantages
- Push is automatic and mimic real-time sharing. Hover, if the remote server is not accessible, they will not receive the updates unless **A** triggers a full push.
- Pull is triggered by the remote servers and make sure they are aligned with everything on the other side.

**Comment by bit111** [comment]
>     * Instance **A**, creates a `read only user` for instance **X**, **Y** and **Z**
>       
>       * These instances will only be able to PULL from **A**
>       * Then create a server connection from **X**, **Y** and **Z** to **A** with flags `pull`

I tried this solution: I've created a `Read Only` user on instance **A** and a sync server with `pull` right on instance **X** but when I click on `Run` button in sync server I have this error: _Remote user not a sync user_
Does it just work with `Sync User` ?

Ok, I've created a new Role of type `Read Only` **with flag on sync** and it works!

**Comment by mokaddem** [comment]
By doing so, the `read only` user can create data on server **A**. So it's no longer a `read only` user. Running the connection test makes you feel like it's an error but you should still be able to pull data.

**Comment by bit111** [comment]
Yes, it also works with `Read Only`.
So, I did further test with the new role `Read Only with sync right` and it cannot push data on server **A**
