### ISSUE TITLE
Events that belongs to org can't  be accessed if sharing group is different

### ISSUE THREAD

**Issue by JakubOnderka** [MISP/MISP#6033]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| MISP version / git hash   | 2.4.127

### Expected behavior

Events that belongs to the organization can be accessed even if the event sharing group is different.

### Actual behavior

If event is created by org that current user belongs and event is shared to sharing group that user org doesn't belongs, event cannot be accessed.

This is because of this change: https://github.com/MISP/MISP/commit/7cd21755dd512c15575c1a1ce824b896fe2bed69

The problem is that event is showed at index page, but after opening it, 'Invalid event' message is showed.

The seconds problem is that logging of this doesn't work, because `fetchEvent` is not valid action for logging.

**Comment by mokaddem** [comment]
The two issues listed here should indeed by fixed
> The problem is that event is showed at index page, but after opening it, 'Invalid event' message is showed.
> The seconds problem is that logging of this doesn't work, because `fetchEvent` is not valid action for logging.

However, the behavior to block is intentional. Do you know how you ended up with such an Event (You own it despite the fact you are not in the SG)?

**Comment by JakubOnderka** [comment]
> Do you know how you ended up with such an Event (You own it despite the fact you are not in the SG)?

Pulling from remote MISP, that has different organisation UUID that we use in our MISP instance.

**Comment by kuchynkap** [comment]
We have the same issue.

**Comment by mokaddem** [comment]
Events belonging to an organisation which is not included in the sharing group assigned to the event will not be shown on the index anymore for that organisation.
This is to avoid confusing behavior where an event is owned by an organisation but this organisation cannot view the details due to sharing group restriction.
One way to allow the org to see the event again is to ask to the remote instance to fix the SG configuration by including the owner org into the SG.

If you have an example where this is not feasible or disrupt your workflow, please let us know.
