### ISSUE TITLE
Update process lock not obvious

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP#6249]
The db update process being locked / stalled should be made more obvious on the diagnostic page, with a remedy available (or being automatic when browsing the diagnostic page?)

**Comment by mokaddem** [comment]
- In the diagnostic, you can see if the lock is set or not.
- Under the `update_progress` page, you can see when the lock will be released and you can release it manually there.

The unlock action has been put over there because before releasing it, you probably want to check if it's stalled or if it's just taking time. As the `update_progress` page shows you how the update is going in real time, I figured it's the best place.

What do you think?

**Comment by iglocska** [comment]
The problem is people aren't aware of the page / nor do they easily end up there. We're getting more and more reports of users trying to "fix" it since they just see the DB issues on the diagnostic page by running the scripts manually. The remedy scripts and the DB sanity check should not even show up in an ideal case if an update is still running - if it is locked / stalled it should be displayed there instead.

**Comment by mokaddem** [comment]
I made slight change on the UI depending on the update state.

1. If the updates are locked and the `db_version` are not the same, the diagnostic is not displayed and this message appears
![image](https://user-images.githubusercontent.com/6977223/91823606-c3c54d80-ec39-11ea-92db-06a5e1b5c222.png)


2. Which lead to the update progress page that also have been adapted to provide more info
![image](https://user-images.githubusercontent.com/6977223/91823699-e8212a00-ec39-11ea-9df9-5c7afacf554e.png)

I think it solves both this issue and this one https://github.com/MISP/MISP/issues/6248

Will push the changes upon confirmation :)

**Comment by iglocska** [comment]
That looks good to me, much more clear! Thanks.

**Comment by mokaddem** [comment]
Fixed in 5a3f50e3a606a9b58ce1f5dd524f2d6828c0a00d
