### ISSUE TITLE
Remove the default defined salt

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#625]
Change from a fixed default defined salt to one that is randomly generated at install time.
This will avoid admins locking themselves out, and cases were whole communities need password reset because the salt was not changed at install time.

**Comment by iglocska** [comment]
Sounds like a good idea indeed.

**Comment by Darkheir** [comment]
It seems to have a problem with the modification you've done:

You just modified the `AppController` file but not the `AppShell` one. So on a new install of MISP, when `UserInitShell` is launched the admin account admin@admin.test is created with the password "admin" and no salt is applied.

The authentication of the admin is later not possible since the `AppController` has set a salt and the password in the DB is not salted.

**Comment by iglocska** [comment]
Indeed, you are correct. Should be fixed now.

**Comment by rotanid** [comment]
for later reference: probably fixed in 94c72d03c80cc5dbfadc68c8ea0feadfb766b16e by @iglocska
