### ISSUE TITLE
Install database user with least privilege required, not all privileges, on misp.* tables

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6301]
I feel it's a bug that the INSTALL.sh script grants all privs to the misp database user.  The MISP server needs to read and write data at the database, but almost certainly does not need to create new tables, drop tables, grant rights to others etc.  Revise the script to grant only the least database privileges required.

I hope I have not created a duplicate, I searched the issues for "least" and other keywords but didn't find anything like this.

Thanks for listening.

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RedHat
| OS version (client)       | MacOS
| PHP version               | 7.2
| MISP version / git hash   | d06cd0d3e9c203fae88b9d8f7a3a10280813f9ec
| Browser                   | any

### Expected behavior

The grant probably should be something like this:
```
... GRANT SELECT, INSERT, UPDATE, DELETE ON ${DBNAME}.* to ...
```

### Actual behavior

As of today, tip of master branch version 2.4, the MISP install script INSTALL.sh has the following:
```
sudo mysql -u ${DBUSER_ADMIN} -p${DBPASSWORD_ADMIN} -e "GRANT ALL PRIVILEGES on ${DBNAME}.* to '${DBUSER_MISP}'@'localhost';"
```

### Steps to reproduce the behavior

View INSTALL.sh.

### Logs, screenshots, configuration dump, ...

N/A

**Comment by iglocska** [comment]
It does actually. The MISP db user is also used by the update procedure which drops / creates tables.

**Comment by chrisinmtown** [comment]
Ah, thanks for educating me.  I still am not confident the user needs privs to re-grant privs etc.  And maybe someday there should be an upgrade user that is separate from the everyday webserver user.  But if all that is just such low priority that it's unlikely to happen, feel free to close this.

**Comment by iglocska** [comment]
That would indeed make sense in the long term to separate it and encode two db users. The benefit would be somewhat limited, as both users' credentials would need to be exposed to MISP in the first place.

**Comment by chrisinmtown** [comment]
Very limited benefit, so unless you see some value here @iglocska, I'll close this issue.

**Comment by iglocska** [comment]
Yeah let's close it for now if you don't mind - we do have some plans in terms of allowing several db connections split into different tasks so maybe something to revisit then (though our use-case was more load balancing and moving the log storage to a different db).

**Comment by chrisinmtown** [comment]
I don't mind.

**Comment by cudeso** [comment]
Picking up this old issue. 

From the tests (event/attribute manipulation, taxonomies, feeds, objects, galaxies) that I did, you only need `CREATE, INSERT, UPDATE, DELETE, SELECT` during normal operations.

The idea for a setup would be to
- set the least required privileges during normal operations (thus CREATE, INSERT, UPDATE, DELETE, SELECT)
- if there's an update, change the DB-user privileges so that it can do the update, then reverting back to the least required privileges after the update

The above is not an ideal working situation but would tick a box for 'least privilege access' during normal operations.
Do you see any issues with only allowing `CREATE, INSERT, UPDATE, DELETE, SELECT` @iglocska ?
