### ISSUE TITLE
Improve handling and validation of MISP.baseUrl to allow for proxy servers

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#6387]
We run MISP behind a proxy server.  The server must push out to wee little web-browser users the correct view from the outside, which we do by configuring MISP.baseurl to something like "misp.org.company.com:34567".  And wee little browsers on the company VPN can resolve that name, life is mostly good.

But the host machine where the webapp runs has a very different network view. That view includes a different hostname and port. The local coordinates are more like "misp-dev.some.ops.company.com:443". One consequence is that the server cannot make a REST call to itself when triggered from the UI. Another consequence is validation of the base URL.  Here's an excerpt from File app/Model/Server.php, I'm especially concerned about line 3627:
```
3612     public function testBaseURL($value)
3613     {
3614         // only run this check via the GUI, via the CLI it won't work
3615         if (php_sapi_name() == 'cli') {
3616             if (!empty($value) && !preg_match('/^http(s)?:\/\//i', $value)) {
3617                 return 'Invalid baseurl, please make sure that the protocol is set.';
3618             }
3619             return true;
3620         }
3621         if ($this->testForEmpty($value) !== true) {
3622             return $this->testForEmpty($value);
3623         }
3624         $regex = "%^(?<proto>https?)://(?<host>(?:(?:\w|-)+\.)+[a-z]{2,})(?::(?<port>[0-9]+))?(?<base>/[a-z0-9_\-\.]+)?$%i";
3625         if ( !preg_match($regex, $value, $matches)
3626                 || strtolower($matches['proto']) != strtolower($this->getProto())
3627                 || strtolower($matches['host']) != strtolower($this->getHost()) ) {
3628             return 'Invalid baseurl, it has to be in the "https://FQDN" format.';
3629         }
3630         return true;
3631     }
```

**Describe the solution you'd like**

I would like a solution that lets me describe accurately to MISP the network and configuration.  And then MISP should do the right thing when it validates the base URL, it should use an appropriate host name when it tries to perform a REST call to itself when triggered from the UI, etc.  I'm sure there are more implications.

**Describe alternatives you've considered**

We are wrangling and warping our network configuration so DNS gives a usable answer in the deployment environment, but that's quite awkward.

**Additional context**

You might see #5681

**Comment by security-penguin** [comment]
It seems this issue may also be related as I am having issues with a similar setup when logging in and some other actions https://github.com/MISP/MISP/issues/4535

**Comment by iglocska** [comment]
So there are several issues mentioned above: 

1. The testBaseURL() function is indeed a bit weak in this regard, however, it's also one that has basically no impact. All it does is warn administrators if the incoming request happens through an alternate baseurl than what is described in the setting. If the check fails you'll get your setting highlighted in the configuration, that's about it.
2. For the rest client, indeed this was an issue. We have added new controls for this in October last year, you can now provide the baseurl through which MISP can reach itself locally:
![image](https://user-images.githubusercontent.com/3668672/106424956-60974b80-6463-11eb-808d-56d44b91075c.png)


@designing-penguin - your issue is unrelated and seems to be a mess up with how redirect after the login it sounds like. I'll try to figure out what's causing that for you.

**Comment by chrisinmtown** [comment]
I opened issue #6940

**Comment by chrisinmtown** [comment]
Now that the setting Security.rest_client_baseurl  is available, this issue probably can be closed?

**Comment by chrisinmtown** [comment]
Nobody answered about Security.rest_client_baseurl but it seems reasonable that the new setting makes this issue moot, so I'm closing it.
