### ISSUE TITLE
Snort export does not work?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#645]
Hi *,
I'm trying to use the REST API to get a list of Snort events. Based on the documentation, I'm trying this URL:
https://x.x.x.x/events/nids/snort/download (The Authorization header is added to the HTTP request).
I don't get a list of Snort events but instead the standard website. Another URL is ok (like /events/hids/md5/download). Any idea?

**Comment by Rafiot** [comment]
If possible, I would recommend you to use the [python API](https://github.com/MISP/PyMISP) which uses the following URL: 
https://x.x.x.x/events/nids/suricata/download/{Event_ID}

FYI, it comes with an example: https://github.com/MISP/PyMISP/blob/master/examples/suricata.py

Just in case, which version of MISP are you using?

**Comment by xme** [comment]
Ok, I'll test the python API... (I'm running 2.3.0)

**Comment by elhoim** [comment]
You can enable debugging which should give you a more informative error message instead of just a redirect. This can be done under **Server Settings\Misc settings**. Don't forget to disable it after your debugging session is done.

This API call will give you all the generated rules based on various attributes, you can see more details in https://github.com/MISP/MISP/blob/master/app/Lib/Export/NidsExport.php#L48
Which means they can be a lot of them.

Since it it generating quite a lot of rules, I would bet it is hitting the PHP memory limit per script (128MB by default IIRC). The error message you get with debugging enabled should say something about this.

I suspected based on a OOB discussion we had that you want to export all snort rules attributes, which would mean /attributes/text/download/snort/false/false/false/ is more appropriate.

You get more details on those API calls under /automation/ than under /pages/display/doc/using_the_system#rest

**Comment by xme** [comment]
I switched to PyMISP... better results!

**Comment by elhoim** [comment]
@xme Can I consider this closed?

**Comment by xme** [comment]
Yep, tx!
