### ISSUE TITLE
Delegation of events only allows selection of local organisations

### ISSUE THREAD

**Issue by Alanpaice** [MISP/MISP#6508]
The feature states: " If you want to publish an event without you or your organisation being tied to it, you can delegate the publication to an other organisation. That also means they will take the ownership of the event."

How ever testing on MISP v 2.4.130 you can only delegate to local target organisations, and not any remote organisations.
If there are no local organisations set up, then the drop down menu for the target org shows blank.

If this is by design that only a local org can be used to delegate, it is not clear in the documentation.

I am testing MISP as a part of an MSc dissertation, so would be happy to test the feature again and give some feed back..

**Comment by iglocska** [comment]
It is by design. Basically the event to be delegated is excluded from the synchronisation mechanism inherently (as it is required to have it set to your organisation only) - so it would never reach the recipient.

The feature is mostly there for ISACs or MISP networks with a spoke - hub topology, where organisations wishing to delegate the publishing create the data on the hub instance in an effort to get the community leader (the ISAC for example) to take custody of the event.

**Comment by Alanpaice** [comment]
Thank you for the clarification. I will add to the Book for update.
