### ISSUE TITLE
cake Admin updateObjectTemplates error: Could not update object templates

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#6708]
2.4.133

Would apreciate some help on how to isolate root cause of the error when trying to update object templates. Did not appear to be anything logged in `debug.log` nor `error.log`. (note: `user_id 14` has `role_id 1`)
```
$ id -a
uid=0(root) gid=0(root) groups=0(root)
$ cd /var/www/MISP
$ app/Console/cake Admin updateObjectTemplates 14

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Could not update object templates
$ 
```

**Comment by chrisinmtown** [comment]
That cake command first runs AdminShell#updateObjectTemplates which is here:

https://github.com/MISP/MISP/blob/ce96003b8997e348ed3b0870162c590fb734e5b1/app/Console/Command/AdminShell.php#L205

That function reports success if the result (maybe an array?) is nonempty, and failure if the result is empty; it doesn't seem to have any way to report an error.  The AdminShell method calls ObjectTemplate#update() which is here:

https://github.com/MISP/MISP/blob/ce96003b8997e348ed3b0870162c590fb734e5b1/app/Model/ObjectTemplate.php#L50

That function runs thru directories at path files/misp-objects/objects trying to find definition.json files, read them, check if their version number is greater than the in-memory version, etc. If all that passes, or if the mysterious 'force' flag is somehow enabled, then it calls __updateObjectTemplate() which is here:

https://github.com/MISP/MISP/blob/ce96003b8997e348ed3b0870162c590fb734e5b1/app/Model/ObjectTemplate.php#L97

That function validates and returns errors if problems are found. But none of the functions listed above log any debug details.  Without a bit of insight, I am struggling to know if the update operation is simply finding zero items that need to be updated, or if something is failing during the attempted update.

Next I will try setting force to true, in desperation to get more info.

**Comment by chrisinmtown** [comment]
Well, today I learned that the message is not exactly an error - it just means no action was taken.  Unfortunately that might mean errors occurred, or it might not -- logging/reporting is deficient in the object template features.

FWIW, we were trying to load two locally defined templates.  Someone put hand-constructed UUID values into our definition.json files.  MISP happily loaded one but not the other.  I speculate it failed silently when it tried to load the second, but that's a guess because no error came back. I replaced the hand-constructed UUID values in both definition.json files with values from the linux uuidgen command, then both loaded as expected.

I opened new issues that narrowly describe behaviors I consider to be bugs.  You may wish to close this slightly broader issue.
