### ISSUE TITLE
Issue when importing STIX2 from OTX

### ISSUE THREAD

**Issue by digihash** [MISP/MISP#6756]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | Win10
| PHP version               | 7.3.19-1~deb10u1
| MISP version / git hash   | v2.4.134 (158036f)
| Browser                   | NA

### Expected behavior
Everything in the STIX2 format to be ingested correctly into the MISP format

### Actual behavior
Domains in a STIX2 file from OTX are shown in some strange STIX2 objects with domains in it.

See screenshot:
![image](https://user-images.githubusercontent.com/1122246/102230336-0ced9480-3eed-11eb-9220-804f1db5bfc0.png)

Also, MITRE ATT&CK framework techniques were added as Attack-pattern objects which is in a sense correct, but the galaxy exists for this technique with exactly the same T-code, name, references, etc. So the Galaxy could just as well be added instead of adding this object in the event.

### Steps to reproduce the behavior
Import the following OTX STIX2 file in an event: 
[5fd825b7fa4eb2223a0cf812.zip](https://github.com/MISP/MISP/files/5696632/5fd825b7fa4eb2223a0cf812.zip)

This STIX2 file came from OTX on https://otx.alienvault.com/pulse/5fd825b7fa4eb2223a0cf812.

**Comment by chrisr3d** [comment]
The issue with the domain name indicators is the patterns are not valid. According to the official documentation, the correct way to define a domain name in STIX 2.0/2.1 is:
```
# Within an observable object
{
    "type": "domain-name",
    "value": "example.com"
}

# The equivalent as pattern
"[domain-name:value = 'example.com']"
```

Nonetheless I updated the attack-pattern, course-of-action and vulnerability objects import to check whether their name matches an existing galaxy (7692e7f):
- If there is a match they are imported as galaxy
- Imported as MISP object otherwise
