### ISSUE TITLE
False error in Database schema diagnostic: 

### ISSUE THREAD

**Issue by LordNeko261** [MISP/MISP#7200]
The Database schema diagnostic shows us the following error present in the database:

![image](https://user-images.githubusercontent.com/68002803/110989683-84a75000-8372-11eb-845c-3942754925dd.png)

We believe that it is a false positive since when applying the corrective measure, the Mysql server notifies us that this type of field cannot have default values

![image](https://user-images.githubusercontent.com/68002803/110989839-c59f6480-8372-11eb-8e71-bcd95cbb56aa.png)

Anyone have any ideas about it? Thanks in advance

**Comment by chrisinmtown** [comment]
Duplicate of https://github.com/MISP/MISP/issues/7137

To help people find this issue, it probably would help to include critical key words like cerebrates, description, null; super difficult to do keyword search on images in 2021.  Maybe someday :/

**Comment by iglocska** [comment]
Indeed that looks like a bug, text fields cannot have a default value at all. @mokaddem - could you have a look?

**Comment by chrisinmtown** [comment]
#7137 points out that the quotes around the word NULL are probably the problem, should be removed, then the error is gone.

**Comment by enjeck** [comment]
Details from #7137, reported by @dpreuveneers

---------------------
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| PHP version               | 7.2
| MISP version / git hash   | 2.4.140

### Expected behavior

After upgrading MISP, the diagnostics tool reports that the database schema is inconsistent, but the 
the recommended action to fix the schema does not work.

### Actual behavior

The MariaDB client returns an error when attempting to manually fix the schema.

### Steps to reproduce the behavior

The recommend action to fix the schema is: 
`ALTER TABLE cerebrates MODIFY COLUMN description text DEFAULT "NULL" NULL COLLATE utf8mb4_unicode_ci ;`

The MariaDB client returns the error message: 
`ERROR 1101 (42000): BLOB/TEXT column 'description' can't have a default value`

Not sure if this is a proper fix, but the https://github.com/MISP/MISP/blob/2.4/db_schema.json file defines at line 710 for the `description` column in `cerebrates` a `column_default` property with the value `"NULL"` (i.e. with double quotes). After changing `"NULL"` to `null`, i.e. similar to other columns, the schema inconsistency is gone.

**Comment by dpreuveneers** [comment]
If you would like me to confirm whether the issue I reported in #7137 is resolved, let me know.

**Comment by PROTechThor** [comment]
> If you would like me to confirm whether the issue I reported in #7137 is resolved, let me know.

@dpreuveneers Not resolved yet. Just closed as a duplicate of this ticket.

**Comment by LordNeko261** [comment]
Hi guys,
First of all, thank you very much for your answers! It has been very useful. After checking the "db_schema.json" file, the "description" column of the "cerebrates" table had a default value of "NULL". We have replaced it with null and the problem appears to have been resolved.

Thank you very much again!

**Comment by mokaddem** [comment]
Thanks for the report!
It's now fixed on the lastest version (92dc815)
