### ISSUE TITLE
IOC import not saving

### ISSUE THREAD

**Issue by abulhol** [MISP/MISP#725]
"Populate from OpenIOC" does not report any errors, but also does not save anything.
I have tried with our own reports, and also with example reports from openioc.org, e.g. http://openioc.org/iocs/ea3cab0c-72ad-40cc-abbf-90846fa4afec.ioc

MISP says:
    Results of the import:
    13 attributes created successfully, 4 indicators could not be mapped and saved.

But if I then view the event, there are 0 attributes. debug.log and error.log do not report any error.

**Comment by adulau** [comment]
I tried to reproduce this on a MISP 2.3.163 but I was able to import the OpenIOC sample ea3cab0c-72ad-40cc-abbf-90846fa4afec.ioc. The attributes were properly created. Are you running the latest 2.3.163?

**Comment by abulhol** [comment]
Yes, I pulled the latest changes this morning, 2.3.163 is showing at the bottom of the web page. 
The strange thing is that sometimes the attributes get added, but mostly not, but there is also no error.

**Comment by abulhol** [comment]
I think I know where the problem is: I have added the same OpenIOC files several times, so the attributes only got saved the first time. 
However, MISP should tell me if I am uploading the same attributes again, shouldn't it?

**Comment by abulhol** [comment]
It also seems that the mapping only works selectively for IOC search terms. E.g. MISP cannot map the following indicator:
```xml
         <Indicator operator="AND" id="e569dbd8-21be-4ce0-a095-2e58368039db">
            <IndicatorItem condition="contains" id="ee3aca29-1e2d-42ea-874d-76a76fd91351">
               <Context document="RegistryItem" search="RegistryItem/Path" type="mir"/>
               <Content type="string">HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run</Content>
            </IndicatorItem>
            <IndicatorItem condition="contains" id="b78001b0-c2f0-4493-8aad-2ab9c0a742c3">
               <Context document="RegistryItem" search="RegistryItem/ValueName" type="mir"/>
               <Content type="string">CdnCtr</Content>
            </IndicatorItem>
            <IndicatorItem condition="contains" id="01310544-f940-4c6c-a2e3-0048dc02412c">
               <Context document="RegistryItem" search="RegistryItem/Value" type="mir"/>
               <Content type="string">C:\Program Files\CNNIC\Cdn\cdnup.exe</Content>
            </IndicatorItem>
         </Indicator>
```
but it does map this one:
```xml
         <Indicator operator="AND" id="c5bcbe62-2e9d-405f-95f9-91be6b393759">
            <IndicatorItem condition="contains" id="b343a993-4d36-4933-bccf-8f746f68d1c7">
               <Context document="RegistryItem" search="RegistryItem/Path" type="mir"/>
               <Content type="string">HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce</Content>
            </IndicatorItem>
            <IndicatorItem condition="contains" id="64cae859-18e7-4b8d-a847-9db4e7f200c7">
               <Context document="RegistryItem" search="RegistryItem/Text" type="mir"/>
               <Content type="string">"C:\Program Files\CNNIC\Cdn\cdnrenew.exe" pre</Content>
            </IndicatorItem>
         </Indicator>
```
What is going on here?

**Comment by adulau** [comment]
Yes, you're right. If the attributes already exist, those won't be added.

Regarding the logging, it's indeed a valid point. It's usually the case when adding existing attributes to an event, you should have an alert bar (red on the top). But there is indeed something missing while dealing with OpenIOC in order to notify the users.

Concerning the other point, it seems the RegistryItem/ValueName which is not properly map to regkey|value. @iglocska could this be a bug?

**Comment by iglocska** [comment]
Sounds like a bug, will have a look when i get home

**Comment by iglocska** [comment]
OK just had a look at that example: The OpenIOC import in MISP has a major inherent weakness due to the flat data structure. 

Generally anything that is within an "AND" branch is discarded by the parser, apart from a few exceptions - compositions that can be mapped to a MISP composite type (for example filename|md5). Otherwise we would run the risk of misinterpreting the information that is passed to MISP (Just saving the filename and extension from an import leads to false positives if we disregard a third "AND" ed term such as filesize - iexplore.exe is not always malicious, but it ca be malicious is the filesize or the hash is a specific value)/ 

In the case of registry entries we can indeed make an exception to the above mechanism though as the MISP regkey|value is mostly used to store registry path + key | value. I'll look into adding a mechanism for detecting this particular triplet of data and I'll add some detection for the same OpenIOC file being added again to the same event.

**Comment by iglocska** [comment]
I've pushed a patch that should:

- allow you to push the same OpenIOC file to several events
- correctly map the regvalue
- allow for the valid regkeypath/regkey/regvalue combo to be converted to MISP's regkey|value attribute

**Comment by abulhol** [comment]
Hi Andras,
I see your point. Basically, the mapping will not work in many cases because OpenIOC AND branches define composite indicators, while MISP mostly collects single attributes. So e.g. this:
``` xml
<Indicator operator="OR" id="7cac8342-fc61-425d-8f38-c2cda2bd3ece">
      <Indicator operator="AND" id="587927cc-77ee-40d4-8626-3fad5fdef53f">
        <IndicatorItem id="2eda84b9-9e4e-482e-b984-537269655de2" condition="contains">
          <Context document="Network" search="Network/DNS" type="mir" />
          <Content type="string">www.hansmuellersvirusschleuder.de</Content>
        </IndicatorItem>
        <IndicatorItem id="66da9f51-7d34-4d5e-b439-22fe6bd262d3" condition="contains">
          <Context document="Network" search="Network/HTTP_Referr" type="mir" />
          <Content type="string">155.233.175.233</Content>
        </IndicatorItem>
      </Indicator>
``` 
would be 2 attributes in MISP, e.g. "domain" and "ip-src", because there is no composite attribute domain|ip. Correct?

**Comment by iglocska** [comment]
That is indeed correct. If you find any examples of indicators that should
map with this limitation in mind but don't, let me know and I'll quickly
add the mapping for them.

Again, thanks for reporting all of these issues!

On Mon, Nov 23, 2015 at 8:39 AM, Benjamin Gathmann <notifications@github.com

**Comment by abulhol** [comment]
Would it also be easy to add new composite types to MISP? Here are some good candidates:
domain|ip
GETrequest|ip
POSTrequest|ip

**Comment by iglocska** [comment]
Definitely an interesting idea. I've added it over here: 

https://github.com/MISP/MISP/issues/460
