### ISSUE TITLE
Automation key Misp

### ISSUE THREAD

**Issue by aymenbnl** [MISP/MISP#7265]
I install MISP today in virtual machine "ubuntu 20.04" but i don't find my Automation key,  i try to find it by search in  "/users/view/me" but i find nothing.
can someone help me where i can find it.
Thank you.

**Comment by Wachizungu** [comment]
Screenshot of the page  you mentioned:

![image](https://user-images.githubusercontent.com/9868873/112771469-5d1bdd00-902c-11eb-96d1-c1c7d89cdfd2.png)

If you did not enable advanced_authkeys, see the first part (you can view the key by clicking on the eye icon).
Otherwise, if advanced_authkeys is enabled, use the add authentication key button after expanding auth keys by clicking on it.

Please add a screenshot next time as it makes it easier to tell what you were looking at / if you have a different view.

**Comment by aymenbnl** [comment]
my problem that i don't find the Auth key even the Add authentication key 

![166527802_194227205542362_629113327925059717_n](https://user-images.githubusercontent.com/76562306/112831947-8cfacd00-908c-11eb-99a1-8fc3940368a0.png)
![167310319_145865047445134_6388934331351352654_n](https://user-images.githubusercontent.com/76562306/112831951-8e2bfa00-908c-11eb-82b0-2581fde775d1.png)

**Comment by Wachizungu** [comment]
Did you click on auth keys to expand it?

**Comment by aymenbnl** [comment]
in this case i make my own key or what i do exactly ??
![166441658_504260063910762_8481869669626881108_n](https://user-images.githubusercontent.com/76562306/112838047-8b350780-9094-11eb-8dd9-b794fbdb8e1e.png)
![166553836_270964224662208_1495696570992761879_n](https://user-images.githubusercontent.com/76562306/112838053-8c663480-9094-11eb-8ab7-59cf05e7650e.png)

**Comment by Wachizungu** [comment]
Yes, just create your key / set the values as you want. You'll get to see the key once and have to note it for later use.

You can delete the key  later and / or create new ones if you feel like.

**Comment by mokaddem** [comment]
Also replied here
https://github.com/MISP/PyMISP/issues/724

**Comment by aymenbnl** [comment]
thank you very much it worked for me
