### ISSUE TITLE
Store event attachments as database blobs not in dirs like /var/www/MISP/app/files/1234

### ISSUE THREAD

**Issue by chrisinmtown** [MISP/MISP#7371]
The MISP server stores attachments like PDF files to its filesystem in directories like /var/www/MISP/app/files/<EVENTID>/

I would like to request that the content is stored to the database in a blob store, with the IDs of the blobs in the event.

I justify this by our use of multiple servers for reliability and the difficulty of keeping server filesystems in sync.  If a web server fails, traffic is automatically sent to the secondary server.  We replicate content /var/www/MISP/app/files periodically, but in case of sudden failure we will lose what users upload.  If the database is used, there's far less risk of loss when a MISP web UI server fails.

You can probably tell I'm not a fan of the mixed model of data storage, with most user data going to Mariadb/mysql and a bunch more going to the filesystem.  Spreading user data over multiple stores creates operational nightmares for us.

**Comment by jloehel** [comment]
What is about sharing a volume for `/var/www/MISP/app/files` between the instances? In my point of view the folder `files` should be not part of the repository. It should point to `/var/lib/misp/files/`. You can mount what ever you want there and share it between the instances. I added a sym-link for that but it would be nice to make it configurable. It would help to improve the docker setup, too.

**Comment by chrisinmtown** [comment]
Thanks @jloehel for the comment but I don't want to argue about whether directories below /var/www/MISP/app are local or network filesystems.  I think a guiding design principle should be that all user-uploaded data, both admin and non-admin, should go to the big MISP database; and the /var/www/MISP/app tree should have only code and system configuration.

**Comment by jloehel** [comment]
> ... and the /var/www/MISP/app tree should have only code and system configuration.

I think so, too. That bothered me right from the beginning because it was not really straight forward to containerize it. But I would go a step ahead and would say even configuration files should be not part of it. They should go to `/etc/` and for containers it should be possible to set [configuration files](https://docs.docker.com/engine/swarm/configs/) or configure it via secrets and ENV variables.

>  I think a guiding design principle should be that all user-uploaded data, both admin and non-admin, should go to the big MISP database;

I disagree. Files should be saved on a file based storage. Maybe in a object store like s3, minio, ... I see a few issues here:

- It's not a FILE. You can not use seek(). Streaming gets difficult. A few exceptions are `FILESTREAM` for mssql, `BFILE` for Oracle, LargeObjects for PostgreSQL. Is there something similar for MySQL pls add?
- The database bloats. Because of the query history. (disk/memory)
- Filesize limitiation of Blobs. It would be necessary to store everything as `LONGBLOB`.
- Backups/Replication takes longer. Maybe races

I would make an exception for YML and JSON files or more general if the dbms is able to understand the file format.

**Comment by chrisinmtown** [comment]
Bloat? Our correlations table has 6M, our logs table has 85M, our attributes table has 25M rows. Fewer than 150 of those attributes (one hundred fifty) are file attachments, total size on disk 64MB.  I think it's a waste of effort to fuss over optimization of data that is less than .001% of our store. Keeping all the user data together makes operations life less error prone during *difficult* times like upgrades, migrations and backups.

**Comment by jloehel** [comment]
> Bloat? Our correlations table has 6M, our logs table has 85M, our attributes table has 25M rows. Fewer than 150 of those attributes (one hundred fifty) are file attachments, total size on disk 64MB. I think it's a waste of effort to fuss over optimization of data that is less than .001% of our store. Keeping all the user data together makes operations life less error prone during _difficult_ times like upgrades, migrations and backups.

This might be true for your use-case. Maybe someone else saves there a few huge files or a lot of small sample files. Think about huge files like pcaps, dd images or memory dumps there. I would vote for a configurable option.

But I need to agree that the upgrade and migration right now is not optimal because the data/configuration is not strictly separated from the code. Thanks for starting the discussion. In example [HAMISPA](https://github.com/0xtf/HAMISPA), @0xtf saves the whole app repository in a EFS. This looks not optimal for me. One EFS for `files`, `configurations`, `images`, ... should be enough.

**Comment by adulau** [comment]
There are many disadvantages of storing large binary object in a DBMS which clearly outperform the advantages of unicity. 

- Loading large blob increase the need of memory by a significant factor (compared to a filesystem cache)
- Backups/dumps will take much more time and including restore
- Updating schema and especially alter table will become much slower
- Performance will drop as memory access will competing with the indexes
- Filesystem and mmap is clearly outperforming for large file

**Comment by iglocska** [comment]
Yeah I totally don't see the advantage of moving to blobs for the file attachments. Knowing of several instances where the sample store is larger than the DB size, it really depends on what you share / what you store. 

Fully agreed with @jloehel on the separation of concerns, we're planning on moving all content files to a detached location from the codebase for easier segregation of user data, but it won't happen over night.

**Comment by chrisinmtown** [comment]
Ok I know when I'm beaten.
