### ISSUE TITLE
Offline install?

### ISSUE THREAD

**Issue by xme** [MISP/MISP#738]
Hi *,

Anybody already installed MISP in offline mode? (read: without Internet connectivity). 
I can download packages and install them manually but what about the installation steps that require access to online data like "pear"?

/x

**Comment by elhoim** [comment]
It seems like you can download pear packages offline; according to [this](http://webcache.googleusercontent.com/search?q=cache:c3gyX41rXhsJ:pear.php.net/manual/en/guide.users.commandline.installing.php+&cd=1&hl=en&ct=clnk&gl=us&client=firefox), using the cached page since the [live page](http://pear.php.net/manual/en/guide.users.commandline.installing.php) was 404 when I tried.

**Comment by elhoim** [comment]
If you are successfull, could copy/paste the steps here or create a list of instructions to help other entities trying to achieve the same thing?

**Comment by xme** [comment]
pear.php.net suffered of a hard drive failure... :-( Waiting for a restore soon!
I'll make a wrapup once completed...

**Comment by Rafiot** [comment]
@xme did you manage to finalize the installation?
