### ISSUE TITLE
Object embed in table in event report breaks markdown rendering

### ISSUE THREAD

**Issue by rainman-a** [MISP/MISP#7421]
On writing an event report I built a table and embedded objects in it. The markdown would not render until I removed the table . It appears that embedded objects, tags, or attributes in an event report table break the rendering in browser.

**Comment by mokaddem** [comment]
Hey,
Thanks for the report!
I pushed a fix (a5b10ce9a853818516ad242a9ea01480d0a421eb) in the dev branch.
I consider it to be temporary because I don't really like this solution and I'm waiting for the team at markdown-it to look at a PR.
If they were to consider that it breaks their model, we'll at least have a solution on MISP side.

**Comment by rainman-a** [comment]
Thanks! I’m looking forward to working with this!
