### ISSUE TITLE
Problem with MISP feeds

### ISSUE THREAD

**Issue by NailBash** [MISP/MISP#7424]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       |CentOS 7
| PHP version               | 7.2.24
| MISP version / git hash   | 2.4.143 (fae511938867cea995bfb7ad6203c104d1516776) 

I have very strange behavior of feeds. I added my custom feeds and downloaded it to MISP, it becomes event. Then I deleted event and tried download feed again, but I have message "Error: Invalid event!". 
![изображение](https://user-images.githubusercontent.com/29750691/118975275-468b6580-b98d-11eb-8a47-d3a63fdb58f5.png)
If I try to delete event number (write empty value to event id field ) it stay same, when I closing feed settings. If I trying "new event each pull" it doesn't create new event.
Please help.

**Comment by Tommi852** [comment]
When you deleted the event where that feed was going, the event was most probably added to Event Blocklist. So MISP is blocking the creation of that event.
You can either remove the event from blocklist or you can use ThreatFox MISP feed instead of the CSV feed you seem to be using. You can find the MISP feed from Abuse.ch page [here.](https://threatfox.abuse.ch/export/.) See the part where it says Daily MISP Events.

**Comment by iglocska** [comment]
Basically when you set up a feed as a "fixed event" target feed, it actually does an additional thing internally on your first pull: It sets the event_id setting of the feed to the event that is created on the first ingestion. Since you've deleted it, it keeps trying to update an event that no longer exists.

Simply edit the feed's config and change the "event_id" field to 0 and it will create a new event on the next ingestion.

**Comment by NailBash** [comment]
Thank you for answers. Well, I accidentally put more than one symbol in csv delimiter and didn't recognize it until now. Sorry. In time of feed downloading I get this error messges in logs
```
2021-05-21 07:11:06 Notice: fgetcsv(): delimiter must be a single character in [/var/www/MISP/app/Lib/Tools/TmpFileTool.php, line 84]
```
When I replaced it with one symbol everything become ok.
