### ISSUE TITLE
to many redirects after first login login new install

### ISSUE THREAD

**Issue by phate1** [MISP/MISP#746]
working through the read me file and all installed ok but when logging in with the default admin account for the first time I get am getting to many redirects error on both chrome and firefox
running CentOS release 6.7 
Apache/2.2.15

no errors etc seen in the log files listed at the bottom of the readme file
was trying to setup with https with self signed cert but reverted to *80 http and getting the same issue
nothing in /var/log/httpd/misp.local_error.log
/var/log/httpd/error_log just shows :
/var/www/MISP/app/tmp/logs/[4174]: 2015-12-05 21:54:09 Notice: User (1): admin@admin.test -- login

any help much appreciated

somewhat new to Linux and very new to web servers be gentle :)

**Comment by Rafiot** [comment]
Sorry for the late answer, did you solve the problem now?

**Comment by Watnegutten** [comment]
I have the same issue although my logs have some entries.
running CentOS 7.1, Apache/2.4.6

**Comment by Rafiot** [comment]
And what is in the logs?

**Comment by iglocska** [comment]
Too many redirects can be caused by MISP not being able to access Resque in the /Vendors dir. @Watnegutten has been very helpful in trying to debug this. 

Basically it can be due to several reasons:
1. The last lines of core.php are left commented out
2. Resque is not installed correctly:

cd /var/www/MISP/app
curl -s https://getcomposer.org/installer | php
php composer.phar require kamisama/cake-resque:4.1.2
php composer.phar config vendor-dir Vendor
php composer.phar install
1.  following the installation instructions I ran into some issues with PHP 5.6 that I had to solve first. In @Watnegutten's case the installation of (2) failed because the PHP 5.6 install's failure. 

I'll retest the CentOS installation guide this weekend and if anything goes wrong I'll make some adjustments and will post the steps to resolve this issue over here.

**Comment by iglocska** [comment]
OK, just did a few rerun of the CentOS installation guide that @RichieB2B has created and it looks like I simply messed up on Friday when I tried it and PHP 5.6 was not correctly installed. 

I went through it step by step on a fresh minimal CentOS 7 installation and in the end everything worked flawlessly - I think have simply missed a step while copy-pasting several lines at a time.

**Comment by RichieB2B** [comment]
Good to know it wasn't my fault. ;-)

**Comment by iglocska** [comment]
Definitely not, the CentOS installer is actually much, much better than the Ubuntu one. I'll try to copy a lot of your stuff when I get around to it.

**Comment by Watnegutten** [comment]
I had to reinstall following the guide - apparently that fixed the issue. I might have done something wrong along the way.

**Comment by elhoim** [comment]
Good news!

Thanks for the update!

**Comment by hetzbh** [comment]
Well, it's still happening. CentOS 7.2 (1511) fresh install and following the instructions [here](https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.centos7.txt), redirect loops after first admin@admin.test when it tries to rech /users/terms page. Log files (either in /var/log/httpd nor in /var/www/MISP/app/tmp/logs/ ) doesn't show any helpful info.

**Comment by YOLOP0wn** [comment]
find a solution there, may you should try it 

https://github.com/MISP/MISP/issues/1008

**Comment by nealkeating** [comment]
Had the same problem tonight while installing the xINSTALL.centos7.txt Guide (which is awesome btw) on CentOS 7. 

I got the aforementioned error upon first login.  Used the info from @Antho59's recommended link above and found that putting a " http://" in front of my FQDN in the baseURL variable within /var/www/MISP/app/Config/config.php fixed the issue for me.

Hope this helps someone else save some time
