### ISSUE TITLE
MISP integration with TheHive

### ISSUE THREAD

**Issue by ghost** [MISP/MISP#7503]
Good Afternoon,

I have a running instance of MISP and I have am having issues getting it to integrate with TheHive.

I created an API user that has a role of publisher and copied that Auth Key into the application.conf file for TheHive.

Now side-note, I put the MISP instance on the same instance of TheHive. Not sure if that's a good practice or not, so please let me know.... but attached is what I have for the MISP portion of the application.conf

I also am not sure what the instance name of my MISP is, so I left it at default MISP. Let me know if you need anything else from me or have any questions. Thanks!

![hivemisp](https://user-images.githubusercontent.com/61601721/122287746-4a90a180-cebf-11eb-8bd7-0ef4553923d3.png)

**Comment by rommelfs** [comment]
If you didn't experience any problems, it's a good start. Otherwise, please explain what the issue is and attach meaningful logs.

(I for my part don't know the expected format within the config file of The Hive, but it looks like the entire module block is commented out and not taken into consideration by The Hive.)
