### ISSUE TITLE
MISP install error

### ISSUE THREAD

**Issue by Sshahar** [MISP/MISP#7515]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu 20.04
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version | 2.4

### Support Questions
Running the installation script as follows:
```
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c
```
I've received the following error:
```
ERROR: setUpClass (__main__.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 179, in __init__
    self._current_user, self._current_role, self._current_user_settings = self.get_user(pythonify=True, expanded=True)
ValueError: not enough values to unpack (expected 3, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testlive_comprehensive.py", line 61, in setUpClass
    cls.admin_misp_connector = PyMISP(url, key, verifycert, debug=False)
  File "/var/www/MISP/PyMISP/pymisp/api.py", line 181, in __init__
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}')
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://188.34.194.18). Please make sure the API key and the URL are correct (http/https is required): not enough values to unpack (expected 3, got 1)
```

Should something be done about it?

**Comment by PascalChardon** [comment]
Hi @Sshahar,
How did you fix the issue?
BR

**Comment by Sshahar** [comment]
> Hi @Sshahar, How did you fix the issue? BR
Sorry, I don't seem to remember... :(

**Comment by oencarnacion** [comment]
The problem is that the MISP instance and the MYSQL are not establishing a connection. The steps I took to do this were the following:

With the file hosted on the misp user called mysql.txt I used the generated root password I went to my mysql instance and reset the root user by putting the password I saw in the file

How to reset the user:

/etc/init.d/mysql stop
mysqld_safe --skip-grant-tables &
mysql -u root
use mysql;
select PASSWORD("password from mysql.txt");
update user set authentication_string=PASSWORD("password from mysql.txt") where user'root';
update user set plugin = "mysql_native_password" where user='root';
quit;
/etc/init.d/mysql start
