### ISSUE TITLE
Add new user by command line

### ISSUE THREAD

**Issue by ojaschauhan** [MISP/MISP#7629]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       |  CentOS, 
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Support Questions
I am deploying MISP by cdk which automatically gets it into a SSO. So to access the portal I need my username password added to misp by command line or before deploying it. 

Need some clarity how I can do that.

1: How to add user by command line in misp
2: How to change default username password before deploying

**Comment by righel** [comment]
Hello @ojaschauhan,
1. You can only create the initial user via command line:
`/var/www/MISP/app/Console/cake userInit`
Otherwise if you want to create users programatically you will have to use the API, docs on that [here](https://www.misp-project.org/documentation/openapi.html#operation/addUser), or use PyMISP.
2. You can reset the default username password with the following command:
`/var/www/MISP/app/Console/cake Password admin@admin.test [password]`

Hope this helps.
