### ISSUE TITLE
Unable to install PyMISP on new MISP Installation

### ISSUE THREAD

**Issue by War10ck3** [MISP/MISP#7729]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Ubuntu
| OS version (client)       | 18.04 LTS
| PHP version               | 7.4
| MISP version / git hash   | Latest version downloadable from MISP repository
| Browser                   | Chrome/IE/Firefox

### Support Questions
Issue: Unable to install PyMISP on new MISP installation.
 
Command: “python3 setup.py install” didn’t run successfully.

Please suggest a feasible solution to resolve this issue.

Error: UI and CLI error attached.

![Error -1](https://user-images.githubusercontent.com/54234520/132184388-8ca399c3-fa28-412b-8375-8473978e3a05.png)
![Error -2](https://user-images.githubusercontent.com/54234520/132184394-9b23d28d-5ba3-42d7-9b9d-f3ab8a392ecf.png)
![Error -3](https://user-images.githubusercontent.com/54234520/132184396-cbbc7888-1c39-4d49-b2e5-925600e42736.png)
![Error -4](https://user-images.githubusercontent.com/54234520/132184398-511b9596-a340-497d-8280-466da0665e9e.png)

**Comment by Rafiot** [comment]
That last commit on PyMISP side should solve it (you will need to git pull). Note that this command is not in the install guide, does it comes from an other one we should update?\

And I see it is a fresh install, I strongly recommend you to use Ubuntu 20.04 instead of of 18.04. It will become important in 2022, when we will deprecate python 3.6 for python 3.8.
