### ISSUE TITLE
When install MISP docker, got "fatal: destination path '/var/www/MISP/app/files/scripts/python-cybox' already exists and is not an empty directory."

### ISSUE THREAD

**Issue by shirley815** [MISP/MISP#7838]
I try to install MISP with the latest version, but always got error message like "fatal: destination path '/var/www/MISP/app/files/scripts/python-cybox' already exists and is not an empty directory."

![image](https://user-images.githubusercontent.com/92505931/137265099-5b5e9f8d-8411-42ac-8fde-972be856e479.png)

Command use:
4. Install Docker Compose：
sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
Check version:  
docker-compose --version
5. Build MISP docker image:
a. Fetch files
$ git clone https://github.com/MISP/misp-docker
$ cd misp-docker
$ cp template.env .env
$ vi .env
b .Build the containers
$ docker-compose build
c .Run containers
$ docker-compose up

**Comment by righel** [comment]
Hello @shirley815 
Just pushed this fix: https://github.com/MISP/misp-docker/pull/134
Let me know if it works for you now.

**Comment by shirley815** [comment]
Hi @luciano, I tried fixed one, but got the other error, followed as below:
![image](https://user-images.githubusercontent.com/92505931/137425154-5a75a0bf-04c8-4fa0-9df6-df455720584e.png)

**Comment by righel** [comment]
Which docker version do you have installed? run docker --version
as of v17.09.0-ce (2017-12-07) the --chown flag should be available.

**Comment by Stefan249** [comment]
misp-modules don't startup anymore

**Comment by Stefan249** [comment]
Sorry for the short comment...
After clean docker setup the misp-modules do not start up.

Trying to restart the misp-modules lead to the following error:
root@1c276e926f88:/usr/local/src/misp-modules# sudo -u www-data /var/www/MISP/venv/bin/python /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -d
No module named 'pybgpranking'
2021-10-18 08:32:43,355 - misp-modules - INFO - Launch MISP modules server from current directory.
2021-10-18 08:32:43,357 - misp-modules - INFO - Helpers loaded cache.py 
2021-10-18 08:32:43,365 - misp-modules - WARNING - MISP modules apiosintds failed due to No module named 'apiosintDS'
2021-10-18 08:32:44,386 - misp-modules - INFO - MISP modules apivoid imported
2021-10-18 08:32:44,389 - misp-modules - WARNING - MISP modules assemblyline_query failed due to No module named 'assemblyline_client'
2021-10-18 08:32:44,391 - misp-modules - WARNING - MISP modules assemblyline_submit failed due to No module named 'assemblyline_client'
Backscatter.io library not installed.
2021-10-18 08:32:44,393 - misp-modules - INFO - MISP modules backscatter_io imported
2021-10-18 08:32:44,395 - misp-modules - WARNING - MISP modules bgpranking failed due to No module named 'pybgpranking'
dnspython3 in missing. use 'pip install dnspython3' to install it.

**Comment by Shannonwje** [comment]
Hello, I faced the same issue but while installing it in my Kali Linux

![image](https://user-images.githubusercontent.com/42537231/139210922-208e934c-f88a-4f38-9229-0adf092969d5.png)

The command I used within my Kali Linux 2020.4:
wget -O /tmp/misp-kali.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh && bash /tmp/misp-kali.sh

^^ this was what's provided by the documentation for installing into Kali

Can't seem to resolve this
