### ISSUE TITLE
Hi I'm trying to install misp where I'm getting error "destination path 'faup' already exists and is not an empty directory"

### ISSUE THREAD

**Issue by viveksis12** [MISP/MISP#7952]
## Please consider the following notes
- Critical security bugs can be reported, preferably PGP encrypted, by mail to: info@circl.lu
- Bug reports and feature requests can be filed as an issue on github: https://github.com/MISP/MISP/issues
- For interactive support please join the Gitter chat on: https://gitter.im/MISP/MISP

The official documentation of MISP can be found here: https://www.circl.lu/doc/misp/
We also periodically do user/admin/developer trainings and have our training material online: https://www.circl.lu/services/misp-training-materials/

Nevertheless you can of course file a Support request as an issue. Please be as precise as possible and fill the template as detailed as possible too.
Please remove this text until the line below. Thanks a lot.
--------8<------

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | MacOS, Win10, Ubuntu, ...
| PHP version               | 5.4, 5.5, 5.6, 7.0, 7.1... (if relevant)
| MISP version / git hash   | 2.4.XX, hash of the commit
| Browser                   | If applicable

### Logs, screenshots, configuration dump, ...
Pls consider the following
Hi I'm trying to install misp into ubuntu machine first it is installed properly then it's was giving "An internal error has caused" then I remove the directory of MISP and try to start reinstall misp but I've stucked at  "destination path 'faup' already exists and is not an empty directory" what should I do now ?

**Comment by iglocska** [comment]
Just removing the MISP directory will obviously cause some issues with the installer, in this case some of the dependencies you are trying to install already exist. You basically have three options:

1. Start from scratch with a clean reinstall
2. Remove the offending destination by reading the installation script and removing faup's installation directory
3. Manually install MISP by following what the install script does and omitting the steps that are already present (so just move on to the next line of instructions if you get an "already exists" message.

Hope this helps!

Also, if you ever run into an internal error in MISP, please don't just rm -rf the MISP directory - the reason for the exception is stored in your error log, normally found in /var/www/MISP/app/tmp/logs/error.log and is often caused by an easy to resolve misconfiguration.
