### ISSUE TITLE
BackgroundJobsTool->processUser() does not work on RHEL 7

### ISSUE THREAD

**Issue by RichieB2B** [MISP/MISP#8054]
The code uses either `/proc/$pid/status` or `ps`. Both are not allowed by SELinux. With Resque the userid was stored in Redis so there was no issue.
https://github.com/MISP/MISP/blob/d5fde923b49efe07e9e16eaa9baeb7c3b2af86b7/app/Lib/Tools/BackgroundJobsTool.php#L692-L701

**Comment by righel** [comment]
Originally it was built like this but for the sake of simplicity and having a single source of truth with `supervisord` API, it was removed.
Keeping the status in two separate places introduces more challenges and in my opinion it is better to delegate it to `supervisord`, unfortunately the API does not return the user running the process, so to keep current functionality we rely on additional system calls.

I believe when using the new background jobs back-end this is not an important check, as now the workers are entirely handled by `supervisord` and there is a `user=www-data/whatever` setting in the programs configuration which will mandate the user that runs the worker.

Thus, in case we cannot get the user of a given PID in more restrictive setups, I would remove the error message and just leave a warning that the check could not be performed due to missing information.

What do you think?

**Comment by RichieB2B** [comment]
Yes, that makes sense. It will be very hard/strange to run the workers as the wrong user using `supervisord`. In the old setup the sudo could be easily forgotten.

**Comment by matthieuxyz** [comment]
What would be the semanage command required to authorize httpd to read /proc and execute ps commands on a redhat system?
