### ISSUE TITLE
Howto send email from MISP

### ISSUE THREAD

**Issue by manosmustang** [MISP/MISP#8168]
Hello,

I am trying to find information on how/where to setup smtp server in order to send email from MISP to users.

Do I need to install an SMPT server on MISP server or I just have to configure the email.php under Config?

Thank you

**Comment by righel** [comment]
Hello @manosmustang 
By default MISP uses php runtime to send emails, you can adjust the settings in your `php.ini` configuration file. 
More info here: https://www.php.net/manual/en/mail.configuration.php

You can also edit `/var/www/MISP/app/Config/email.php` and replace the `$default` variable to replace the default behavior, for example:
```php
public $default = array(
		'transport' => 'Smtp',
		'host' => 'smtp.mailtrap.io',
		'port' => 2525,
		'username' => 'your_user',
		'password' => 'your_pass'
	);
```
But I only recommend this for debugging/development, not for a production environment setup.

Also check the `MISP.disable_emailing` setting is set to `false` in [http://MISP_HOST/servers/serverSettings/MISP](/servers/serverSettings/MISP)

Let me know if that helps.

**Comment by manosmustang** [comment]
Hi @righel ,

Why you do not recommend it for production?

At php.ini there is no username/psw for smtp server.

Thanks

**Comment by righel** [comment]
The config file `/var/www/MISP/app/Config/email.php` is tracked by git and any changes will create conflicts when you try to update your MISP instance, as it does a `git pull`.

You can add your auth parameters to servers sendmail configuration and it should work.

**Comment by manosmustang** [comment]
So next step is the configuration of Postfix

Thank you @righel

**Comment by test200000** [comment]
hello i did all this steps but i dont still get the email

**Comment by manosmustang** [comment]
Hi @test200000,

If you want to send email from MISP check this wiki. I have created [this](https://github.com/manosmustang/Various/wiki/MISP-E%E2%80%90mail-Configuration) after hours of struggling. 


Let me know if you have any issues

**Comment by manosmustang** [comment]
@test200000 r u OK with it?

**Comment by test200000** [comment]
Not yet, but the link was helpful i used O365 SMTP relay to set it up and I'm making some modifications before i test again.

**Comment by test200000** [comment]
@manosmustang i was able to see what the issue was. your document really helped too.

the issue i had was my docker install was not the full version that has the email module.

I used the [https://misp.github.io/MISP/xINSTALL.ubuntu2204](https://misp.github.io/MISP/xINSTALL.ubuntu2204) documentation to do the installation again.

then for my main.cf file i used the `# Set your domain and hostname
myhostname = put your host name
mydomain = put your domain
myorigin = $mydomain

# Outlook SMTP server
relayhost = [smtp.office365.com]:587

# Enable SASL authentication
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_tls_security_options = noanonymous

# Enable TLS encryption
smtp_use_tls = yes
smtp_tls_security_level = encrypt
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

# Network settings
inet_interfaces = all
mynetworks = 127.0.0.0/8
inet_protocols = ipv4

# Disable local recipient checking
local_recipient_maps =

# Remove any existing virtual alias maps
virtual_alias_maps =

# Set the sender_canonical_maps to empty
sender_canonical_maps = regexp:/etc/postfix/sender_canonical

` 

i also used the below for my sender canonical for it to send directly with the user i want `^.*$/    put your email address

`
