### ISSUE TITLE
Support: An Internal Error Has Occurred.  Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator. 

### ISSUE THREAD

**Issue by Airborne1974** [MISP/MISP#8212]
### Expected behavior

Hi,

expected behavior is to view event when clicked on it. 

### Actual behavior

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.

### Steps to reproduce

Login to misp. Try to open event.

### Version

2.4.155

### Operating System

CentOS

### Operating System version

7

### PHP version

7.2.24

### Browser

Firefox

### Browser version

97.0.2(64-bit)

### Relevant log output

```shell
2022-03-16 17:16:52 Error: [Error] Class 'DefaultWarning' not found
Request URL: /events/view/13915
Stack Trace:
#0 /var/www/MISP/app/Model/Behavior/EventWarningBehavior.php(18): EventWarningBehavior->__loadCustomWarningSystems()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(238): EventWarningBehavior->generateWarnings(Object(Event), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(829): BehaviorCollection->dispatchMethod(Object(Event), Array, Array)
#3 /var/www/MISP/app/Controller/EventsController.php(1609): Model->__call('generateWarning...', Array)
#4 /var/www/MISP/app/Controller/EventsController.php(1818): EventsController->__viewUI(Array, Array, false, NULL)
#5 [internal function]: EventsController->view('13915')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Could you update to the latest version and retry? Should work correctly now.

**Comment by Airborne1974** [comment]
It works now. Thank you very much.

**Comment by oencarnacion** [comment]
The problem is that the MISP instance and the MYSQL are not establishing a connection. The steps I took to do this were the following:

With the file hosted on the misp user called mysql.txt I used the generated root password I went to my mysql instance and reset the root user by putting the password I saw in the file

How to reset the user:

/etc/init.d/mysql stop
mysqld_safe --skip-grant-tables &
mysql -u root
use mysql;
select PASSWORD("password from mysql.txt");
update user set authentication_string=PASSWORD("password from mysql.txt") where user'root';
update user set plugin = "mysql_native_password" where user='root';
quit;
/etc/init.d/mysql start
