### ISSUE TITLE
Support: Help with command for Database

### ISSUE THREAD

**Issue by LumberJohn6** [MISP/MISP#8573]
### Support Questions

This should be a simple question, but I don't know enough about MySQL to solve it alone.
I'm having this issue with a mismatch in the database schema, and the wrench icon doesn't suggest a command.

![image](https://user-images.githubusercontent.com/90254449/189118449-9ecd899e-d730-4598-8b42-6f3dc822aec8.png)

I don't know if I should put the logs for this question, but from what I can see, there isn't any error or information helpful.
Any help is appreciated!

### MISP version

MISP 2.4.161

### Operating System

Ubuntu

### Operating System version

20.04.4 LTS

### PHP version

 7.4.3

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LumberJohn6** [comment]
I don't know if this helps, but here are the column diagnostics:

![image](https://user-images.githubusercontent.com/90254449/189655680-50ccd000-c364-41d1-875e-168371bb9940.png)

**Comment by UFOSmuggler** [comment]
firstly i'd like to note that these column diagnostics claim to be experimental and may highlight benign issues, so you may not need to take action, but i will answer anyway.

before undertaking any action i advise taking a backup first, or testing on a dev misp instance or something before touching a prod system.

two differences are visible for the ip column, what you have is not nullable and also not in utf8mb3_bin collation.  to correct both, the following should work:

`alter table logs modify ip varchar(45) character set utf8mb3 collate utf8mb3_bin not null default "";`

HOWEVER, looking at the table schema in the INSTALL/MYSQL.sql file for 2.4.161/162 it looks like the following:

```
--
-- Table structure for table `logs`
--

CREATE TABLE IF NOT EXISTS `logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` text CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `created` datetime NOT NULL,
  `model` varchar(80) COLLATE utf8_bin NOT NULL,
  `model_id` int(11) NOT NULL,
  `action` varchar(20) COLLATE utf8_bin NOT NULL,
  `user_id` int(11) NOT NULL,
  `change` text COLLATE utf8_bin,
  `email` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT "",
  `org` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT "",
  `description` text CHARACTER SET utf8 COLLATE utf8_bin,
  `ip` varchar(45) COLLATE utf8_bin NOT NULL DEFAULT "",
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
which suggests the following may be more appropriate:

`alter table logs modify ip varchar(45) not null default "";`

**Comment by LumberJohn6** [comment]
Thank you very much for the help!

> firstly i'd like to note that these column diagnostics claim to be experimental and may highlight benign issues, so you may not need to take action, but i will answer anyway.

Yeah I don't know if it is an actual error, because it doesn't seem to affect anything, or at least there are no new errors on my logs.
But still I would like to try and have a stable, working version of MISP with no errors.

Unfortunately, the commands you recommended both give me this error on MySQL:
![image](https://user-images.githubusercontent.com/90254449/189856569-064c9938-d500-4d9e-909e-7cc1137e7226.png)

**Comment by UFOSmuggler** [comment]
show us the output of `show create table logs`

**Comment by LumberJohn6** [comment]
> show us the output of `show create table logs`

Here are the create table logs:
![image](https://user-images.githubusercontent.com/90254449/190083383-9ac6d2e9-e52a-4551-9893-5681ce5d2094.png)

**Comment by UFOSmuggler** [comment]
cheers, i imagine you have some nulls in there.  give this a bash to get rid of the nulls:
`update logs set ip = "" where ip is null;`
then
`alter table logs modify ip varchar(45) not null default "";`

**Comment by LumberJohn6** [comment]
Cheers, thank you for the help!

Well, the first command ran through a lot of time, but it finally finished I think.
To check that I used the command `show processlist;` to see the running process until that one was finished.
Unfortunately, the second command still gives me the same error...
Any ideas?

**Comment by UFOSmuggler** [comment]
hmmm, weird.  before my previous post i changed my schema to match yours and chucked a few nulls in the ip column to check if that caused the error you were getting, which it did, so i figured it was a fair assumption.  

if it is still saying `ERROR 1265 (01000): Data truncated for column 'ip' at row 1` with emphasis on the "row 1", please show me what row one is:

`select * from logs limit 1;`

if it formats poorly try `select * from logs limit 1\G` to use vertical output

if it not row 1 any more, say it's row 100, try `select * from logs limit 99,1;`
since its a 0 based index in this case we subtract 1 from 100.

maybe also try specifying the collation explicitly, in case its trying to set it to something else:
`alter table logs modify ip varchar(45) collate utf8_bin not null default "";`

**Comment by LumberJohn6** [comment]
Hello, once again thank you for the help.

Using the command with a vertical output, I have this on the first row:
![image](https://user-images.githubusercontent.com/90254449/190356718-a28c5c24-c40a-4bd7-9c03-511302cea003.png)

I found out that all the IPs on the logs table are null...
I don't know if this is a problem or if its supposed to be that way

**Comment by UFOSmuggler** [comment]
yeah, when we attempt to make that column "not null", it can't, because of all the nulls.  the command i gave you earlier, `update logs set ip = "" where ip is null;` tries to turn all the nulls into the default "" (empty varchar), so that the `alter table logs modify ip varchar(45) collate utf8_bin not null default "";` command can succeed.

i guess that the execution of the `update logs set ip = "" where ip is null;` command didn't finish, as you have quite a lot of logs (looks like 45 million rows).  you could try running it again and verifying none of the ips are null any more, or truncate the logs table so its empty and then running `alter table logs modify ip varchar(45) collate utf8_bin not null default "";`

**Comment by LumberJohn6** [comment]
Thank you so much. You were right, the command didn't finish.
I let it run through the weekend, and today I ran the second command, which fixed the problem.
Once again thank you for all the help and patience!

**Comment by UFOSmuggler** [comment]
you're welcome mate, have a good one
