### ISSUE TITLE
Showing correlations per event in the index

### ISSUE THREAD

**Issue by adulau** [MISP/MISP#863]
Showing correlations per event in the index. Would it be possible to show the number of correlated attributes in the index of MISP? to directly spot the correlated events versus the uncorrelated ones.

**Comment by iglocska** [comment]
I've just pushed this but I ended up showing the number of events that correlate instead of the number of attributes - but in retrospect, not sure what would be more handy. Let me know if you'd like me to switch it.

So basically now it shows the number of events that an event correlates with, if it has 20 correlating attributes all leading to the same event it will show up as "1". 

The feature needs to be enabled by a site admin as it may have a hefty performance cost.

**Comment by iglocska** [comment]
Update: Testing it on the live instance it's actually pretty snappy, managed to do it in a single action for all events in one go so it's not bad at all!
