### ISSUE TITLE
Support: SimpleBackgroudJob / Worker can't fetch feeds due to Mysql missing

### ISSUE THREAD

**Issue by EvaYiYang** [MISP/MISP#8876]
### Support Questions

We have configured all the required settings for SimpleBackgoundJobs, and the workers are able to start shows green. 
However whenever we tried to fetch events from a feed, the worker stalled in the job lists, and ended up with the following error message in the log. 

```STDERR: Error: Database connection "Mysql" is missing, or could not be created.```

Further investigating into this Mysql connection error, we found it was caused by `SQLSTATE[HY000] [2002] Permission denied`. 
I'm not sure where to go after this. We are connecting a remote MySQL databse via sqlclient, the connection between server and db seems fine as MISP is able to display all events and show no issue with MySQL connection except this worker issue. 

Any help would be appreciated. Thanks in advance. 

### MISP version

2.4.159

### Operating System

Ubuntu 

### Operating System version

20.04

### PHP version

7.4

### Relevant log output

```shell
2023-01-19 09:34:07 Error: [JOB ID: 6a3d8ff4-b1ac-48bf-98b1-8f60736c23d3] - failed with error code 244. STDERR: Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#5 /var/www/MISP/app/Model/User.php(237): Model->getDataSource()
#6 [internal function]: User->__construct()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#11 /var/www/MISP/app/Console/Command/AppShell.php(35): Shell->initialize()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#14 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#15 {main}
. STDOUT: .
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zischan303** [comment]
Have you a solution? I have the same problem

**Comment by iglocska** [comment]
Check your database config file, you probably have it misconfigured (/var/www/MISP/app/Config/database.php by default).

Check if you can connect to mysql via the command line client

`mysql -h [host] -u [username] -p [database_name]` and enter the given password.

If it still doesn't work and you are running a distro with SELinux enabled, make sure that the `httpd_can_network_connect_db` directive is enabled.

If the issue specifically only affects the background worker, make sure that the config file is readable by the user running the background worker and that said user isn't blocked from accessing mysql. 

Also, considering that the issue simply states that the DB connection was rejected, please create a separate issue if you're running into this and the above solution didn't solve your issues, mostly because there are just too many causes for this to occur and lumping them into the same issue can be counter-productive as you probably need separate solutions beyond the above stated.
