### ISSUE TITLE
How to identify common attributes between events 

### ISSUE THREAD

**Issue by enzokrr** [MISP/MISP#8927]
### Support Questions

Hello again,
The solution that was given to me on my previous issue (#8925) does not work and the issue was closed directly, which is why I allow myself to reopen one.

I imported in my MISP instance a text file containing an IP address list (so I have an event containing a set of attributes each corresponding to an IP address).
I would like to identify the attributes of this event, which are also present in at least one other event in my organization.
Of course I have the "related events" panel on the right of my event, showing me which events have common attributes, but I don’t know how to identify these attributes.
![image](https://user-images.githubusercontent.com/126159148/220931926-fcef5668-5b96-451b-93ba-b4e5ec128984.png)
I can’t click the numbers, nothing happens:
![image](https://user-images.githubusercontent.com/126159148/220932203-d356f846-8844-42f8-bfb1-9b0ca00e2a64.png)

I specify that my event contains 7731 attributes (IP addresses) so I need something automated.

Thanks

### MISP version

2.4.121

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samitainio** [comment]
@enzokrr 

You first need to update your MISP instance and after that there will be a new feature available to you that does just the thing you are asking for:

Open the event you want to compare from and then:
1. Select the "Filtering tool"
2. Select the field "show" next to the "Correlations with event" and select the event you want to compare to
3. Finally select "Filter"

![image](https://user-images.githubusercontent.com/5585477/221431424-26d283a8-0b60-4ed4-8694-ef144a081158.png)

Other alternative is that you manually compare the attributes from your MySQL database but I think it would be much more convenient to update your MISP instance and just clickety-click from the user interface to get the results. If I would be updating that old MISP instance I would first make sure to take all proper backups of it before even attempting to update it since your current version is really old - v2.4.121 was released on Feb 10, 2020. Good luck!

**Comment by enzokrr** [comment]
@samitainio  Thanks for your answer !
