### ISSUE TITLE
MISP Edit Feeds from other organizations

### ISSUE THREAD

**Issue by eliassteiner** [MISP/MISP#9035]
The problem is that we receive various feeds from other organizations, and our analysts need to be able to adjust the IDS flag on these feeds. However, since these feeds come from other organizations, only site administrators can make changes to them. This poses a challenge for us, either to make all analysts site administrators or to find a way for analysts to adjust the IDS flag on the feeds without being site administrators.

Can someone help me?

**Comment by dwe2e** [comment]
We have the same issue!

**Comment by cvandeplas** [comment]
Editing IDS fields is to choose what should or shouldn't be exported to an IDS is not recommended. 
I would recommend to create a **local tag or taxonomy**, and use that one to mark events/attributes so that they can easily be excluded from your IDS exports. 

For example:
- myorg-ids:False
- myorg-ids:True
 
Bring a local tag, it will not be uploaded to other MISP instances.
You might want to keep an eye on external data coming in with this tag/taxonomy though.

**Comment by eliassteiner** [comment]
thank you for your awnser. this helps me
