### ISSUE TITLE
In need of PyMISP query information 

### ISSUE THREAD

**Issue by EdAtt** [MISP/MISP#9052]
### Support Questions

Can someone explain to me why a query run through the MISP UI is so much faster than a similar query run with PyMISP?  When I log into the main MISP main landing page UI, and select "Modify Filters" and then fill in the "Rule" with an organization & Organization name, then hit "Add" and "Apply", the resulting UI page is displayed in second or even subsecond time.  However, if I use PyMISP, and use this similar code, the response is in the 80 second response time area.

`
misp = PyMISP(misp_instance, misp_key, misp_verifycert, 'json')

start = datetime.datetime.now()
result = misp.search(controller='events', org="<org name>", limit=10)
end = datetime.datetime.now()

cmd_elapse = end - start
`

Is there another query that the UI is using?  If there is, can that query be duplicated with PyMISP?  Is there any way to get a similar response time using PyMISP? 

### MISP version

2.4.170

### Operating System

RedHat

### Operating System version

20.04

### PHP version

7.0

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rafiot** [comment]
The very short answer it to use the `search_index` method instead of `search`, and it will return the same output as you have on the index page (without the content of the events).

------------------

But getting events should not take that long, so let's try a couple of things.

Can you try to pass `page=1` and remove the `org=""` parameter? The index in the webpage will only get the metadata, and not the full event (including attributes/objects), so if you have gigantic events, it may take some time (you can pass `metadata=True` in order to skip the content of the event, it will give you the same output as the `search_index` call).

If it is still taking very long, can you check how big the events are?

**Comment by EdAtt** [comment]
Rafiot,
Thanks for your suggestion on using "search_index".  I ran it and the data came back in .094 seconds, .100 seconds and .099 seconds.  This is exactly what I was looking for.
