### ISSUE TITLE
Support: How get list of ip or domain without authentication ?

### ISSUE THREAD

**Issue by marsupdivers** [MISP/MISP#9160]
### Support Questions

Hi,
I'm a newbie in MISP project and i discover all the potential of the solution.
i have a little question.
How can i access to https://my-misp.com/attributes/text/download/domain/ without authentication ?

I would like to link this to my fortigate but i can't setup api on it, only basic authentication. how can i do ?

![image](https://github.com/MISP/MISP/assets/109803006/fb2e2724-0a34-4331-98d6-27abad6048bf)

### MISP version

2.4.172

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

all

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by iglocska** [comment]
Multiple things:

1. Don't use that endpoint, it's deprecated for a long time, you can instead use:
`/attributes/restSearch/returnFormat:text/type:domain` to achieve the same output using the modern API (all parameters are recommended to be POSTed as a JSON, but since that is tricky for you the above will do).

2.  For the authentication, please tell Fortigate to allow custom headers (for authentication especially) to be passed as otherwise you'll run into all sorts of issues :) With that said, this is obviously not something that will help you on the short term, so here's what you can do: 

Enable the setting `Security.allow_unsafe_apikey_named_para` in server settings -> security

After that you can pass your API key in the URL as a GET request such as this:

`https://path.to.your.misp/attributes/restSearch/returnFormat:text/type:domain/apikey:FOOBARBAZ`

Keep in mind, this is frowned upon and having apikeys in the URL is something that makes interception easier, so please understand the risks before enabling this, and keep hammering away at the fortigate folks!
