### ISSUE TITLE
Bug: Proposed search in Attributes panel from GUI shows an empty result

### ISSUE THREAD

**Issue by minisephirot** [MISP/MISP#9258]
### Actual behavior

I have an object in an event describing a process :
![image](https://github.com/MISP/MISP/assets/22344585/35e0a08f-a612-4e97-b4cc-2cb0b52708bc)

It correlated with other events, so I'm clicking on the magnifying glass to check it out:
![image](https://github.com/MISP/MISP/assets/22344585/5e31e021-2efa-4260-9056-0f6dc1cf605e)
The link points me to: _"https://<my_misp_url>/attributes/search/value:%25TEMP%25%5Ctmpzjk6ajsk%5Cinvoice.exe"_

It seems to me that IOCs that contains complex characters breaks the search functionality. 
- I've tried with the search attribute in POST and this gives me the exact same result
- RESTApi also returns 0 attributes

### Expected behavior

To me the expected behaviour should be that I get the IOC I searched for when I clicked on the glass.
That might have heavy implication with the backend's handling of the search's input (there could a light-weighted solution with search mode using "strict" string matching).

### Steps to reproduce

I've attached an export of my Object in case someone wanna try by themselves: [object.txt](https://github.com/MISP/MISP/files/12407077/object.txt)

1. Import the IOC i've joined in a MISP instance
2. Click on the magnifying glass to launch a search
3. The result should be 1 or more items but contains 0

There are workarounds like using subsets of what I want to match:
IOC: _%WINDIR%\syswow64\windowspowershell\v1.0\powershell.exe_
- OK: https://<my_misp_url>/attributes/search/value:%25%5Cpowershell.exe
- KO: https://<my_misp_url>/attributes/search/value:%250%5Cpowershell.exe

### Version

2.4.174

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.0

### Browser

Firefox

### Browser version

116.0.3

### Extra attachments

On the side note: the ordering of this template is confusion-inducing, describing how something should be before stating how they actually are and why they are problematic is -to me- confusing from an external reader point of view..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by righel** [comment]
Just leaving some notes here.
Searching by the value `%TEMP%\tmpzjk6ajsk\invoice.exe`, generated the following SQL query:
```sql
... WHERE ((`Attribute`.`value1` LIKE '%TEMP%\\tmpzjk6ajsk\\invoice.exe') OR (`Attribute`.`value2` LIKE '%TEMP%\\tmpzjk6ajsk\\invoice.exe'))
```
https://github.com/MISP/MISP/blob/4b6c6240ef8dda06b0f9048dd52dace48df9bda2/app/Model/AppModel.php#L3296-L3302

In this context the percent sign is not escaped properly an interpreted as a wildcard which results.

Applying `addcslashes($object['value'], '%_')` would change the result term to `\%TEMP\%\tmpzjk6ajsk\invoice.exe` would traduce the search should solve the issue in theory.
https://github.com/MISP/MISP/blob/4b6c6240ef8dda06b0f9048dd52dace48df9bda2/app/View/Elements/Events/View/attribute_correlations.ctp#L74-L82

But then, since the query does not start with `%` the query switches to an exact match (see `AppModel.php` snippet above)
```sql
... WHERE ((`Attribute`.`value1` = '\%TEMP\%\\tmpzjk6ajsk\\invoice.exe') OR (`Attribute`.`value2` = '\%TEMP\%\\tmpzjk6ajsk\\invoice.exe'))
```

**Comment by righel** [comment]
fixed in `develop` by https://github.com/MISP/MISP/commit/910fc39806430c89195b0db34e11f14f6cdfd469
will be included in the next release
