### ISSUE TITLE
Bug: Workflows fail without any meaningful explanation of why

### ISSUE THREAD

**Issue by Dave-0-0** [MISP/MISP#9344]
### Actual behavior

Created a simple workflow in MISP.  A webhook is supposed to execute when an event is published.

![misp1](https://github.com/MISP/MISP/assets/51136463/c073e247-4072-484d-bb0b-d37a9cc965c8)

When running the workflow an error appears.
![misp2](https://github.com/MISP/MISP/assets/51136463/e622d491-e6b3-4874-82f3-d05c648eacc1)

When looking at the HTTP Response: 

![misp3](https://github.com/MISP/MISP/assets/51136463/dd4a99e7-6558-44ae-b2ad-110af6a81b0a)

When clicking on the "Execution Logs", the application times out. 

We also tried updating MISP through its native utility, but that broke MISP and we had to restore from backup.

### Expected behavior

The webhook fires successfully. If it is not successful, an error is presented that gives direction on what went wrong or what to troubleshoot, instead of something generic. Execution logs are viewable without timing out.

### Steps to reproduce

1. Create a new workflow for when an event is published
2. Create a webhook. 
3. Condigure the webhook to point to an endpoint
4. Connect the workflow from step 1 to the webhook created in step 2. 
5. Make sure debug mode is on 
6. Press the blue "Run Workflow" button 
7. Enter some text (I used the word TEST) in the window that pops up
8. Press "Run Workflow" in the same window 

### Version

2.4.160

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4

### Browser

Chrome and MSEdge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mokaddem** [comment]
Hey @Dave-0-0,

Thanks for the detailed feedback.
Indeed, simply running the `Event publish` workflow without providing a valid input is not going to work. I've added 
2253338 (on the `develop` branch) more feedback so that you might know where things went wrong.

If you want to run your `publish` workflow, you have to provide the JSON of the Event you want to run it on. The easiest way to achieve that is to go in `/events/view/123` and append `.json` at the end to get the JSON format, so like this: `/events/view/123.json`. Then you only have to copy/paste it.

A better approach is to enable the `debug` mode and collect the original data sent while actually publishing an event.

I hope that helps!
