### ISSUE TITLE
HTTP 500 Error with brand new instance

### ISSUE THREAD

**Issue by xme** [MISP/MISP#970]
I just installed a brand new MISP (pull from github). When accessing the web interface, I got this:

2016-02-24 09:35:14 Error: Fatal Error (4): syntax error, unexpected '[' in [/var/www/MISP/app/Controller/EventsContr
oller.php, line 104]
2016-02-24 09:35:14 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(4, 'syntax erro

r, u...', '/var/www/MISP/a...', 104)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/MISP/a...', 104, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(933): call_user_func('ErrorHandler::h...', 4, 'syntax error, u

...', '/var/www/MISP/a...', 104, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

Any idea? (Setup made following /INSTALL/INSTALL.ubuntu1404.txt)

**Comment by iglocska** [comment]
Just wondering what PHP version are you on? It sounds like a syntax error
on direct access of an array element returned by a function

example function()[0]

which was not supported in PHP < 5.4 if I recall correctly. MISP 2.4
requires PHP 5.5+, so that could be causing this, though since you used the
Ubuntu 14.04 installation guide this is probably not the case.

Let me know if your PHP is newer than that and you still get that error!

**Comment by xme** [comment]
Good catch! Wrong PHP version... Tx!

**Comment by adulau** [comment]
Thanks for the feedback.
