### ISSUE TITLE
Bug: 2.4.194 Update breaks MISP - bookmarks- in database

### ISSUE THREAD

**Issue by elvidence** [MISP/MISP#9791]
### Actual behavior

When navigating MIPS pages, you get "An Internal Error Has Occurred.
Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator."

### Expected behavior

Should allow browser navigating pages 

### Steps to reproduce

Again this one is not easy to reproduce, as I have production and test machine. Test machine updated fine, but production failed. 

### Version

2.4.194

### Operating System

Ubuntu

### Operating System version

22.04

### PHP version

7.4

### Browser

Firefox

### Relevant log output

```shell
Error: [MissingTableException] Table bookmarks for model Bookmark was not found in datasource default.
Exception Attributes: array (
  'table' => 'bookmarks',
  'class' => 'Bookmark',
  'ds' => 'default',
)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elvidence** [comment]
There appears to be a missing BookmarksController.php file in the /var/www/MISP/app/Controller/ directory. Something may have prevented the file from being transferred or saved there. Permissions are correct, and no errors occurred during the update. I'll investigate further and let you know the results. This issue could be specific to my setup, as the staging environment machine updated without any problems.

Regarding release management, I suggest implementing two types of releases: **stable** and **experimental.** The stable release would maintain existing functionality and only include bug fixes. The experimental release would introduce new features for testing by enthusiastic users who can report any issues they encounter. Once or twice a year, the stable version could be upgraded with thoroughly tested new features (which may still include some bugs:).
This approach would allow for:

Maintaining a reliable version for production environments
Faster innovation and feedback on new features
Improved overall stability of the main release

**Comment by UFOSmuggler** [comment]
try `sudo -u www-data /var/www/MISP/app/Console/cake admin runUpdates` in case db table updates need to be run.  this will also clean the model cache.

edit: you could also try `sudo -u www-data /var/www/MISP/app/Console/cake admin setDatabaseVersion 60` to regress the recorded db version, so that the runUpdates command attempts to re-apply the db updates.  it doesn't actually check anything but the db_version key in the admin_settings table to determine whether or not an update is required, so if it erroneously sets it as up-to-date (ie v 127) it will forever skip that update.  setting it to something low should let it fix it, if this is the problem.

**Comment by elvidence** [comment]
Looks like the latest version  v2.4.194 (fcc1b112fa600f0a86cf1db1c43d15346fd55b18) worked with no issues.
